JUCE: ModifierKeys Class Reference
ModifierKeys Class Reference
juce_gui_basics » keyboard
Represents the state of the mouse buttons and modifier keys.
Public Types
enum Flags {
noModifiers = 0 , shiftModifier = 1 , ctrlModifier = 2 , altModifier = 4 ,
leftButtonModifier = 16 , rightButtonModifier = 32 , middleButtonModifier = 64 , commandModifier = 8 ,
popupMenuClickModifier = rightButtonModifier | ctrlModifier , allKeyboardModifiers = shiftModifier | ctrlModifier | altModifier | commandModifier , allMouseButtonModifiers = leftButtonModifier | rightButtonModifier | middleButtonModifier , ctrlAltCommandModifiers = ctrlModifier | altModifier | commandModifier
}
Flags that represent the different keys.
Public Member Functions
ModifierKeys ()=default
Creates a ModifierKeys object with no flags set.
ModifierKeys (int flags) noexcept
Creates a ModifierKeys object from a raw set of flags.
ModifierKeys (const ModifierKeys &)=default
Creates a copy of another object.
ModifierKeys & operator= (const ModifierKeys &)=default
Copies this object from another one.
bool isCommandDown () const noexcept
Checks whether the 'command' key flag is set (or 'ctrl' on Windows/Linux).
bool isPopupMenu () const noexcept
Checks whether the user is trying to launch a pop-up menu.
bool isLeftButtonDown () const noexcept
Checks whether the flag is set for the left mouse-button.
bool isRightButtonDown () const noexcept
Checks whether the flag is set for the right mouse-button.
bool isMiddleButtonDown () const noexcept
bool isAnyMouseButtonDown () const noexcept
Tests for any of the mouse-button flags.
bool isAnyModifierKeyDown () const noexcept
Tests for any of the modifier key flags.
bool isShiftDown () const noexcept
Checks whether the shift key's flag is set.
bool isCtrlDown () const noexcept
Checks whether the CTRL key's flag is set.
bool isAltDown () const noexcept
Checks whether the ALT key's flag is set.
ModifierKeys withOnlyMouseButtons () const noexcept
Returns a copy of only the mouse-button flags.
ModifierKeys withoutMouseButtons () const noexcept
Returns a copy of only the non-mouse flags.
bool operator== (const ModifierKeys other) const noexcept
bool operator!= (const ModifierKeys other) const noexcept
int getRawFlags () const noexcept
Returns the raw flags for direct testing.
ModifierKeys withoutFlags (int rawFlagsToClear) const noexcept
ModifierKeys withFlags (int rawFlagsToSet) const noexcept
bool testFlags (int flagsToTest) const noexcept
Tests a combination of flags and returns true if any of them are set.
int getNumMouseButtonsDown () const noexcept
Returns the total number of mouse buttons that are down.
Static Public Member Functions
static ModifierKeys getCurrentModifiers () noexcept
Creates a ModifierKeys object to represent the last-known state of the keyboard and mouse buttons.
static ModifierKeys getCurrentModifiersRealtime () noexcept
Creates a ModifierKeys object to represent the current state of the keyboard and mouse buttons.
Static Public Attributes
static ModifierKeys currentModifiers
This object represents the last-known state of the keyboard and mouse buttons.
Detailed Description
Represents the state of the mouse buttons and modifier keys.
This is used both by mouse events and by KeyPress objects to describe the state of keys such as shift, control, alt, etc.
See also
KeyPress, MouseEvent::mods
Member Enumeration Documentation
Flags
enum ModifierKeys::Flags
Flags that represent the different keys.
Enumerator
noModifiers
Indicates no modifier keys.
shiftModifier
Shift key flag.
ctrlModifier
CTRL key flag.
altModifier
ALT key flag.
leftButtonModifier
Left mouse button flag.
rightButtonModifier
Right mouse button flag.
middleButtonModifier
Middle mouse button flag.
commandModifier
Command key flag - on windows this is the same as the CTRL key flag.
popupMenuClickModifier
Popup menu flag - on windows this is the same as rightButtonModifier, on the Mac it's the same as (rightButtonModifier | ctrlModifier).
allKeyboardModifiers
Represents a combination of all the shift, alt, ctrl and command key modifiers.
allMouseButtonModifiers
Represents a combination of all the mouse buttons at once.
ctrlAltCommandModifiers
Represents a combination of all the alt, ctrl and command key modifiers.
Constructor & Destructor Documentation
ModifierKeys() [1/3]
ModifierKeys::ModifierKeys () default
Creates a ModifierKeys object with no flags set.
Referenced by getCurrentModifiers(), getCurrentModifiersRealtime(), ModifierKeys(), operator!=(), operator=(), operator==(), withFlags(), withOnlyMouseButtons(), withoutFlags(), and withoutMouseButtons().
ModifierKeys() [2/3]
ModifierKeys::ModifierKeys (int flags) noexcept
Creates a ModifierKeys object from a raw set of flags.
Parameters
flags to represent the keys that are down
See also
shiftModifier, ctrlModifier, altModifier, leftButtonModifier, rightButtonModifier, commandModifier, popupMenuClickModifier
ModifierKeys() [3/3]
ModifierKeys::ModifierKeys (const ModifierKeys &) default
Creates a copy of another object.
References ModifierKeys().
Member Function Documentation
operator=()
ModifierKeys & ModifierKeys::operator= (const ModifierKeys &) default
Copies this object from another one.
References ModifierKeys().
isCommandDown()
bool ModifierKeys::isCommandDown () const noexcept
Checks whether the 'command' key flag is set (or 'ctrl' on Windows/Linux).
This is a platform-agnostic way of checking for the operating system's preferred command-key modifier - so on the Mac it tests for the cmd key, on Windows/Linux, it's actually checking for the CTRL key.
References commandModifier, and testFlags().
Referenced by SelectedItemSet< SelectableItemType >::addToSelectionBasedOnModifiers(), and LassoComponent< SelectableItemType >::dragLasso().
isPopupMenu()
bool ModifierKeys::isPopupMenu () const noexcept
Checks whether the user is trying to launch a pop-up menu.
This checks for platform-specific modifiers that might indicate that the user is following the operating system's normal method of showing a pop-up menu.
So on Windows/Linux, this method is really testing for a right-click. On the Mac, it tests for either the CTRL key being down, or a right-click.
References popupMenuClickModifier, and testFlags().
Referenced by SelectedItemSet< SelectableItemType >::addToSelectionOnMouseDown().
isLeftButtonDown()
bool ModifierKeys::isLeftButtonDown () const noexcept
Checks whether the flag is set for the left mouse-button.
References leftButtonModifier, and testFlags().
isRightButtonDown()
bool ModifierKeys::isRightButtonDown () const noexcept
Checks whether the flag is set for the right mouse-button.
Note that for detecting popup-menu clicks, you should be using isPopupMenu() instead, as this is platform-independent (and makes your code more explanatory too).
References rightButtonModifier, and testFlags().
isMiddleButtonDown()
bool ModifierKeys::isMiddleButtonDown () const noexcept
References middleButtonModifier, and testFlags().
isAnyMouseButtonDown()
bool ModifierKeys::isAnyMouseButtonDown () const noexcept
Tests for any of the mouse-button flags.
References allMouseButtonModifiers, and testFlags().
isAnyModifierKeyDown()
bool ModifierKeys::isAnyModifierKeyDown () const noexcept
Tests for any of the modifier key flags.
References altModifier, commandModifier, ctrlModifier, shiftModifier, and testFlags().
isShiftDown()
bool ModifierKeys::isShiftDown () const noexcept
Checks whether the shift key's flag is set.
References shiftModifier, and testFlags().
Referenced by SelectedItemSet< SelectableItemType >::addToSelectionBasedOnModifiers(), and LassoComponent< SelectableItemType >::dragLasso().
isCtrlDown()
bool ModifierKeys::isCtrlDown () const noexcept
Checks whether the CTRL key's flag is set.
Remember that it's better to use the platform-agnostic routines to test for command-key and popup-menu modifiers.
See also
isCommandDown, isPopupMenu
References ctrlModifier, and testFlags().
isAltDown()
bool ModifierKeys::isAltDown () const noexcept
Checks whether the ALT key's flag is set.
References altModifier, and testFlags().
Referenced by LassoComponent< SelectableItemType >::dragLasso().
withOnlyMouseButtons()
ModifierKeys ModifierKeys::withOnlyMouseButtons () const nodiscard noexcept
Returns a copy of only the mouse-button flags.
References allMouseButtonModifiers, and ModifierKeys().
withoutMouseButtons()
ModifierKeys ModifierKeys::withoutMouseButtons () const nodiscard noexcept
Returns a copy of only the non-mouse flags.
References allMouseButtonModifiers, and ModifierKeys().
operator==()
bool ModifierKeys::operator== (const ModifierKeys other) const noexcept
References ModifierKeys().
operator!=()
bool ModifierKeys::operator!= (const ModifierKeys other) const noexcept
References ModifierKeys().
getRawFlags()
int ModifierKeys::getRawFlags () const noexcept
Returns the raw flags for direct testing.
withoutFlags()
ModifierKeys ModifierKeys::withoutFlags (int rawFlagsToClear) const nodiscard noexcept
References ModifierKeys().
withFlags()
ModifierKeys ModifierKeys::withFlags (int rawFlagsToSet) const nodiscard noexcept
References ModifierKeys().
testFlags()
bool ModifierKeys::testFlags (int flagsToTest) const noexcept
Tests a combination of flags and returns true if any of them are set.
Referenced by isAltDown(), isAnyModifierKeyDown(), isAnyMouseButtonDown(), isCommandDown(), isCtrlDown(), isLeftButtonDown(), isMiddleButtonDown(), isPopupMenu(), isRightButtonDown(), and isShiftDown().
getNumMouseButtonsDown()
int ModifierKeys::getNumMouseButtonsDown () const noexcept
Returns the total number of mouse buttons that are down.
getCurrentModifiers()
ModifierKeys ModifierKeys::getCurrentModifiers () static noexcept
Creates a ModifierKeys object to represent the last-known state of the keyboard and mouse buttons.
This method is here for backwards compatibility and there's no need to call it anymore, you should use the public currentModifiers member directly.
References currentModifiers, getCurrentModifiers(), and ModifierKeys().
Referenced by getCurrentModifiers().
getCurrentModifiersRealtime()
ModifierKeys ModifierKeys::getCurrentModifiersRealtime () static noexcept
Creates a ModifierKeys object to represent the current state of the keyboard and mouse buttons.
This method is here for backwards compatibility and you should call ComponentPeer::getCurrentModifiersRealtime() instead (which is what this method now does).
References ModifierKeys().
Member Data Documentation
currentModifiers
ModifierKeys ModifierKeys::currentModifiers static
This object represents the last-known state of the keyboard and mouse buttons.
Referenced by getCurrentModifiers().