JUCE: RelativePointPath::ElementBase Class Reference
RelativePointPath::ElementBase Class Reference abstract
juce_gui_basics » positioning
Base class for the elements that make up a RelativePointPath.
Public Member Functions
ElementBase (ElementType type)
virtual ~ElementBase ()=default
virtual void addToPath (Path &path, Expression::Scope *) const =0
virtual RelativePoint * getControlPoints (int &numPoints)=0
virtual ElementBase * clone () const =0
bool isDynamic ()
Public Attributes
const ElementType type
Detailed Description
Base class for the elements that make up a RelativePointPath.
Constructor & Destructor Documentation
ElementBase()
RelativePointPath::ElementBase::ElementBase (ElementType type)
References type.
Referenced by RelativePointPath::CloseSubPath::clone(), RelativePointPath::CubicTo::clone(), clone(), RelativePointPath::LineTo::clone(), RelativePointPath::QuadraticTo::clone(), and RelativePointPath::StartSubPath::clone().
~ElementBase()
virtual RelativePointPath::ElementBase::~ElementBase () virtual default
Member Function Documentation
addToPath()
virtual void RelativePointPath::ElementBase::addToPath (Path & path, Expression::Scope *) const pure virtual
Implemented in RelativePointPath::CloseSubPath, RelativePointPath::CubicTo, RelativePointPath::LineTo, RelativePointPath::QuadraticTo, and RelativePointPath::StartSubPath.
getControlPoints()
virtual RelativePoint * RelativePointPath::ElementBase::getControlPoints (int & numPoints) pure virtual
Implemented in RelativePointPath::CloseSubPath, RelativePointPath::CubicTo, RelativePointPath::LineTo, RelativePointPath::QuadraticTo, and RelativePointPath::StartSubPath.
clone()
virtual ElementBase * RelativePointPath::ElementBase::clone () const pure virtual
Implemented in RelativePointPath::CloseSubPath, RelativePointPath::CubicTo, RelativePointPath::LineTo, RelativePointPath::QuadraticTo, and RelativePointPath::StartSubPath.
References ElementBase().
isDynamic()
bool RelativePointPath::ElementBase::isDynamic ()
Member Data Documentation
type
const ElementType RelativePointPath::ElementBase::type
Referenced by ElementBase().