JUCE: ScrollBar Class Reference
ScrollBar Class Reference
juce_gui_basics » layout
A scrollbar component.
Classes
class Listener
A class for receiving events from a ScrollBar.
struct LookAndFeelMethods
This abstract base class is implemented by LookAndFeel classes to provide scrollbar-drawing functionality.
Public Types
enum ColourIds { backgroundColourId = 0x1000300 , thumbColourId = 0x1000400 , trackColourId = 0x1000401 }
A set of colour IDs to use to change the colour of various aspects of the component.
Public Types inherited from Component
enum class WindowControlKind {
client , caption , minimise , maximise ,
close , sizeTop , sizeLeft , sizeRight ,
sizeBottom , sizeTopLeft , sizeTopRight , sizeBottomLeft ,
sizeBottomRight
}
Types of control that are commonly found in windows, especially title-bars.
enum class FocusContainerType { none , focusContainer , keyboardFocusContainer }
A focus container type that can be passed to setFocusContainerType().
enum FocusChangeType { focusChangedByMouseClick , focusChangedByTabKey , focusChangedDirectly }
Enumeration used by the focusGained() and focusLost() methods.
enum class FocusChangeDirection { unknown , forward , backward }
Enumeration used by the focusGainedWithDirection() method.
Public Member Functions
ScrollBar (bool isVertical)
Creates a Scrollbar.
~ScrollBar () override
Destructor.
bool isVertical () const noexcept
Returns true if the scrollbar is vertical, false if it's horizontal.
void setOrientation (bool shouldBeVertical)
Changes the scrollbar's direction.
void setAutoHide (bool shouldHideWhenFullRange)
Tells the scrollbar whether to make itself invisible when not needed.
bool autoHides () const noexcept
Returns true if this scrollbar is set to auto-hide when its thumb is as big as its maximum range.
void setRangeLimits (Range< double > newRangeLimit, NotificationType notification=sendNotificationAsync)
Sets the minimum and maximum values that the bar will move between.
void setRangeLimits (double minimum, double maximum, NotificationType notification=sendNotificationAsync)
Sets the minimum and maximum values that the bar will move between.
Range< double > getRangeLimit () const noexcept
Returns the current limits on the thumb position.
double getMinimumRangeLimit () const noexcept
Returns the lower value that the thumb can be set to.
double getMaximumRangeLimit () const noexcept
Returns the upper value that the thumb can be set to.
bool setCurrentRange (Range< double > newRange, NotificationType notification=sendNotificationAsync)
Changes the position of the scrollbar's 'thumb'.
void setCurrentRange (double newStart, double newSize, NotificationType notification=sendNotificationAsync)
Changes the position of the scrollbar's 'thumb'.
void setCurrentRangeStart (double newStart, NotificationType notification=sendNotificationAsync)
Moves the bar's thumb position.
Range< double > getCurrentRange () const noexcept
Returns the current thumb range.
double getCurrentRangeStart () const noexcept
Returns the position of the top of the thumb.
double getCurrentRangeSize () const noexcept
Returns the current size of the thumb.
void setSingleStepSize (double newSingleStepSize) noexcept
Sets the amount by which the up and down buttons will move the bar.
double getSingleStepSize () const noexcept
Returns the current step size.
bool moveScrollbarInSteps (int howManySteps, NotificationType notification=sendNotificationAsync)
Moves the scrollbar by a number of single-steps.
bool moveScrollbarInPages (int howManyPages, NotificationType notification=sendNotificationAsync)
Moves the scroll bar up or down in pages.
bool scrollToTop (NotificationType notification=sendNotificationAsync)
Scrolls to the top (or left).
bool scrollToBottom (NotificationType notification=sendNotificationAsync)
Scrolls to the bottom (or right).
void setButtonRepeatSpeed (int initialDelayInMillisecs, int repeatDelayInMillisecs, int minimumDelayInMillisecs=-1)
Changes the delay before the up and down buttons autorepeat when they are held down.
void addListener (Listener *listener)
Registers a listener that will be called when the scrollbar is moved.
void removeListener (Listener *listener)
Deregisters a previously-registered listener.
bool keyPressed (const KeyPress &) override
Called when a key is pressed.
void mouseWheelMove (const MouseEvent &, const MouseWheelDetails &) override
Called when the mouse-wheel is moved.
void lookAndFeelChanged () override
Called to let the component react to a change in the look-and-feel setting.
void mouseDown (const MouseEvent &) override
Called when a mouse button is pressed.
void mouseDrag (const MouseEvent &) override
Called when the mouse is moved while a button is held down.
void mouseUp (const MouseEvent &) override
Called when a mouse button is released.
void paint (Graphics &) override
Components can override this method to draw their content.
void resized () override
Called when this component's size has been changed.
void parentHierarchyChanged () override
Called to indicate that the component's parents have changed.
void setVisible (bool) override
Makes the component visible or invisible.
std::unique_ptr< AccessibilityHandler > createAccessibilityHandler () override
Override this method to return a custom AccessibilityHandler for this component.
Public Member Functions inherited from Component
Component () noexcept
Creates a component.
~Component () override
Destructor.
Component (const String &componentName) noexcept
Creates a component, setting its name at the same time.
String getName () const noexcept
Returns the name of this component.
virtual void setName (const String &newName)
Sets the name of this component.
String getComponentID () const noexcept
Returns the ID string that was set by setComponentID().
void setComponentID (const String &newID)
Sets the component's ID string.
bool isVisible () const noexcept
Tests whether the component is visible or not.
virtual void visibilityChanged ()
Called when this component's visibility changes.
bool isShowing () const
Tests whether this component and all its parents are visible.
virtual void addToDesktop (int windowStyleFlags, void *nativeWindowToAttachTo=nullptr)
Makes this component appear as a window on the desktop.
void removeFromDesktop ()
If the component is currently showing on the desktop, this will hide it.
bool isOnDesktop () const noexcept
Returns true if this component is currently showing on the desktop.
ComponentPeer * getPeer () const
Returns the heavyweight window that contains this component.
virtual void userTriedToCloseWindow ()
For components on the desktop, this is called if the system wants to close the window.
virtual void minimisationStateChanged (bool isNowMinimised)
Called for a desktop component which has just been minimised or un-minimised.
virtual float getDesktopScaleFactor () const
Returns the default scale factor to use for this component when it is placed on the desktop.
void toFront (bool shouldAlsoGainKeyboardFocus)
Brings the component to the front of its siblings.
void toBack ()
Changes this component's z-order to be at the back of all its siblings.
void toBehind (Component *other)
Changes this component's z-order so that it's just behind another component.
void setAlwaysOnTop (bool shouldStayOnTop)
Sets whether the component should always be kept at the front of its siblings.
bool isAlwaysOnTop () const noexcept
Returns true if this component is set to always stay in front of its siblings.
int getX () const noexcept
Returns the x coordinate of the component's left edge.
int getY () const noexcept
Returns the y coordinate of the top of this component.
int getWidth () const noexcept
Returns the component's width in pixels.
int getHeight () const noexcept
Returns the component's height in pixels.
int getRight () const noexcept
Returns the x coordinate of the component's right-hand edge.
Point< int > getPosition () const noexcept
Returns the component's top-left position as a Point.
int getBottom () const noexcept
Returns the y coordinate of the bottom edge of this component.
Rectangle< int > getBounds () const noexcept
Returns this component's bounding box.
Rectangle< int > getLocalBounds () const noexcept
Returns the component's bounds, relative to its own origin.
Rectangle< int > getBoundsInParent () const noexcept
Returns the area of this component's parent which this component covers.
int getScreenX () const
Returns this component's x coordinate relative the screen's top-left origin.
int getScreenY () const
Returns this component's y coordinate relative the screen's top-left origin.
Point< int > getScreenPosition () const
Returns the position of this component's top-left corner relative to the screen's top-left.
Rectangle< int > getScreenBounds () const
Returns the bounds of this component, relative to the screen's top-left.
Point< int > getLocalPoint (const Component *sourceComponent, Point< int > pointRelativeToSourceComponent) const
Converts a point to be relative to this component's coordinate space.
Point< float > getLocalPoint (const Component *sourceComponent, Point< float > pointRelativeToSourceComponent) const
Converts a point to be relative to this component's coordinate space.
Rectangle< int > getLocalArea (const Component *sourceComponent, Rectangle< int > areaRelativeToSourceComponent) const
Converts a rectangle to be relative to this component's coordinate space.
Rectangle< float > getLocalArea (const Component *sourceComponent, Rectangle< float > areaRelativeToSourceComponent) const
Converts a rectangle to be relative to this component's coordinate space.
Point< int > localPointToGlobal (Point< int > localPoint) const
Converts a point relative to this component's top-left into a screen coordinate.
Point< float > localPointToGlobal (Point< float > localPoint) const
Converts a point relative to this component's top-left into a screen coordinate.
Rectangle< int > localAreaToGlobal (Rectangle< int > localArea) const
Converts a rectangle from this component's coordinate space to a screen coordinate.
Rectangle< float > localAreaToGlobal (Rectangle< float > localArea) const
Converts a rectangle from this component's coordinate space to a screen coordinate.
void setTopLeftPosition (int x, int y)
Moves the component to a new position.
void setTopLeftPosition (Point< int > newTopLeftPosition)
Moves the component to a new position.
void setTopRightPosition (int x, int y)
Moves the component to a new position.
void setTopRightPosition (Point< int >)
Moves the component to a new position.
void setSize (int newWidth, int newHeight)
Changes the size of the component.
void setBounds (int x, int y, int width, int height)
Changes the component's position and size.
void setBounds (Rectangle< int > newBounds)
Changes the component's position and size.
void setBoundsRelative (float proportionalX, float proportionalY, float proportionalWidth, float proportionalHeight)
Changes the component's position and size in terms of fractions of its parent's size.
void setBoundsRelative (Rectangle< float > proportionalArea)
Changes the component's position and size in terms of fractions of its parent's size.
void setBoundsInset (BorderSize< int > borders)
Changes the component's position and size based on the amount of space to leave around it.
void setBoundsToFit (Rectangle< int > targetArea, Justification justification, bool onlyReduceInSize)
Positions the component within a given rectangle, keeping its proportions unchanged.
void setCentrePosition (int x, int y)
Changes the position of the component's centre.
void setCentrePosition (Point< int > newCentrePosition)
Changes the position of the component's centre.
void setCentreRelative (float x, float y)
Changes the position of the component's centre.
void centreWithSize (int width, int height)
Changes the component's size and centres it within its parent.
void setTransform (const AffineTransform &transform)
Sets a transform matrix to be applied to this component.
AffineTransform getTransform () const
Returns the transform that is currently being applied to this component.
bool isTransformed () const noexcept
Returns true if a non-identity transform is being applied to this component.
int proportionOfWidth (float proportion) const noexcept
Returns a proportion of the component's width.
int proportionOfHeight (float proportion) const noexcept
Returns a proportion of the component's height.
int getParentWidth () const noexcept
Returns the width of the component's parent.
int getParentHeight () const noexcept
Returns the height of the component's parent.
Rectangle< int > getParentMonitorArea () const
Returns the screen coordinates of the monitor that contains this component.
int getNumChildComponents () const noexcept
Returns the number of child components that this component contains.
Component * getChildComponent (int index) const noexcept
Returns one of this component's child components, by it index.
int getIndexOfChildComponent (const Component *child) const noexcept
Returns the index of this component in the list of child components.
const Array< Component * > & getChildren () const noexcept
Provides access to the underlying array of child components.
Component * findChildWithID (StringRef componentID) const noexcept
Looks for a child component with the specified ID.
void addChildComponent (Component *child, int zOrder=-1)
Adds a child component to this one.
void addChildComponent (Component &child, int zOrder=-1)
Adds a child component to this one.
void addAndMakeVisible (Component *child, int zOrder=-1)
Adds a child component to this one, and also makes the child visible if it isn't already.
void addAndMakeVisible (Component &child, int zOrder=-1)
Adds a child component to this one, and also makes the child visible if it isn't already.
void addChildAndSetID (Component *child, const String &componentID)
Adds a child component to this one, makes it visible, and sets its component ID.
void removeChildComponent (Component *childToRemove)
Removes one of this component's child-components.
Component * removeChildComponent (int childIndexToRemove)
Removes one of this component's child-components by index.
void removeAllChildren ()
Removes all this component's children.
void deleteAllChildren ()
Removes and deletes all of this component's children.
Component * getParentComponent () const noexcept
Returns the component which this component is inside.
template<class TargetClass>
TargetClass * findParentComponentOfClass () const
Searches the parent components for a component of a specified class.
Component * getTopLevelComponent () const noexcept
Returns the highest-level component which contains this one or its parents.
bool isParentOf (const Component *possibleChild) const noexcept
Checks whether a component is anywhere inside this component or its children.
virtual void childrenChanged ()
Subclasses can use this callback to be told when children are added or removed, or when their z-order changes.
virtual bool hitTest (int x, int y)
Tests whether a given point is inside the component.
virtual WindowControlKind findControlAtPoint (Point< float >) const
For components that are added to the desktop, this may be called to determine what kind of control is at particular locations in the window.
virtual void windowControlClickedClose ()
For components that are added to the desktop, this may be called to indicate that the mouse was clicked inside the area of the "close" control.
virtual void windowControlClickedMinimise ()
For components that are added to the desktop, this may be called to indicate that the mouse was clicked inside the area of the "minimise" control.
virtual void windowControlClickedMaximise ()
For components that are added to the desktop, this may be called to indicate that the mouse was clicked inside the area of the "maximise" control.
void setInterceptsMouseClicks (bool allowClicksOnThisComponent, bool allowClicksOnChildComponents) noexcept
Changes the default return value for the hitTest() method.
void getInterceptsMouseClicks (bool &allowsClicksOnThisComponent, bool &allowsClicksOnChildComponents) const noexcept
Retrieves the current state of the mouse-click interception flags.
bool contains (Point< int > localPoint)
Returns true if a given point lies within this component or one of its children.
bool contains (Point< float > localPoint)
Returns true if a given point lies within this component or one of its children.
bool reallyContains (Point< int > localPoint, bool returnTrueIfWithinAChild)
Returns true if a given point lies in this component, taking any overlapping siblings into account.
bool reallyContains (Point< float > localPoint, bool returnTrueIfWithinAChild)
Returns true if a given point lies in this component, taking any overlapping siblings into account.
Component * getComponentAt (int x, int y)
Returns the component at a certain point within this one.
Component * getComponentAt (Point< int > position)
Returns the component at a certain point within this one.
Component * getComponentAt (Point< float > position)
Returns the component at a certain point within this one.
void repaint ()
Marks the whole component as needing to be redrawn.
void repaint (int x, int y, int width, int height)
Marks a subsection of this component as needing to be redrawn.
void repaint (Rectangle< int > area)
Marks a subsection of this component as needing to be redrawn.
void setBufferedToImage (bool shouldBeBuffered)
Makes the component use an internal buffer to optimise its redrawing.
Image createComponentSnapshot (Rectangle< int > areaToGrab, bool clipImageToComponentBounds=true, float scaleFactor=1.0f, const ImageType &imageType=NativeImageType{})
Generates a snapshot of part of this component.
void paintEntireComponent (Graphics &context, bool ignoreAlphaLevel)
Draws this component and all its subcomponents onto the specified graphics context.
void setPaintingIsUnclipped (bool shouldPaintWithoutClipping) noexcept
This allows you to indicate that this component doesn't require its graphics context to be clipped when it is being painted.
bool isPaintingUnclipped () const noexcept
Returns true if this component doesn't require its graphics context to be clipped when it is being painted.
void setComponentEffect (ImageEffectFilter *newEffect)
Adds an effect filter to alter the component's appearance.
ImageEffectFilter * getComponentEffect () const noexcept
Returns the current component effect.
LookAndFeel & getLookAndFeel () const noexcept
Finds the appropriate look-and-feel to use for this component.
void setLookAndFeel (LookAndFeel *newLookAndFeel)
Sets the look and feel to use for this component.
FontOptions withDefaultMetrics (FontOptions opt) const
Returns a copy of the FontOptions with the default metrics kind from the component's LookAndFeel.
void sendLookAndFeelChange ()
Calls the methods repaint(), lookAndFeelChanged(), and colourChanged() in this component and all its children recursively.
void setOpaque (bool shouldBeOpaque)
Indicates whether any parts of the component might be transparent.
bool isOpaque () const noexcept
Returns true if no parts of this component are transparent.
void setBroughtToFrontOnMouseClick (bool shouldBeBroughtToFront) noexcept
Indicates whether the component should be brought to the front when clicked.
bool isBroughtToFrontOnMouseClick () const noexcept
Indicates whether the component should be brought to the front when clicked-on.
void setExplicitFocusOrder (int newFocusOrderIndex)
Sets the focus order of this component.
int getExplicitFocusOrder () const
Returns the focus order of this component, if one has been specified.
void setFocusContainerType (FocusContainerType containerType) noexcept
Sets whether this component is a container for components that can have their focus traversed, and the type of focus traversal that it supports.
bool isFocusContainer () const noexcept
Returns true if this component has been marked as a focus container.
bool isKeyboardFocusContainer () const noexcept
Returns true if this component has been marked as a keyboard focus container.
Component * findFocusContainer () const
Returns the focus container for this component.
Component * findKeyboardFocusContainer () const
Returns the keyboard focus container for this component.
void setWantsKeyboardFocus (bool wantsFocus) noexcept
Sets a flag to indicate whether this component wants keyboard focus or not.
bool getWantsKeyboardFocus () const noexcept
Returns true if the component is interested in getting keyboard focus.
void setMouseClickGrabsKeyboardFocus (bool shouldGrabFocus)
Chooses whether a click on this component automatically grabs the focus.
bool getMouseClickGrabsKeyboardFocus () const noexcept
Returns the last value set with setMouseClickGrabsKeyboardFocus().
void grabKeyboardFocus ()
Tries to give keyboard focus to this component.
void giveAwayKeyboardFocus ()
If this component or any of its children currently have the keyboard focus, this will defocus it, send a focus change notification, and try to pass the focus to the next component.
bool hasKeyboardFocus (bool trueIfChildIsFocused) const
Returns true if this component currently has the keyboard focus.
void moveKeyboardFocusToSibling (bool moveToNext)
Tries to move the keyboard focus to one of this component's siblings.
virtual std::unique_ptr< ComponentTraverser > createFocusTraverser ()
Creates a ComponentTraverser object to determine the logic by which focus should be passed from this component.
virtual std::unique_ptr< ComponentTraverser > createKeyboardFocusTraverser ()
Creates a ComponentTraverser object to use to determine the logic by which keyboard focus should be passed from this component.
void setHasFocusOutline (bool hasFocusOutline) noexcept
Use this to indicate that the component should have an outline drawn around it when it has keyboard focus.
bool hasFocusOutline () const noexcept
Returns true if this component should have a focus outline.
bool isEnabled () const noexcept
Returns true if the component (and all its parents) are enabled.
void setEnabled (bool shouldBeEnabled)
Enables or disables this component.
virtual void enablementChanged ()
Callback to indicate that this component has been enabled or disabled.
float getAlpha () const noexcept
Returns the component's current transparency level.
void setAlpha (float newAlpha)
Changes the transparency of this component.
virtual void alphaChanged ()
Called when setAlpha() is used to change the alpha value of this component.
void setMouseCursor (const MouseCursor &cursorType)
Changes the mouse cursor shape to use when the mouse is over this component.
virtual MouseCursor getMouseCursor ()
Returns the mouse cursor shape to use when the mouse is over this component.
void updateMouseCursor () const
Forces the current mouse cursor to be updated.
virtual void paintOverChildren (Graphics &g)
Components can override this method to draw over the top of their children.
void mouseMove (const MouseEvent &event) override
Called when the mouse moves inside a component.
void mouseEnter (const MouseEvent &event) override
Called when the mouse first enters a component.
void mouseExit (const MouseEvent &event) override
Called when the mouse moves out of a component.
void mouseDoubleClick (const MouseEvent &event) override
Called when a mouse button has been double-clicked on a component.
void mouseMagnify (const MouseEvent &event, float scaleFactor) override
Called when a pinch-to-zoom mouse-gesture is used.
void setRepaintsOnMouseActivity (bool shouldRepaint) noexcept
Causes automatic repaints when the mouse enters or exits this component.
void addMouseListener (MouseListener *newListener, bool wantsEventsForAllNestedChildComponents)
Registers a listener to be told when mouse events occur in this component.
void removeMouseListener (MouseListener *listenerToRemove)
Deregisters a mouse listener.
void addKeyListener (KeyListener *newListener)
Adds a listener that wants to hear about keypresses that this component receives.
void removeKeyListener (KeyListener *listenerToRemove)
Removes a previously-registered key listener.
virtual bool keyStateChanged (bool isKeyDown)
Called when a key is pressed or released.
virtual void modifierKeysChanged (const ModifierKeys &modifiers)
Called when a modifier key is pressed or released.
virtual void focusGained (FocusChangeType cause)
Called to indicate that this component has just acquired the keyboard focus.
virtual void focusGainedWithDirection (FocusChangeType cause, FocusChangeDirection direction)
Called to indicate that this component has just acquired the keyboard focus.
virtual void focusLost (FocusChangeType cause)
Called to indicate that this component has just lost the keyboard focus.
virtual void focusOfChildComponentChanged (FocusChangeType cause)
Called to indicate a change in whether or not this component is the parent of the currently-focused component.
bool isMouseOver (bool includeChildren=false) const
Returns true if the mouse is currently over this component.
bool isMouseButtonDown (bool includeChildren=false) const
Returns true if the mouse button is currently held down in this component.
bool isMouseOverOrDragging (bool includeChildren=false) const
True if the mouse is over this component, or if it's being dragged in this component.
Point< int > getMouseXYRelative () const
Returns the mouse's current position, relative to this component.
virtual void moved ()
Called when this component's position has been changed.
virtual void childBoundsChanged (Component *child)
Called when one of this component's children is moved or resized.
virtual void parentSizeChanged ()
Called when this component's immediate parent has been resized.
virtual void broughtToFront ()
Called when this component has been moved to the front of its siblings.
void addComponentListener (ComponentListener *newListener)
Adds a listener to be told about changes to the component hierarchy or position.
void removeComponentListener (ComponentListener *listenerToRemove)
Removes a component listener.
void postCommandMessage (int commandId)
Dispatches a numbered message to this component.
virtual void handleCommandMessage (int commandId)
Called to handle a command that was sent by postCommandMessage().
int runModalLoop ()
Runs a component modally, waiting until the loop terminates.
void enterModalState (bool takeKeyboardFocus=true, ModalComponentManager::Callback *callback=nullptr, bool deleteWhenDismissed=false)
Puts the component into a modal state.
void exitModalState (int returnValue=0)
Ends a component's modal state.
bool isCurrentlyModal (bool onlyConsiderForemostModalComponent=true) const noexcept
Returns true if this component is the modal one.
bool isCurrentlyBlockedByAnotherModalComponent () const
Checks whether there's a modal component somewhere that's stopping this one from receiving messages.
virtual bool canModalEventBeSentToComponent (const Component *targetComponent)
When a component is modal, this callback allows it to choose which other components can still receive events.
virtual void inputAttemptWhenModal ()
Called when the user tries to click on a component that is blocked by another modal component.
NamedValueSet & getProperties () noexcept
Returns the set of properties that belong to this component.
const NamedValueSet & getProperties () const noexcept
Returns the set of properties that belong to this component.
Colour findColour (int colourID, bool inheritFromParent=false) const
Looks for a colour that has been registered with the given colour ID number.
void setColour (int colourID, Colour newColour)
Registers a colour to be used for a particular purpose.
void removeColour (int colourID)
If a colour has been set with setColour(), this will remove it.
bool isColourSpecified (int colourID) const
Returns true if the specified colour ID has been explicitly set for this component using the setColour() method.
void copyAllExplicitColoursTo (Component &target) const
This looks for any colours that have been specified for this component, and copies them to the specified target component.
virtual void colourChanged ()
This method is called when a colour is changed by the setColour() method, or when the look-and-feel is changed by the setLookAndFeel() or sendLookAndFeelChanged() methods.
void * getWindowHandle () const
Returns the underlying native window handle for this component.
Positioner * getPositioner () const noexcept
Returns the Positioner object that has been set for this component.
void setPositioner (Positioner *newPositioner)
Sets a new Positioner object for this component.
void setCachedComponentImage (CachedComponentImage *newCachedImage)
Gives the component a CachedComponentImage that should be used to buffer its painting.
CachedComponentImage * getCachedComponentImage () const noexcept
Returns the object that was set by setCachedComponentImage().
void invalidateCachedImageResources ()
Invalidates cached images, both in the CachedComponentImage (if any) and the image effect state.
void setViewportIgnoreDragFlag (bool ignoreDrag) noexcept
Sets a flag to indicate whether mouse drag events on this Component should be ignored when it is inside a Viewport with drag-to-scroll functionality enabled.
bool getViewportIgnoreDragFlag () const noexcept
Retrieves the current state of the Viewport drag-to-scroll functionality flag.
String getTitle () const noexcept
Returns the title text for this component.
void setTitle (const String &newTitle)
Sets the title for this component.
String getDescription () const noexcept
Returns the description for this component.
void setDescription (const String &newDescription)
Sets the description for this component.
String getHelpText () const noexcept
Returns the help text for this component.
void setHelpText (const String &newHelpText)
Sets the help text for this component.
void setAccessible (bool shouldBeAccessible)
Sets whether this component and its children are visible to accessibility clients.
bool isAccessible () const noexcept
Returns true if this component and its children are visible to accessibility clients.
AccessibilityHandler * getAccessibilityHandler ()
Returns the accessibility handler for this component, or nullptr if this component is not accessible.
void invalidateAccessibilityHandler ()
Invalidates the AccessibilityHandler that is currently being used for this component.
Public Member Functions inherited from MouseListener
virtual ~MouseListener ()=default
Destructor.
Public Member Functions inherited from AsyncUpdater
AsyncUpdater ()
Creates an AsyncUpdater object.
virtual ~AsyncUpdater ()
Destructor.
void triggerAsyncUpdate ()
Causes the callback to be triggered at a later time.
void cancelPendingUpdate () noexcept
This will stop any pending updates from happening.
void handleUpdateNowIfNeeded ()
If an update has been triggered and is pending, this will invoke it synchronously.
bool isUpdatePending () const noexcept
Returns true if there's an update callback in the pipeline.
Additional Inherited Members
Static Public Member Functions inherited from Component
static float JUCE_CALLTYPE getApproximateScaleFactorForComponent (const Component *targetComponent)
Returns the approximate scale factor for a given component by traversing its parent hierarchy and applying each transform and finally scaling this by the global scale factor.
static Component *JUCE_CALLTYPE getCurrentlyFocusedComponent () noexcept
Returns the component that currently has the keyboard focus.
static void JUCE_CALLTYPE unfocusAllComponents ()
If any component has keyboard focus, this will defocus it.
static void JUCE_CALLTYPE beginDragAutoRepeat (int millisecondsBetweenCallbacks)
Ensures that a non-stop stream of mouse-drag events will be sent during the current mouse-drag operation.
static bool JUCE_CALLTYPE isMouseButtonDownAnywhere () noexcept
Returns true if a mouse button is currently down.
static int JUCE_CALLTYPE getNumCurrentlyModalComponents () noexcept
Returns the number of components that are currently in a modal state.
static Component *JUCE_CALLTYPE getCurrentlyModalComponent (int index=0) noexcept
Returns one of the components that are currently modal.
Detailed Description
A scrollbar component.
To use a scrollbar, set up its total range using the setRangeLimits() method - this sets the range of values it can represent. Then you can use setCurrentRange() to change the position and size of the scrollbar's 'thumb'.
Registering a ScrollBar::Listener with the scrollbar will allow you to find out when the user moves it, and you can use the getCurrentRangeStart() to find out where they moved it to.
The scrollbar will adjust its own visibility according to whether its thumb size allows it to actually be scrolled.
For most purposes, it's probably easier to use a Viewport or ListBox instead of handling a scrollbar directly.
See also
ScrollBar::Listener
Member Enumeration Documentation
ColourIds
enum ScrollBar::ColourIds
A set of colour IDs to use to change the colour of various aspects of the component.
These constants can be used either via the Component::setColour(), or LookAndFeel::setColour() methods.
See also
Component::setColour, Component::findColour, LookAndFeel::setColour, LookAndFeel::findColour
Enumerator
backgroundColourId
The background colour of the scrollbar.
thumbColourId
A base colour to use for the thumb.
The look and feel will probably use variations on this colour.
trackColourId
A base colour to use for the slot area of the bar.
The look and feel will probably use variations on this colour.
Constructor & Destructor Documentation
ScrollBar()
ScrollBar::ScrollBar (bool isVertical)
Creates a Scrollbar.
Parameters
isVertical specifies whether the bar should be a vertical or horizontal
References isVertical().
Referenced by ScrollBar::LookAndFeelMethods::drawScrollbar(), ScrollBar::LookAndFeelMethods::drawScrollbarButton(), ScrollBar::LookAndFeelMethods::getMinimumScrollbarThumbSize(), ScrollBar::LookAndFeelMethods::getScrollbarButtonSize(), and ScrollBar::Listener::scrollBarMoved().
~ScrollBar()
ScrollBar::~ScrollBar () override
Destructor.
Member Function Documentation
isVertical()
bool ScrollBar::isVertical () const noexcept
Returns true if the scrollbar is vertical, false if it's horizontal.
Referenced by ScrollBar().
setOrientation()
void ScrollBar::setOrientation (bool shouldBeVertical)
Changes the scrollbar's direction.
You'll also need to resize the bar appropriately - this just changes its internal layout.
Parameters
shouldBeVertical true makes it vertical; false makes it horizontal.
setAutoHide()
void ScrollBar::setAutoHide (bool shouldHideWhenFullRange)
Tells the scrollbar whether to make itself invisible when not needed.
The default behaviour is for a scrollbar to become invisible when the thumb fills the whole of its range (i.e. when it can't be moved). Setting this value to false forces the bar to always be visible.
See also
autoHides()
autoHides()
bool ScrollBar::autoHides () const noexcept
Returns true if this scrollbar is set to auto-hide when its thumb is as big as its maximum range.
See also
setAutoHide
setRangeLimits() [1/2]
void ScrollBar::setRangeLimits (Range< double > newRangeLimit, NotificationType notification = sendNotificationAsync)
Sets the minimum and maximum values that the bar will move between.
The bar's thumb will always be constrained so that the entire thumb lies within this range.
Parameters
newRangeLimit the new range.
notification whether to send a notification of the change to listeners. A notification will only be sent if the range has changed.
See also
setCurrentRange
References sendNotificationAsync, and setRangeLimits().
Referenced by setRangeLimits(), and setRangeLimits().
setRangeLimits() [2/2]
void ScrollBar::setRangeLimits (double minimum, double maximum, NotificationType notification = sendNotificationAsync)
Sets the minimum and maximum values that the bar will move between.
The bar's thumb will always be constrained so that the entire thumb lies within this range.
Parameters
minimum the new range minimum.
maximum the new range maximum.
notification whether to send a notification of the change to listeners. A notification will only be sent if the range has changed.
See also
setCurrentRange
References sendNotificationAsync, and setRangeLimits().
getRangeLimit()
Range< double > ScrollBar::getRangeLimit () const noexcept
Returns the current limits on the thumb position.
See also
setRangeLimits
References getRangeLimit().
Referenced by getRangeLimit().
getMinimumRangeLimit()
double ScrollBar::getMinimumRangeLimit () const noexcept
Returns the lower value that the thumb can be set to.
This is the value set by setRangeLimits().
getMaximumRangeLimit()
double ScrollBar::getMaximumRangeLimit () const noexcept
Returns the upper value that the thumb can be set to.
This is the value set by setRangeLimits().
setCurrentRange() [1/2]
bool ScrollBar::setCurrentRange (Range< double > newRange, NotificationType notification = sendNotificationAsync)
Changes the position of the scrollbar's 'thumb'.
This sets both the position and size of the thumb - to just set the position without changing the size, you can use setCurrentRangeStart().
If this method call actually changes the scrollbar's position, it will trigger an asynchronous call to ScrollBar::Listener::scrollBarMoved() for all the listeners that are registered.
The notification parameter can be used to optionally send or inhibit a callback to any scrollbar listeners.
Returns
true if the range was changed, or false if nothing was changed.
See also
getCurrentRange. setCurrentRangeStart
References sendNotificationAsync.
setCurrentRange() [2/2]
void ScrollBar::setCurrentRange (double newStart, double newSize, NotificationType notification = sendNotificationAsync)
Changes the position of the scrollbar's 'thumb'.
This sets both the position and size of the thumb - to just set the position without changing the size, you can use setCurrentRangeStart().
Parameters
newStart the top (or left) of the thumb, in the range getMinimumRangeLimit() <= newStart <= getMaximumRangeLimit(). If the value is beyond these limits, it will be clipped.
newSize the size of the thumb, such that getMinimumRangeLimit() <= newStart + newSize <= getMaximumRangeLimit(). If the size is beyond these limits, it will be clipped.
notification specifies if and how a callback should be made to any listeners if the range actually changes
See also
setCurrentRangeStart, getCurrentRangeStart, getCurrentRangeSize
References sendNotificationAsync.
setCurrentRangeStart()
void ScrollBar::setCurrentRangeStart (double newStart, NotificationType notification = sendNotificationAsync)
Moves the bar's thumb position.
This will move the thumb position without changing the thumb size. Note that the maximum thumb start position is (getMaximumRangeLimit() - getCurrentRangeSize()).
If this method call actually changes the scrollbar's position, it will trigger an asynchronous call to ScrollBar::Listener::scrollBarMoved() for all the listeners that are registered.
See also
setCurrentRange
References sendNotificationAsync.
getCurrentRange()
Range< double > ScrollBar::getCurrentRange () const noexcept
Returns the current thumb range.
See also
getCurrentRange, setCurrentRange
getCurrentRangeStart()
double ScrollBar::getCurrentRangeStart () const noexcept
Returns the position of the top of the thumb.
See also
getCurrentRange, setCurrentRangeStart
getCurrentRangeSize()
double ScrollBar::getCurrentRangeSize () const noexcept
Returns the current size of the thumb.
See also
getCurrentRange, setCurrentRange
setSingleStepSize()
void ScrollBar::setSingleStepSize (double newSingleStepSize) noexcept
Sets the amount by which the up and down buttons will move the bar.
The value here is in terms of the total range, and is added or subtracted from the thumb position when the user clicks an up/down (or left/right) button.
getSingleStepSize()
double ScrollBar::getSingleStepSize () const noexcept
Returns the current step size.
See also
setSingleStepSize
moveScrollbarInSteps()
bool ScrollBar::moveScrollbarInSteps (int howManySteps, NotificationType notification = sendNotificationAsync)
Moves the scrollbar by a number of single-steps.
This will move the bar by a multiple of its single-step interval (as specified using the setSingleStepSize() method).
A positive value here will move the bar down or to the right, a negative value moves it up or to the left.
Parameters
howManySteps the number of steps to move the scrollbar
notification whether to send a notification of the change to listeners. A notification will only be sent if the position has changed.
Returns
true if the scrollbar's position actually changed.
References sendNotificationAsync.
moveScrollbarInPages()
bool ScrollBar::moveScrollbarInPages (int howManyPages, NotificationType notification = sendNotificationAsync)
Moves the scroll bar up or down in pages.
This will move the bar by a multiple of its current thumb size, effectively doing a page-up or down.
A positive value here will move the bar down or to the right, a negative value moves it up or to the left.
Parameters
howManyPages the number of pages to move the scrollbar
notification whether to send a notification of the change to listeners. A notification will only be sent if the position has changed.
Returns
true if the scrollbar's position actually changed.
References sendNotificationAsync.
scrollToTop()
bool ScrollBar::scrollToTop (NotificationType notification = sendNotificationAsync)
Scrolls to the top (or left).
This is the same as calling setCurrentRangeStart (getMinimumRangeLimit());
Parameters
notification whether to send a notification of the change to listeners. A notification will only be sent if the position has changed.
Returns
true if the scrollbar's position actually changed.
References sendNotificationAsync.
scrollToBottom()
bool ScrollBar::scrollToBottom (NotificationType notification = sendNotificationAsync)
Scrolls to the bottom (or right).
This is the same as calling setCurrentRangeStart (getMaximumRangeLimit() - getCurrentRangeSize());
Parameters
notification whether to send a notification of the change to listeners. A notification will only be sent if the position has changed.
Returns
true if the scrollbar's position actually changed.
References sendNotificationAsync.
setButtonRepeatSpeed()
void ScrollBar::setButtonRepeatSpeed (int initialDelayInMillisecs, int repeatDelayInMillisecs, int minimumDelayInMillisecs = -1)
Changes the delay before the up and down buttons autorepeat when they are held down.
For an explanation of what the parameters are for, see Button::setRepeatSpeed().
See also
Button::setRepeatSpeed
addListener()
void ScrollBar::addListener (Listener * listener)
Registers a listener that will be called when the scrollbar is moved.
removeListener()
void ScrollBar::removeListener (Listener * listener)
Deregisters a previously-registered listener.
keyPressed()
bool ScrollBar::keyPressed (const KeyPress & key) override virtual
Called when a key is pressed.
When a key is pressed, the component that has the keyboard focus will have this method called. Remember that a component will only be given the focus if its setWantsKeyboardFocus() method has been used to enable this.
If your implementation returns true, the event will be consumed and not passed on to any other listeners. If it returns false, the key will be passed to any KeyListeners that have been registered with this component. As soon as one of these returns true, the process will stop, but if they all return false, the event will be passed upwards to this component's parent, and so on.
The default implementation of this method does nothing and returns false.
See also
keyStateChanged, getCurrentlyFocusedComponent, addKeyListener
Reimplemented from Component.
mouseWheelMove()
void ScrollBar::mouseWheelMove (const MouseEvent & event, const MouseWheelDetails & wheel) override virtual
Called when the mouse-wheel is moved.
This callback is sent to the component that the mouse is over when the wheel is moved.
If not overridden, a component will forward this message to its parent, so that parent components can collect mouse-wheel messages that happen to child components which aren't interested in them. (Bear in mind that if you attach a component as a mouse-listener to other components, then those wheel moves will also end up calling this method and being passed up to the parents, which may not be what you intended to happen).
Parameters
event details about the mouse event
wheel details about the mouse wheel movement
Reimplemented from Component.
lookAndFeelChanged()
void ScrollBar::lookAndFeelChanged () override virtual
Called to let the component react to a change in the look-and-feel setting.
When the look-and-feel is changed for a component, this method, repaint(), and colourChanged() are called on the original component and all its children recursively.
It can also be triggered manually by the sendLookAndFeelChange() method, in case an application uses a LookAndFeel class that might have changed internally.
See also
sendLookAndFeelChange, getLookAndFeel
Reimplemented from Component.
mouseDown()
void ScrollBar::mouseDown (const MouseEvent & event) override virtual
Called when a mouse button is pressed.
The MouseEvent object passed in contains lots of methods for finding out which button was pressed, as well as which modifier keys (e.g. shift, ctrl) were held down at the time.
Once a button is held down, the mouseDrag method will be called when the mouse moves, until the button is released.
Parameters
event details about the position and status of the mouse event, including the source component in which it occurred
See also
mouseUp, mouseDrag, mouseDoubleClick, contains
Reimplemented from Component.
mouseDrag()
void ScrollBar::mouseDrag (const MouseEvent & event) override virtual
Called when the mouse is moved while a button is held down.
When a mouse button is pressed inside a component, that component receives mouseDrag callbacks each time the mouse moves, even if the mouse strays outside the component's bounds.
Parameters
event details about the position and status of the mouse event, including the source component in which it occurred
See also
mouseDown, mouseUp, mouseMove, contains, setDragRepeatInterval
Reimplemented from Component.
mouseUp()
void ScrollBar::mouseUp (const MouseEvent & event) override virtual
Called when a mouse button is released.
A mouseUp callback is sent to the component in which a button was pressed even if the mouse is actually over a different component when the button is released.
The MouseEvent object passed in contains lots of methods for finding out which buttons were down just before they were released.
Parameters
event details about the position and status of the mouse event, including the source component in which it occurred
See also
mouseDown, mouseDrag, mouseDoubleClick, contains
Reimplemented from Component.
paint()
void ScrollBar::paint (Graphics & g) override virtual
Components can override this method to draw their content.
The paint() method gets called when a region of a component needs redrawing, either because the component's repaint() method has been called, or because something has happened on the screen that means a section of a window needs to be redrawn.
Any child components will draw themselves over whatever this method draws. If you need to paint over the top of your child components, you can also implement the paintOverChildren() method to do this.
If you want to cause a component to redraw itself, this is done asynchronously - calling the repaint() method marks a region of the component as "dirty", and the paint() method will automatically be called sometime later, by the message thread, to paint any bits that need refreshing. In JUCE (and almost all modern UI frameworks), you never redraw something synchronously.
You should never need to call this method directly - to take a snapshot of the component you could use createComponentSnapshot() or paintEntireComponent().
Parameters
g the graphics context that must be used to do the drawing operations.
See also
repaint, paintOverChildren, Graphics
Reimplemented from Component.
resized()
void ScrollBar::resized () override virtual
Called when this component's size has been changed.
A component can implement this method to do things such as laying out its child components when its width or height changes.
The method is called synchronously as a result of the setBounds or setSize methods, so repeatedly changing a components size will repeatedly call its resized method (unlike things like repainting, where multiple calls to repaint are coalesced together).
If the component is a top-level window on the desktop, its size could also be changed by operating-system factors beyond the application's control.
See also
moved, setSize
Reimplemented from Component.
parentHierarchyChanged()
void ScrollBar::parentHierarchyChanged () override virtual
Called to indicate that the component's parents have changed.
When a component is added or removed from its parent, this method will be called on all of its children (recursively - so all children of its children will also be called as well).
Subclasses can override this if they need to react to this in some way.
See also
getParentComponent, isShowing, ComponentListener::componentParentHierarchyChanged
Reimplemented from Component.
setVisible()
void ScrollBar::setVisible (bool shouldBeVisible) override virtual
Makes the component visible or invisible.
This method will show or hide the component. Note that components default to being non-visible when first created. Also note that visible components won't be seen unless all their parent components are also visible.
This method will call visibilityChanged() and also componentVisibilityChanged() for any component listeners that are interested in this component.
Parameters
shouldBeVisible whether to show or hide the component
See also
isVisible, isShowing, visibilityChanged, ComponentListener::componentVisibilityChanged
Reimplemented from Component.
createAccessibilityHandler()
std::unique_ptr< AccessibilityHandler > ScrollBar::createAccessibilityHandler () override virtual
Override this method to return a custom AccessibilityHandler for this component.
The default implementation creates and returns a AccessibilityHandler object with an unspecified role, meaning that it will be visible to accessibility clients but without a specific role, action callbacks or interfaces. To control how accessibility clients see and interact with your component subclass AccessibilityHandler, implement the desired behaviours, and return an instance of it from this method in your component subclass.
The accessibility handler you return here is guaranteed to be destroyed before its Component, so it's safe to store and use a reference back to the Component inside the AccessibilityHandler if necessary.
This function should rarely be called directly. If you need to query a component's accessibility handler, it's normally better to call getAccessibilityHandler(). The exception to this rule is derived implementations of createAccessibilityHandler(), which may find it useful to call the base class implementation, and then wrap or modify the result.
See also
getAccessibilityHandler
Reimplemented from Component.
Referenced by Viewport::createScrollBarComponent().