JUCE: AccessibilityTextValueInterface Class Reference
AccessibilityTextValueInterface Class Reference abstract
juce_gui_basics » accessibility
A value interface that represents a text value.
Public Member Functions
bool isReadOnly () const override=0
Returns true if the value is read-only and cannot be modified by an accessibility client.
String getCurrentValueAsString () const override=0
Returns the current value.
void setValueAsString (const String &newValue) override=0
Sets the current value to a new value.
double getCurrentValue () const final
Returns the current value as a double.
void setValue (double newValue) final
Sets the current value to a new double value.
AccessibleValueRange getRange () const final
If this is a ranged value, this should return a valid AccessibleValueRange object representing the supported numerical range.
Public Member Functions inherited from AccessibilityValueInterface
virtual ~AccessibilityValueInterface ()=default
Destructor.
Detailed Description
A value interface that represents a text value.
Member Function Documentation
isReadOnly()
bool AccessibilityTextValueInterface::isReadOnly () const override pure virtual
Returns true if the value is read-only and cannot be modified by an accessibility client.
See also
setValueAsString
Implements AccessibilityValueInterface.
getCurrentValueAsString()
String AccessibilityTextValueInterface::getCurrentValueAsString () const override pure virtual
Returns the current value.
Implements AccessibilityValueInterface.
Referenced by getCurrentValue().
setValueAsString()
void AccessibilityTextValueInterface::setValueAsString (const String & newValue) override pure virtual
Sets the current value to a new value.
Implements AccessibilityValueInterface.
Referenced by setValue().
getCurrentValue()
double AccessibilityTextValueInterface::getCurrentValue () const final virtual
Returns the current value as a double.
Implements AccessibilityValueInterface.
References getCurrentValueAsString().
setValue()
void AccessibilityTextValueInterface::setValue (double newValue) final virtual
Sets the current value to a new double value.
Implements AccessibilityValueInterface.
References setValueAsString().
getRange()
AccessibleValueRange AccessibilityTextValueInterface::getRange () const final virtual
If this is a ranged value, this should return a valid AccessibleValueRange object representing the supported numerical range.
Implements AccessibilityValueInterface.