JUCE: PopupMenu::MenuItemIterator Class Reference
PopupMenu::MenuItemIterator Class Reference
juce_gui_basics » menus
Allows you to iterate through the items in a pop-up menu, and examine their properties.
Public Member Functions
MenuItemIterator (const PopupMenu &menu, bool searchRecursively=false)
Creates an iterator that will scan through the items in the specified menu.
~MenuItemIterator ()
Destructor.
bool next ()
Returns true if there is another item, and sets up all this object's member variables to reflect that item's properties.
Item & getItem () const
Returns a reference to the description of the current item.
Detailed Description
Allows you to iterate through the items in a pop-up menu, and examine their properties.
To use this, just create one and repeatedly call its next() method. When this returns true, all the member variables of the iterator are filled-out with information describing the menu item. When it returns false, the end of the list has been reached.
Constructor & Destructor Documentation
MenuItemIterator()
PopupMenu::MenuItemIterator::MenuItemIterator (const PopupMenu & menu, bool searchRecursively = false)
Creates an iterator that will scan through the items in the specified menu.
Be careful not to add any items to a menu while it is being iterated, or things could get out of step.
Parameters
menu the menu that needs to be scanned
searchRecursively if true, all submenus will be recursed into to do an exhaustive search
References PopupMenu::PopupMenu().
Referenced by getItem().
~MenuItemIterator()
PopupMenu::MenuItemIterator::~MenuItemIterator ()
Destructor.
Member Function Documentation
next()
bool PopupMenu::MenuItemIterator::next ()
Returns true if there is another item, and sets up all this object's member variables to reflect that item's properties.
getItem()
Item & PopupMenu::MenuItemIterator::getItem () const
Returns a reference to the description of the current item.
It is only valid to call this after next() has returned true!
References MenuItemIterator().