JUCE: TextLayout Class Reference
TextLayout Class Reference final
juce_graphics » fonts
A Pre-formatted piece of text, which may contain multiple fonts and colours.
Classes
class Glyph
A positioned glyph.
class Line
A line containing a sequence of glyph-runs.
class Run
A sequence of glyphs with a common font and colour.
Public Types
using iterator = DereferencingIterator< Line* const*>
using const_iterator = DereferencingIterator<const Line* const*>
Public Member Functions
TextLayout ()
Creates an empty layout.
TextLayout (const TextLayout &)
TextLayout & operator= (const TextLayout &)
TextLayout (TextLayout &&) noexcept
TextLayout & operator= (TextLayout &&) noexcept
~TextLayout ()
Destructor.
void createLayout (const AttributedString &, float maxWidth)
Creates a layout from the given attributed string.
void createLayout (const AttributedString &, float maxWidth, float maxHeight)
Creates a layout from the given attributed string, given some size constraints.
void createLayoutWithBalancedLineLengths (const AttributedString &, float maxWidth)
Creates a layout, attempting to choose a width which results in lines of a similar length.
void createLayoutWithBalancedLineLengths (const AttributedString &, float maxWidth, float maxHeight)
Creates a layout, attempting to choose a width which results in lines of a similar length.
void draw (Graphics &, Rectangle< float > area) const
Draws the layout within the specified area.
float getWidth () const noexcept
Returns the maximum width of the content.
float getHeight () const noexcept
Returns the maximum height of the content.
int getNumLines () const noexcept
Returns the number of lines in the layout.
Line & getLine (int index) const noexcept
Returns one of the lines.
void addLine (std::unique_ptr< Line >)
Adds a line to the layout.
void ensureStorageAllocated (int numLinesNeeded)
Pre-allocates space for the specified number of lines.
iterator begin ()
Returns an iterator over the lines of content.
const_iterator begin () const
const_iterator cbegin () const
iterator end ()
Returns an iterator over the lines of content.
const_iterator end () const
const_iterator cend () const
void recalculateSize ()
If you modify the TextLayout after creating it, call this to compute the new dimensions of the content.
Static Public Member Functions
static Rectangle< float > getStringBounds (const AttributedString &string)
This convenience function adds an AttributedString to a TextLayout and returns the bounding box of the text after shaping.
static Rectangle< float > getStringBounds (const Font &font, StringRef text)
This convenience function adds text to a TextLayout using the specified font and returns the bounding box of the text after shaping.
static float getStringWidth (const AttributedString &string)
This convenience function adds an AttributedString to a TextLayout and returns the bounding box of the text after shaping.
static float getStringWidth (const Font &font, StringRef text)
This convenience function adds text to a TextLayout using the specified font and returns the width of the bounding box of the text after shaping.
Detailed Description
A Pre-formatted piece of text, which may contain multiple fonts and colours.
A TextLayout is created from an AttributedString, and once created can be quickly drawn into a Graphics context.
See also
AttributedString
Member Typedef Documentation
iterator
using TextLayout::iterator = DereferencingIterator< Line* const*>
const_iterator
using TextLayout::const_iterator = DereferencingIterator<const Line* const*>
Constructor & Destructor Documentation
TextLayout() [1/3]
TextLayout::TextLayout ()
Creates an empty layout.
Having created a TextLayout, you can populate it using createLayout() or createLayoutWithBalancedLineLengths().
Referenced by getStringBounds(), operator=(), operator=(), TextLayout(), TextLayout(), and ~TextLayout().
TextLayout() [2/3]
TextLayout::TextLayout (const TextLayout &)
References TextLayout().
TextLayout() [3/3]
TextLayout::TextLayout (TextLayout &&) noexcept
References TextLayout().
~TextLayout()
TextLayout::~TextLayout ()
Destructor.
References TextLayout().
Member Function Documentation
operator=() [1/2]
TextLayout & TextLayout::operator= (const TextLayout &)
References TextLayout().
operator=() [2/2]
TextLayout & TextLayout::operator= (TextLayout &&) noexcept
References TextLayout().
createLayout() [1/2]
void TextLayout::createLayout (const AttributedString & , float maxWidth)
Creates a layout from the given attributed string.
This will replace any data that is currently stored in the layout.
References createLayout().
Referenced by createLayout(), createLayout(), and getStringBounds().
createLayout() [2/2]
void TextLayout::createLayout (const AttributedString & , float maxWidth, float maxHeight)
Creates a layout from the given attributed string, given some size constraints.
This will replace any data that is currently stored in the layout.
References createLayout().
createLayoutWithBalancedLineLengths() [1/2]
void TextLayout::createLayoutWithBalancedLineLengths (const AttributedString & , float maxWidth)
Creates a layout, attempting to choose a width which results in lines of a similar length.
This will be slower than the normal createLayout method, but produces a tidier result.
References createLayoutWithBalancedLineLengths().
Referenced by createLayoutWithBalancedLineLengths(), and createLayoutWithBalancedLineLengths().
createLayoutWithBalancedLineLengths() [2/2]
void TextLayout::createLayoutWithBalancedLineLengths (const AttributedString & , float maxWidth, float maxHeight)
Creates a layout, attempting to choose a width which results in lines of a similar length.
This will be slower than the normal createLayout method, but produces a tidier result.
References createLayoutWithBalancedLineLengths().
draw()
void TextLayout::draw (Graphics & , Rectangle< float > area) const
Draws the layout within the specified area.
The position of the text within the rectangle is controlled by the justification flags set in the original AttributedString that was used to create this layout.
References draw().
Referenced by draw().
getWidth()
float TextLayout::getWidth () const noexcept
Returns the maximum width of the content.
References getWidth().
Referenced by getWidth().
getHeight()
float TextLayout::getHeight () const noexcept
Returns the maximum height of the content.
getNumLines()
int TextLayout::getNumLines () const noexcept
Returns the number of lines in the layout.
Referenced by getStringBounds().
getLine()
Line & TextLayout::getLine (int index) const noexcept
Returns one of the lines.
Referenced by getStringBounds().
addLine()
void TextLayout::addLine (std::unique_ptr< Line >)
Adds a line to the layout.
The layout will take ownership of this line object and will delete it when it is no longer needed.
ensureStorageAllocated()
void TextLayout::ensureStorageAllocated (int numLinesNeeded)
Pre-allocates space for the specified number of lines.
begin() [1/2]
iterator TextLayout::begin ()
Returns an iterator over the lines of content.
begin() [2/2]
const_iterator TextLayout::begin () const
cbegin()
const_iterator TextLayout::cbegin () const
end() [1/2]
iterator TextLayout::end ()
Returns an iterator over the lines of content.
end() [2/2]
const_iterator TextLayout::end () const
cend()
const_iterator TextLayout::cend () const
recalculateSize()
void TextLayout::recalculateSize ()
If you modify the TextLayout after creating it, call this to compute the new dimensions of the content.
getStringBounds() [1/2]
Rectangle< float > TextLayout::getStringBounds (const AttributedString & string) static
This convenience function adds an AttributedString to a TextLayout and returns the bounding box of the text after shaping.
The returned bounding box is positioned with its origin at the left end of the text's baseline.
References createLayout(), getLine(), TextLayout::Line::getLineBounds(), getNumLines(), and TextLayout().
Referenced by getStringBounds(), getStringWidth(), and getStringWidth().
getStringBounds() [2/2]
Rectangle< float > TextLayout::getStringBounds (const Font & font, StringRef text) static
This convenience function adds text to a TextLayout using the specified font and returns the bounding box of the text after shaping.
The returned bounding box is positioned with its origin at the left end of the text's baseline.
References AttributedString::append(), and getStringBounds().
getStringWidth() [1/2]
float TextLayout::getStringWidth (const AttributedString & string) static
This convenience function adds an AttributedString to a TextLayout and returns the bounding box of the text after shaping.
References getStringBounds().
getStringWidth() [2/2]
float TextLayout::getStringWidth (const Font & font, StringRef text) static
This convenience function adds text to a TextLayout using the specified font and returns the width of the bounding box of the text after shaping.
References getStringBounds().