JUCE: juce::midi_ci::SubscriptionKey Class Reference
juce::midi_ci::SubscriptionKey Class Reference
juce_midi_ci » ci
A key used to uniquely identify ongoing property subscriptions initiated by a ci::Device.
Public Member Functions
SubscriptionKey ()=default
Constructor.
SubscriptionKey (MUID muid, Token64 key)
Constructor.
MUID getMuid () const
Returns the muid of the device to which we are subscribed.
Token64 getKey () const
Returns an identifier unique to this subscription.
bool operator== (const SubscriptionKey &other) const
Equality operator.
bool operator!= (const SubscriptionKey &other) const
Inequality operator.
bool operator< (const SubscriptionKey &other) const
Less-than operator.
Detailed Description
A key used to uniquely identify ongoing property subscriptions initiated by a ci::Device.
Constructor & Destructor Documentation
SubscriptionKey() [1/2]
juce::midi_ci::SubscriptionKey::SubscriptionKey () default
Constructor.
Referenced by operator!=(), operator<(), and operator==().
SubscriptionKey() [2/2]
juce::midi_ci::SubscriptionKey::SubscriptionKey (MUID muid, Token64 key)
Constructor.
Member Function Documentation
getMuid()
MUID juce::midi_ci::SubscriptionKey::getMuid () const
Returns the muid of the device to which we are subscribed.
getKey()
Token64 juce::midi_ci::SubscriptionKey::getKey () const
Returns an identifier unique to this subscription.
operator==()
bool juce::midi_ci::SubscriptionKey::operator== (const SubscriptionKey & other) const
Equality operator.
References SubscriptionKey().
operator!=()
bool juce::midi_ci::SubscriptionKey::operator!= (const SubscriptionKey & other) const
Inequality operator.
References SubscriptionKey().
operator<()
bool juce::midi_ci::SubscriptionKey::operator< (const SubscriptionKey & other) const
Less-than operator.
References SubscriptionKey().