JUCE: MessageBoxOptions Class Reference
MessageBoxOptions Class Reference
juce_gui_basics » windows
Class used to create a set of options to pass to the AlertWindow and NativeMessageBox methods for showing dialog boxes.
Public Member Functions
MessageBoxOptions ()=default
MessageBoxOptions (const MessageBoxOptions &)=default
MessageBoxOptions & operator= (const MessageBoxOptions &)=default
MessageBoxOptions withIconType (MessageBoxIconType type) const
Sets the type of icon that should be used for the dialog box.
MessageBoxOptions withTitle (const String &boxTitle) const
Sets the title of the dialog box.
MessageBoxOptions withMessage (const String &boxMessage) const
Sets the message that should be displayed in the dialog box.
MessageBoxOptions withButton (const String &text) const
If the string passed in is not empty, this will add a button to the dialog box with the specified text.
MessageBoxOptions withAssociatedComponent (Component *component) const
The component that the dialog box should be associated with.
MessageBoxOptions withParentComponent (Component *component) const
The component that will contain the message box (e.g.
MessageBoxIconType getIconType () const noexcept
Returns the icon type of the dialog box.
String getTitle () const
Returns the title of the dialog box.
String getMessage () const
Returns the message of the dialog box.
int getNumButtons () const noexcept
Returns the number of buttons that have been added to the dialog box.
String getButtonText (int buttonIndex) const
Returns the text that has been set for one of the buttons of the dialog box.
Component * getAssociatedComponent () const noexcept
Returns the component that the dialog box is associated with.
Component * getParentComponent () const noexcept
Returns the component that will be used as the parent of the dialog box.
Static Public Member Functions
static MessageBoxOptions makeOptionsOk (MessageBoxIconType iconType, const String &title, const String &message, const String &buttonText=String(), Component *associatedComponent=nullptr)
Creates options suitable for a message box with a single button.
static MessageBoxOptions makeOptionsOkCancel (MessageBoxIconType iconType, const String &title, const String &message, const String &button1Text=String(), const String &button2Text=String(), Component *associatedComponent=nullptr)
Creates options suitable for a message box with two buttons.
static MessageBoxOptions makeOptionsYesNo (MessageBoxIconType iconType, const String &title, const String &message, const String &button1Text=String(), const String &button2Text=String(), Component *associatedComponent=nullptr)
Creates options suitable for a message box with two buttons.
static MessageBoxOptions makeOptionsYesNoCancel (MessageBoxIconType iconType, const String &title, const String &message, const String &button1Text=String(), const String &button2Text=String(), const String &button3Text=String(), Component *associatedComponent=nullptr)
Creates options suitable for a message box with three buttons.
Detailed Description
Class used to create a set of options to pass to the AlertWindow and NativeMessageBox methods for showing dialog boxes.
You can chain together a series of calls to this class's methods to create a set of whatever options you want to specify.
E.g.
AlertWindow::showAsync (MessageBoxOptions()
                          .withIconType (MessageBoxIconType::InfoIcon)
                          .withTitle ("A Title")
                          .withMessage ("A message.")
                          .withButton ("OK")
                          .withButton ("Cancel")
                          .withAssociatedComponent (myComp),
                        myCallback);
Constructor & Destructor Documentation
MessageBoxOptions() [1/2]
MessageBoxOptions::MessageBoxOptions () default
Referenced by makeOptionsOk(), makeOptionsOkCancel(), makeOptionsYesNo(), makeOptionsYesNoCancel(), MessageBoxOptions(), operator=(), withAssociatedComponent(), withButton(), withIconType(), withMessage(), withParentComponent(), and withTitle().
MessageBoxOptions() [2/2]
MessageBoxOptions::MessageBoxOptions (const MessageBoxOptions &) default
References MessageBoxOptions().
Member Function Documentation
operator=()
MessageBoxOptions & MessageBoxOptions::operator= (const MessageBoxOptions &) default
References MessageBoxOptions().
withIconType()
MessageBoxOptions MessageBoxOptions::withIconType (MessageBoxIconType type) const nodiscard
Sets the type of icon that should be used for the dialog box.
References MessageBoxOptions(), and withMember().
withTitle()
MessageBoxOptions MessageBoxOptions::withTitle (const String & boxTitle) const nodiscard
Sets the title of the dialog box.
References MessageBoxOptions(), and withMember().
withMessage()
MessageBoxOptions MessageBoxOptions::withMessage (const String & boxMessage) const nodiscard
Sets the message that should be displayed in the dialog box.
References MessageBoxOptions(), and withMember().
withButton()
MessageBoxOptions MessageBoxOptions::withButton (const String & text) const nodiscard
If the string passed in is not empty, this will add a button to the dialog box with the specified text.
Generally up to 3 buttons are supported for dialog boxes, so adding any more than this may have no effect.
References MessageBoxOptions().
withAssociatedComponent()
MessageBoxOptions MessageBoxOptions::withAssociatedComponent (Component * component) const nodiscard
The component that the dialog box should be associated with.
References Component, MessageBoxOptions(), and withMember().
withParentComponent()
MessageBoxOptions MessageBoxOptions::withParentComponent (Component * component) const nodiscard
The component that will contain the message box (e.g.
the AudioProcessorEditor in a plugin).
This will only affect JUCE AlertWindows. It won't affect the drawing of native message boxes. This is mainly intended for use in AU plugins, where opening additional windows can be problematic.
References Component, MessageBoxOptions(), and withMember().
getIconType()
MessageBoxIconType MessageBoxOptions::getIconType () const noexcept
Returns the icon type of the dialog box.
See also
withIconType
getTitle()
String MessageBoxOptions::getTitle () const
Returns the title of the dialog box.
See also
withTitle
getMessage()
String MessageBoxOptions::getMessage () const
Returns the message of the dialog box.
See also
withMessage
getNumButtons()
int MessageBoxOptions::getNumButtons () const noexcept
Returns the number of buttons that have been added to the dialog box.
See also
withButtonText
getButtonText()
String MessageBoxOptions::getButtonText (int buttonIndex) const
Returns the text that has been set for one of the buttons of the dialog box.
See also
withButtonText, getNumButtons
getAssociatedComponent()
Component * MessageBoxOptions::getAssociatedComponent () const noexcept
Returns the component that the dialog box is associated with.
See also
withAssociatedComponent
References Component.
getParentComponent()
Component * MessageBoxOptions::getParentComponent () const noexcept
Returns the component that will be used as the parent of the dialog box.
See also
withParentComponent
References Component.
makeOptionsOk()
MessageBoxOptions MessageBoxOptions::makeOptionsOk (MessageBoxIconType iconType, const String & title, const String & message, const String & buttonText = String(), Component * associatedComponent = nullptr) static
Creates options suitable for a message box with a single button.
If no button text is supplied, "OK" will be used.
References Component, and MessageBoxOptions().
Referenced by StandalonePluginHolder::askUserToLoadState(), and StandalonePluginHolder::askUserToSaveState().
makeOptionsOkCancel()
MessageBoxOptions MessageBoxOptions::makeOptionsOkCancel (MessageBoxIconType iconType, const String & title, const String & message, const String & button1Text = String(), const String & button2Text = String(), Component * associatedComponent = nullptr) static
Creates options suitable for a message box with two buttons.
If no button text is supplied, "OK" and "Cancel" will be used.
References Component, and MessageBoxOptions().
makeOptionsYesNo()
MessageBoxOptions MessageBoxOptions::makeOptionsYesNo (MessageBoxIconType iconType, const String & title, const String & message, const String & button1Text = String(), const String & button2Text = String(), Component * associatedComponent = nullptr) static
Creates options suitable for a message box with two buttons.
If no button text is supplied, "Yes" and "No" will be used.
References Component, and MessageBoxOptions().
makeOptionsYesNoCancel()
MessageBoxOptions MessageBoxOptions::makeOptionsYesNoCancel (MessageBoxIconType iconType, const String & title, const String & message, const String & button1Text = String(), const String & button2Text = String(), const String & button3Text = String(), Component * associatedComponent = nullptr) static
Creates options suitable for a message box with three buttons.
If no button text is supplied, "Yes", "No", and "Cancel" will be used.
References Component, InfoIcon, and MessageBoxOptions().