JUCE: ARARegionSequence Class Reference
ARARegionSequence Class Reference
juce_audio_processors » utilities
Base class representing an ARA region sequence.
Public Types
using PropertiesPtr = ARA::PlugIn::PropertiesPtr<ARA::ARARegionSequenceProperties>
using Listener = ARARegionSequenceListener
Public Member Functions
template<typename Document_t = ARADocument>
Document_t * getDocument () const noexcept
Returns the result of ARA::PlugIn::RegionSequence::getDocument() with the pointer cast to ARADocument*.
template<typename MusicalContext_t = ARAMusicalContext>
MusicalContext_t * getMusicalContext () const noexcept
Returns the result of ARA::PlugIn::RegionSequence::getMusicalContext() with the pointer cast to ARAMusicalContext*.
template<typename PlaybackRegion_t = ARAPlaybackRegion>
const std::vector< PlaybackRegion_t * > & getPlaybackRegions () const noexcept
Returns the result of ARA::PlugIn::RegionSequence::getPlaybackRegions() with the pointers within cast to ARAPlaybackRegion*.
size_t getNumChildren () const noexcept override
Returns the number of ARA model objects aggregated by this object.
ARAObject * getChild (size_t index) override
Returns the child object associated with the given index.
ARAObject * getParent () override
Returns the ARA model object that aggregates this object.
void visit (ARAObjectVisitor &visitor) override
Allows the retrieval of the concrete type of a model object.
Range< double > getTimeRange (ARAPlaybackRegion::IncludeHeadAndTail includeHeadAndTail=ARAPlaybackRegion::IncludeHeadAndTail::no) const
Returns the playback time range covered by the regions in this sequence.
double getCommonSampleRate () const
If all audio sources used by the playback regions in this region sequence have the same sample rate, this rate is returned here, otherwise 0.0 is returned.
Public Member Functions inherited from ARAListenableModelClass< ARARegionSequenceListener >
ARAListenableModelClass ()=default
Constructor.
virtual ~ARAListenableModelClass ()=default
Destructor.
void addListener (ARARegionSequenceListener *l)
Subscribe l to notified by changes to the object.
void removeListener (ARARegionSequenceListener *l)
Unsubscribe l from object notifications.
void notifyListeners (Callback &&callback)
Call the provided callback for each of the added listeners.
Public Member Functions inherited from ARAObject
virtual ~ARAObject ()=default
Destructor.
template<typename Fn>
void traverse (Fn &&fn)
Implements a depth first traversal of the ARA model graph starting from the current object, and visiting its children recursively.
Detailed Description
Base class representing an ARA region sequence.
Member Typedef Documentation
PropertiesPtr
using ARARegionSequence::PropertiesPtr = ARA::PlugIn::PropertiesPtr<ARA::ARARegionSequenceProperties>
Listener
using ARARegionSequence::Listener = ARARegionSequenceListener
Member Function Documentation
getDocument()
template<typename Document_t = ARADocument> Document_t * ARARegionSequence::getDocument () const noexcept
Returns the result of ARA::PlugIn::RegionSequence::getDocument() with the pointer cast to ARADocument*.
If you have overridden ARADocumentControllerSpecialisation::doCreateDocument(), then you can use the template parameter to cast the pointers to your subclass of ARADocument.
Referenced by getParent().
getMusicalContext()
template<typename MusicalContext_t = ARAMusicalContext> MusicalContext_t * ARARegionSequence::getMusicalContext () const noexcept
Returns the result of ARA::PlugIn::RegionSequence::getMusicalContext() with the pointer cast to ARAMusicalContext*.
If you have overridden ARADocumentControllerSpecialisation::doCreateMusicalContext(), then you can use the template parameter to cast the pointers to your subclass of ARAMusicalContext.
getPlaybackRegions()
template<typename PlaybackRegion_t = ARAPlaybackRegion> const std::vector< PlaybackRegion_t * > & ARARegionSequence::getPlaybackRegions () const noexcept
Returns the result of ARA::PlugIn::RegionSequence::getPlaybackRegions() with the pointers within cast to ARAPlaybackRegion*.
If you have overridden ARADocumentControllerSpecialisation::doCreatePlaybackRegion(), then you can use the template parameter to cast the pointers to your subclass of ARAPlaybackRegion.
getNumChildren()
size_t ARARegionSequence::getNumChildren () const override virtual noexcept
Returns the number of ARA model objects aggregated by this object.
Objects that are merely referred to, but not aggregated by the current object are not included in this count, e.g. a referenced RegionSequence does not count as a child of the referring PlaybackRegion.
See the ARA documentation's ARA Model Graph Overview for more details.
Implements ARAObject.
getChild()
ARAObject * ARARegionSequence::getChild (size_t index) override virtual
Returns the child object associated with the given index.
The index should be smaller than the value returned by getNumChildren().
Note that the index of a particular object may change when the ARA model graph is edited.
Implements ARAObject.
References getChild().
Referenced by getChild().
getParent()
ARAObject * ARARegionSequence::getParent () override virtual
Returns the ARA model object that aggregates this object.
Returns nullptr for the ARADocument root object.
Implements ARAObject.
References getDocument(), and getParent().
Referenced by getParent().
visit()
void ARARegionSequence::visit (ARAObjectVisitor & visitor) override virtual
Allows the retrieval of the concrete type of a model object.
To use this, create a new class derived from ARAObjectVisitor and override its functions depending on which concrete types you are interested in.
Calling this function inside the function passed to ARAObject::traverse() allows you to map the entire ARA model graph.
Implements ARAObject.
References ARAObjectVisitor::visitRegionSequence().
getTimeRange()
Range< double > ARARegionSequence::getTimeRange (ARAPlaybackRegion::IncludeHeadAndTail includeHeadAndTail = ARAPlaybackRegion::IncludeHeadAndTail::no) const
Returns the playback time range covered by the regions in this sequence.
Parameters
includeHeadAndTail Whether or not the range includes the playback region's head and tail time.
References ARAPlaybackRegion::no.
getCommonSampleRate()
double ARARegionSequence::getCommonSampleRate () const
If all audio sources used by the playback regions in this region sequence have the same sample rate, this rate is returned here, otherwise 0.0 is returned.
If the region sequence has no playback regions, this also returns 0.0.