JUCE: FontOptions Class Reference
FontOptions Class Reference final
juce_graphics » fonts
Options that describe a particular font.
Public Member Functions
FontOptions ()
Constructs the default set of options.
FontOptions (float fontHeight)
Constructs the default set of options with a custom height.
FontOptions (float fontHeight, int styleFlags)
Constructs the default set of options with a custom height and style.
FontOptions (const String &typefaceName, float fontHeight, int styleFlags)
Constructs the default set of options with a given typeface and parameters.
FontOptions (const String &typefaceName, const String &typefaceStyle, float fontHeight)
Constructs the default set of options with a given typeface and parameters.
FontOptions (const Typeface::Ptr &typeface)
Constructs the default set of options with a given typeface.
FontOptions withName (String x) const
Returns a copy of these options with a new typeface name.
FontOptions withStyle (String x) const
Returns a copy of these options with a new typeface style.
FontOptions withTypeface (Typeface::Ptr x) const
Returns a copy of these options with a new typeface.
FontOptions withFallbacks (std::vector< String > x) const
Returns a copy of these options with a new set of preferred fallback family names.
FontOptions withFallbackEnabled (bool x=true) const
Returns a copy of these options with font fallback enabled or disabled.
FontOptions withHeight (float x) const
Returns a copy of these options with the specified height in JUCE units (can be fractional).
FontOptions withPointHeight (float x) const
Returns a copy of these options with the specified height in points (can be fractional).
FontOptions withKerningFactor (float x) const
Returns a copy of these options with the specified extra kerning factor (also called "tracking").
FontOptions withHorizontalScale (float x) const
Returns a copy of these options with the specified horizontal scale factor, defaults to 1.0.
FontOptions withUnderline (bool x=true) const
Returns a copy of these options with underline enabled or disabled, defaults to disabled.
FontOptions withMetricsKind (TypefaceMetricsKind x) const
Returns a copy of these options with the specified metrics kind.
FontOptions withAscentOverride (std::optional< float > x) const
Returns a copy of these options with the specified font metrics value override.
FontOptions withDescentOverride (std::optional< float > x) const
Returns a copy of these options with the specified font metrics value override.
auto getName () const
auto getStyle () const
auto getTypeface () const
auto getFallbacks () const
auto getHeight () const
auto getPointHeight () const
auto getKerningFactor () const
auto getHorizontalScale () const
auto getFallbackEnabled () const
auto getUnderline () const
auto getMetricsKind () const
auto getAscentOverride () const
auto getDescentOverride () const
bool operator== (const FontOptions &other) const
Equality operator.
bool operator!= (const FontOptions &other) const
Inequality operator.
bool operator< (const FontOptions &other) const
Less-than operator.
bool operator<= (const FontOptions &other) const
Less-than-or-equal operator.
bool operator> (const FontOptions &other) const
Greater-than operator.
bool operator>= (const FontOptions &other) const
Greater-than-or-equal operator.
Detailed Description
Options that describe a particular font.
Used to construct Font instances in a fluent style.
See also
Typeface, Font
Constructor & Destructor Documentation
FontOptions() [1/6]
FontOptions::FontOptions ()
Constructs the default set of options.
Referenced by operator!=(), operator<(), operator<=(), operator==(), operator>(), operator>=(), withAscentOverride(), withDescentOverride(), withFallbackEnabled(), withFallbacks(), withHeight(), withHorizontalScale(), withKerningFactor(), withMetricsKind(), withName(), withPointHeight(), withStyle(), withTypeface(), and withUnderline().
FontOptions() [2/6]
FontOptions::FontOptions (float fontHeight) explicit
Constructs the default set of options with a custom height.
FontOptions() [3/6]
FontOptions::FontOptions (float fontHeight, int styleFlags)
Constructs the default set of options with a custom height and style.
Parameters
fontHeight the height in pixels (can be fractional)
styleFlags the style to use - this can be a combination of the Font::bold, Font::italic and Font::underlined, or just Font::plain for the normal style.
See also
Font::FontStyleFlags, Font::getDefaultSansSerifFontName
FontOptions() [4/6]
FontOptions::FontOptions (const String & typefaceName, float fontHeight, int styleFlags)
Constructs the default set of options with a given typeface and parameters.
Parameters
typefaceName the font family of the typeface to use
fontHeight the height in pixels (can be fractional)
styleFlags the style to use - this can be a combination of the Font::bold, Font::italic and Font::underlined, or just Font::plain for the normal style.
See also
Font::FontStyleFlags, Font::getDefaultSansSerifFontName
FontOptions() [5/6]
FontOptions::FontOptions (const String & typefaceName, const String & typefaceStyle, float fontHeight)
Constructs the default set of options with a given typeface and parameters.
Parameters
typefaceName the font family of the typeface to use
typefaceStyle the font style of the typeface to use
fontHeight the height in pixels (can be fractional)
FontOptions() [6/6]
FontOptions::FontOptions (const Typeface::Ptr & typeface)
Constructs the default set of options with a given typeface.
Member Function Documentation
withName()
FontOptions FontOptions::withName (String x) const nodiscard
Returns a copy of these options with a new typeface name.
If the options include a non-null Typeface::Ptr, this will be ignored. Otherwise, a suitable typeface will be located based on the typeface name and style strings.
References FontOptions(), jassertfalse, withMember(), and x.
Referenced by withTypeface().
withStyle()
FontOptions FontOptions::withStyle (String x) const nodiscard
Returns a copy of these options with a new typeface style.
If the options include a non-null Typeface::Ptr, this will be ignored. Otherwise, a suitable typeface will be located based on the typeface name and style strings.
References FontOptions(), jassertfalse, withMember(), and x.
withTypeface()
FontOptions FontOptions::withTypeface (Typeface::Ptr x) const nodiscard
Returns a copy of these options with a new typeface.
If the typeface is non-null, it takes precedence over the name and style strings.
References FontOptions(), jassert, withMember(), withName(), and x.
withFallbacks()
FontOptions FontOptions::withFallbacks (std::vector< String > x) const nodiscard
Returns a copy of these options with a new set of preferred fallback family names.
References FontOptions(), withMember(), and x.
withFallbackEnabled()
FontOptions FontOptions::withFallbackEnabled (bool x = true) const nodiscard
Returns a copy of these options with font fallback enabled or disabled.
References FontOptions(), withMember(), and x.
withHeight()
FontOptions FontOptions::withHeight (float x) const nodiscard
Returns a copy of these options with the specified height in JUCE units (can be fractional).
FontOptions can hold either a JUCE height, set via withHeight(), or a point height, set via withPointHeight(). After calling withHeight(), the result of getPointHeight() will be -1.0f to indicate that the point height is unset.
For more information about how JUCE font heights work, see Font::setHeight().
References FontOptions(), jassert, and x.
withPointHeight()
FontOptions FontOptions::withPointHeight (float x) const nodiscard
Returns a copy of these options with the specified height in points (can be fractional).
After calling withPointHeight(), the result of getHeight() will be -1.0f to indicate that the JUCE height is unset.
For more information about how point heights work, see Font::setPointHeight().
References FontOptions(), jassert, and x.
withKerningFactor()
FontOptions FontOptions::withKerningFactor (float x) const nodiscard
Returns a copy of these options with the specified extra kerning factor (also called "tracking").
References FontOptions(), withMember(), and x.
withHorizontalScale()
FontOptions FontOptions::withHorizontalScale (float x) const nodiscard
Returns a copy of these options with the specified horizontal scale factor, defaults to 1.0.
References FontOptions(), withMember(), and x.
withUnderline()
FontOptions FontOptions::withUnderline (bool x = true) const nodiscard
Returns a copy of these options with underline enabled or disabled, defaults to disabled.
References FontOptions(), withMember(), and x.
withMetricsKind()
FontOptions FontOptions::withMetricsKind (TypefaceMetricsKind x) const nodiscard
Returns a copy of these options with the specified metrics kind.
References FontOptions(), withMember(), and x.
Referenced by LookAndFeel::withDefaultMetrics().
withAscentOverride()
FontOptions FontOptions::withAscentOverride (std::optional< float > x) const nodiscard
Returns a copy of these options with the specified font metrics value override.
std::nullopt indicates that the font should use the built-in typeface metric; otherwise, the ascent value will be found by multiplying the provided value by the font size in points.
References FontOptions(), withMember(), and x.
withDescentOverride()
FontOptions FontOptions::withDescentOverride (std::optional< float > x) const nodiscard
Returns a copy of these options with the specified font metrics value override.
std::nullopt indicates that the font should use the built-in typeface metric; otherwise, the descent value will be found by multiplying the provided value by the font size in points.
References FontOptions(), withMember(), and x.
getName()
auto FontOptions::getName () const nodiscard
See also
withName()
getStyle()
auto FontOptions::getStyle () const nodiscard
See also
withStyle()
getTypeface()
auto FontOptions::getTypeface () const nodiscard
See also
withTypeface()
getFallbacks()
auto FontOptions::getFallbacks () const nodiscard
See also
withFallbacks()
getHeight()
auto FontOptions::getHeight () const nodiscard
See also
withHeight()
getPointHeight()
auto FontOptions::getPointHeight () const nodiscard
See also
withPointHeight()
getKerningFactor()
auto FontOptions::getKerningFactor () const nodiscard
See also
withKerningFactor()
getHorizontalScale()
auto FontOptions::getHorizontalScale () const nodiscard
See also
withHorizontalScale()
getFallbackEnabled()
auto FontOptions::getFallbackEnabled () const nodiscard
See also
withFallbackEnabled()
getUnderline()
auto FontOptions::getUnderline () const nodiscard
See also
withUnderline()
getMetricsKind()
auto FontOptions::getMetricsKind () const nodiscard
See also
withMetricsKind()
getAscentOverride()
auto FontOptions::getAscentOverride () const nodiscard
See also
withAscentOverride()
getDescentOverride()
auto FontOptions::getDescentOverride () const nodiscard
See also
withDescentOverride()
operator==()
bool FontOptions::operator== (const FontOptions & other) const nodiscard
Equality operator.
References FontOptions().
operator!=()
bool FontOptions::operator!= (const FontOptions & other) const nodiscard
Inequality operator.
References FontOptions().
operator<()
bool FontOptions::operator< (const FontOptions & other) const nodiscard
Less-than operator.
Allows FontOptions to be used as keys in a map.
References FontOptions().
operator<=()
bool FontOptions::operator<= (const FontOptions & other) const nodiscard
Less-than-or-equal operator.
References FontOptions().
operator>()
bool FontOptions::operator> (const FontOptions & other) const nodiscard
Greater-than operator.
References FontOptions().
operator>=()
bool FontOptions::operator>= (const FontOptions & other) const nodiscard
Greater-than-or-equal operator.
References FontOptions(), and portable.