JUCE: MidiDeviceListConnection Class Reference
MidiDeviceListConnection Class Reference
juce_audio_devices » midi_io
To find out when the available MIDI devices change, call MidiDeviceListConnection::make(), passing a lambda that will be called on each configuration change.
Public Types
using Key = uint64_t
Public Member Functions
MidiDeviceListConnection ()=default
Constructs an inactive connection.
MidiDeviceListConnection (const MidiDeviceListConnection &)=delete
MidiDeviceListConnection (MidiDeviceListConnection &&other) noexcept
MidiDeviceListConnection & operator= (const MidiDeviceListConnection &)=delete
MidiDeviceListConnection & operator= (MidiDeviceListConnection &&other) noexcept
~MidiDeviceListConnection () noexcept
void reset () noexcept
Clears this connection.
Static Public Member Functions
static MidiDeviceListConnection make (std::function< void()>)
Registers a function to be called whenever the midi device list changes.
Detailed Description
To find out when the available MIDI devices change, call MidiDeviceListConnection::make(), passing a lambda that will be called on each configuration change.
To stop the lambda receiving callbacks, destroy the MidiDeviceListConnection instance returned from make(), or call reset() on it.
// Start listening for configuration changes
auto connection = MidiDeviceListConnection::make ([]
{
    // This will print a message when devices are connected/disconnected
    DBG ("MIDI devices changed");
});
// Stop listening
connection.reset();
Member Typedef Documentation
Key
using MidiDeviceListConnection::Key = uint64_t
Constructor & Destructor Documentation
MidiDeviceListConnection() [1/3]
MidiDeviceListConnection::MidiDeviceListConnection () default
Constructs an inactive connection.
Referenced by make(), MidiDeviceListConnection(), MidiDeviceListConnection(), operator=(), operator=(), and reset().
MidiDeviceListConnection() [2/3]
MidiDeviceListConnection::MidiDeviceListConnection (const MidiDeviceListConnection &) delete
References MidiDeviceListConnection().
MidiDeviceListConnection() [3/3]
MidiDeviceListConnection::MidiDeviceListConnection (MidiDeviceListConnection && other) noexcept
References MidiDeviceListConnection().
~MidiDeviceListConnection()
MidiDeviceListConnection::~MidiDeviceListConnection () noexcept
Member Function Documentation
operator=() [1/2]
MidiDeviceListConnection & MidiDeviceListConnection::operator= (const MidiDeviceListConnection &) delete
References MidiDeviceListConnection().
operator=() [2/2]
MidiDeviceListConnection & MidiDeviceListConnection::operator= (MidiDeviceListConnection && other) noexcept
References MidiDeviceListConnection().
reset()
void MidiDeviceListConnection::reset () noexcept
Clears this connection.
If this object had an active connection, that connection will be deactivated, and the corresponding callback will be removed from the MidiDeviceListConnectionBroadcaster.
References MidiDeviceListConnection(), and reset().
Referenced by reset().
make()
MidiDeviceListConnection MidiDeviceListConnection::make (std::function< void()>) static
Registers a function to be called whenever the midi device list changes.
The callback will only be active for as long as the return MidiDeviceListConnection remains alive. To stop receiving device change notifications, destroy the Connection object, e.g. by allowing it to fall out of scope.
References MidiDeviceListConnection().