JUCE: files
files
juce_core
Namespaces
namespace juce
Classes
class AndroidDocumentInfo
Some information about a document.
class AndroidDocumentPermission
Represents a permission granted to an application to read and/or write to a particular document or tree.
class AndroidDocument
Provides access to a document on Android devices.
class AndroidDocumentIterator
An iterator that visits child documents in a directory.
class File
Represents a local file or directory.
struct File::NaturalFileComparator
Comparator for files.
class FileFilter
Interface for deciding which files are suitable for something.
class FileInputStream
An input stream that reads from a local file.
class FileOutputStream
An output stream that writes into a local file.
class FileSearchPath
Represents a set of folders that make up a search path.
class MemoryMappedFile
Maps a file into virtual memory for easy reading and/or writing.
class DirectoryEntry
Describes the attributes of a file or folder.
class RangedDirectoryIterator
Allows iterating over files and folders using C++11 range-for syntax.
class TemporaryFile
Manages a temporary file, which will be deleted when this object is deleted.
class WildcardFileFilter
A type of FileFilter that works by wildcard pattern matching.
Functions
const DirectoryEntry & operator* (const DirectoryEntry &e) noexcept
A convenience operator so that the expression *it++ works correctly when it is an instance of RangedDirectoryIterator.
RangedDirectoryIterator begin (const RangedDirectoryIterator &it)
Returns the iterator that was passed in.
RangedDirectoryIterator end (const RangedDirectoryIterator &)
Returns a default-constructed sentinel value.
Detailed Description
Function Documentation
operator*()
const DirectoryEntry & operator* (const DirectoryEntry & e) noexcept
A convenience operator so that the expression *it++ works correctly when it is an instance of RangedDirectoryIterator.
begin()
RangedDirectoryIterator begin (const RangedDirectoryIterator & it)
Returns the iterator that was passed in.
Provided for range-for compatibility.
Referenced by AudioProcessorValueTreeState::ParameterLayout::add(), MemoryBlock::end(), MemoryBlock::end(), String::end(), makeAnimationLimits(), makeRange(), operator==(), and AudioProcessorValueTreeState::ParameterLayout::ParameterLayout().
end()
RangedDirectoryIterator end (const RangedDirectoryIterator &)
Returns a default-constructed sentinel value.
Provided for range-for compatibility.
Referenced by AudioProcessorValueTreeState::ParameterLayout::add(), CodeDocument::findLineContaining(), CodeDocument::findTokenContaining(), StringPool::getPooledString(), CodeDocument::getTextBetween(), CharacterFunctions::lengthUpTo(), CharPointer_ASCII::lengthUpTo(), CharPointer_UTF16::lengthUpTo(), CharPointer_UTF32::lengthUpTo(), CharPointer_UTF8::lengthUpTo(), Path::lineTo(), makeAnimationLimits(), makeAnimationLimits(), makeRange(), operator==(), SparseSet< Type >::operator[](), AudioProcessorValueTreeState::ParameterLayout::ParameterLayout(), ListenerList< ListenerClass, ArrayType >::remove(), and CodeEditorComponent::selectRegion().