JUCE: TextEditor::LookAndFeelMethods Struct Reference
TextEditor::LookAndFeelMethods Struct Reference abstract
juce_gui_basics » widgets
This abstract base class is implemented by LookAndFeel classes to provide TextEditor drawing functionality.
Public Member Functions
virtual ~LookAndFeelMethods ()=default
virtual void fillTextEditorBackground (Graphics &, int width, int height, TextEditor &)=0
virtual void drawTextEditorOutline (Graphics &, int width, int height, TextEditor &)=0
virtual CaretComponent * createCaretComponent (Component *keyFocusOwner)=0
Detailed Description
This abstract base class is implemented by LookAndFeel classes to provide TextEditor drawing functionality.
Constructor & Destructor Documentation
~LookAndFeelMethods()
virtual TextEditor::LookAndFeelMethods::~LookAndFeelMethods () virtual default
Member Function Documentation
fillTextEditorBackground()
virtual void TextEditor::LookAndFeelMethods::fillTextEditorBackground (Graphics & , int width, int height, TextEditor &) pure virtual
Implemented in LookAndFeel_V2, and LookAndFeel_V4.
References TextEditor::TextEditor().
drawTextEditorOutline()
virtual void TextEditor::LookAndFeelMethods::drawTextEditorOutline (Graphics & , int width, int height, TextEditor &) pure virtual
Implemented in LookAndFeel_V1, LookAndFeel_V2, LookAndFeel_V3, and LookAndFeel_V4.
References TextEditor::TextEditor().
createCaretComponent()
virtual CaretComponent * TextEditor::LookAndFeelMethods::createCaretComponent (Component * keyFocusOwner) pure virtual
Implemented in LookAndFeel_V2.
References Component::Component().