JUCE: ResizableWindow::LookAndFeelMethods Struct Reference
ResizableWindow::LookAndFeelMethods Struct Reference abstract
juce_gui_basics » windows
This abstract base class is implemented by LookAndFeel classes to provide window drawing functionality.
Public Member Functions
virtual ~LookAndFeelMethods ()=default
virtual void drawCornerResizer (Graphics &, int w, int h, bool isMouseOver, bool isMouseDragging)=0
virtual void drawResizableFrame (Graphics &, int w, int h, const BorderSize< int > &)=0
virtual void fillResizableWindowBackground (Graphics &, int w, int h, const BorderSize< int > &, ResizableWindow &)=0
virtual void drawResizableWindowBorder (Graphics &, int w, int h, const BorderSize< int > &border, ResizableWindow &)=0
Detailed Description
This abstract base class is implemented by LookAndFeel classes to provide window drawing functionality.
Constructor & Destructor Documentation
~LookAndFeelMethods()
virtual ResizableWindow::LookAndFeelMethods::~LookAndFeelMethods () virtual default
Member Function Documentation
drawCornerResizer()
virtual void ResizableWindow::LookAndFeelMethods::drawCornerResizer (Graphics & , int w, int h, bool isMouseOver, bool isMouseDragging) pure virtual
Implemented in LookAndFeel_V1, and LookAndFeel_V2.
References h, Component::isMouseOver(), and w.
drawResizableFrame()
virtual void ResizableWindow::LookAndFeelMethods::drawResizableFrame (Graphics & , int w, int h, const BorderSize< int > &) pure virtual
Implemented in LookAndFeel_V2.
References h, and w.
fillResizableWindowBackground()
virtual void ResizableWindow::LookAndFeelMethods::fillResizableWindowBackground (Graphics & , int w, int h, const BorderSize< int > & , ResizableWindow &) pure virtual
Implemented in LookAndFeel_V2.
References h, ResizableWindow::ResizableWindow(), and w.
drawResizableWindowBorder()
virtual void ResizableWindow::LookAndFeelMethods::drawResizableWindowBorder (Graphics & , int w, int h, const BorderSize< int > & border, ResizableWindow &) pure virtual
Implemented in LookAndFeel_V2.
References h, ResizableWindow::ResizableWindow(), and w.