JUCE: juce::midi_ci::Message::PropertyGetData Struct Reference
juce::midi_ci::Message::PropertyGetData Struct Reference
juce_midi_ci » ci
See the MIDI-CI specification.
Public Member Functions
bool operator== (const PropertyGetData &x) const
bool operator!= (const PropertyGetData &x) const
Public Member Functions inherited from juce::midi_ci::Message::StaticSizePropertyExchange
auto tie () const
Additional Inherited Members
Public Attributes inherited from juce::midi_ci::Message::StaticSizePropertyExchange
std::byte requestID {}
Span< const std::byte > header
Detailed Description
See the MIDI-CI specification.
Member Function Documentation
operator==()
bool juce::midi_ci::Message::PropertyGetData::operator== (const PropertyGetData & x) const
References juce::midi_ci::Message::StaticSizePropertyExchange::tie(), and x.
Referenced by operator!=().
operator!=()
bool juce::midi_ci::Message::PropertyGetData::operator!= (const PropertyGetData & x) const
References operator==(), and x.