JUCE: juce::dsp::ProcessorDuplicator< MonoProcessorType, StateType > Struct Template Reference
juce::dsp::ProcessorDuplicator< MonoProcessorType, StateType > Struct Template Reference
juce_dsp » processors
Converts a mono processor class into a multi-channel version by duplicating it and applying multichannel buffers across an array of instances.
Public Member Functions
ProcessorDuplicator ()
ProcessorDuplicator (StateType *stateToUse)
ProcessorDuplicator (typename StateType::Ptr stateToUse)
ProcessorDuplicator (const ProcessorDuplicator &)=default
ProcessorDuplicator (ProcessorDuplicator &&)=default
void prepare (const ProcessSpec &spec)
void reset () noexcept
template<typename ProcessContext>
void process (const ProcessContext &context) noexcept
Public Attributes
StateType::Ptr state
Detailed Description
template<typename MonoProcessorType, typename StateType>
struct juce::dsp::ProcessorDuplicator< MonoProcessorType, StateType >
Converts a mono processor class into a multi-channel version by duplicating it and applying multichannel buffers across an array of instances.
When the prepare method is called, it uses the specified number of channels to instantiate the appropriate number of instances, which it then uses in its process() method.
Constructor & Destructor Documentation
ProcessorDuplicator() [1/5]
template<typename MonoProcessorType, typename StateType> juce::dsp::ProcessorDuplicator< MonoProcessorType, StateType >::ProcessorDuplicator ()
References state.
Referenced by ProcessorDuplicator(), and ProcessorDuplicator().
ProcessorDuplicator() [2/5]
template<typename MonoProcessorType, typename StateType> juce::dsp::ProcessorDuplicator< MonoProcessorType, StateType >::ProcessorDuplicator (StateType * stateToUse)
References state.
ProcessorDuplicator() [3/5]
template<typename MonoProcessorType, typename StateType> juce::dsp::ProcessorDuplicator< MonoProcessorType, StateType >::ProcessorDuplicator (typename StateType::Ptr stateToUse)
References state.
ProcessorDuplicator() [4/5]
template<typename MonoProcessorType, typename StateType> juce::dsp::ProcessorDuplicator< MonoProcessorType, StateType >::ProcessorDuplicator (const ProcessorDuplicator< MonoProcessorType, StateType > &) default
References ProcessorDuplicator().
ProcessorDuplicator() [5/5]
template<typename MonoProcessorType, typename StateType> juce::dsp::ProcessorDuplicator< MonoProcessorType, StateType >::ProcessorDuplicator (ProcessorDuplicator< MonoProcessorType, StateType > &&) default
References ProcessorDuplicator().
Member Function Documentation
prepare()
template<typename MonoProcessorType, typename StateType> void juce::dsp::ProcessorDuplicator< MonoProcessorType, StateType >::prepare (const ProcessSpec & spec)
References juce::dsp::ProcessSpec::numChannels, and state.
reset()
template<typename MonoProcessorType, typename StateType> void juce::dsp::ProcessorDuplicator< MonoProcessorType, StateType >::reset () noexcept
process()
template<typename MonoProcessorType, typename StateType> template<typename ProcessContext> void juce::dsp::ProcessorDuplicator< MonoProcessorType, StateType >::process (const ProcessContext & context) noexcept
References jassert, and jmin().
Member Data Documentation
state
template<typename MonoProcessorType, typename StateType> StateType::Ptr juce::dsp::ProcessorDuplicator< MonoProcessorType, StateType >::state
Referenced by prepare(), ProcessorDuplicator(), ProcessorDuplicator(), and ProcessorDuplicator().