JUCE: SidePanel::LookAndFeelMethods Struct Reference
SidePanel::LookAndFeelMethods Struct Reference abstract
juce_gui_basics » layout
This abstract base class is implemented by LookAndFeel classes to provide SidePanel drawing functionality.
Public Member Functions
virtual ~LookAndFeelMethods ()=default
virtual Font getSidePanelTitleFont (SidePanel &)=0
virtual Justification getSidePanelTitleJustification (SidePanel &)=0
virtual Path getSidePanelDismissButtonShape (SidePanel &)=0
Detailed Description
This abstract base class is implemented by LookAndFeel classes to provide SidePanel drawing functionality.
Constructor & Destructor Documentation
~LookAndFeelMethods()
virtual SidePanel::LookAndFeelMethods::~LookAndFeelMethods () virtual default
Member Function Documentation
getSidePanelTitleFont()
virtual Font SidePanel::LookAndFeelMethods::getSidePanelTitleFont (SidePanel &) pure virtual
Implemented in LookAndFeel_V2.
References SidePanel::SidePanel().
getSidePanelTitleJustification()
virtual Justification SidePanel::LookAndFeelMethods::getSidePanelTitleJustification (SidePanel &) pure virtual
Implemented in LookAndFeel_V2.
References SidePanel::SidePanel().
getSidePanelDismissButtonShape()
virtual Path SidePanel::LookAndFeelMethods::getSidePanelDismissButtonShape (SidePanel &) pure virtual
Implemented in LookAndFeel_V2.
References SidePanel::SidePanel().