JUCE: AudioProcessorGraph::Connection Struct Reference
AudioProcessorGraph::Connection Struct Reference
juce_audio_processors » processors
Represents a connection between two channels of two nodes in an AudioProcessorGraph.
Public Member Functions
constexpr Connection ()=default
constexpr Connection (NodeAndChannel sourceIn, NodeAndChannel destinationIn) noexcept
constexpr Connection (const Connection &)=default
constexpr Connection & operator= (const Connection &)=default
constexpr bool operator== (const Connection &other) const noexcept
constexpr bool operator!= (const Connection &other) const noexcept
constexpr bool operator< (const Connection &other) const noexcept
Public Attributes
NodeAndChannel source { {}, 0 }
The channel and node which is the input source for this connection.
NodeAndChannel destination { {}, 0 }
The channel and node which is the input source for this connection.
Detailed Description
Represents a connection between two channels of two nodes in an AudioProcessorGraph.
To create a connection, use AudioProcessorGraph::addConnection().
Constructor & Destructor Documentation
Connection() [1/3]
AudioProcessorGraph::Connection::Connection () constexpr default
Referenced by Connection(), operator!=(), operator<(), operator=(), and operator==().
Connection() [2/3]
AudioProcessorGraph::Connection::Connection (NodeAndChannel sourceIn, NodeAndChannel destinationIn) constexpr noexcept
References destination, and source.
Connection() [3/3]
AudioProcessorGraph::Connection::Connection (const Connection &) constexpr default
References Connection().
Member Function Documentation
operator=()
Connection & AudioProcessorGraph::Connection::operator= (const Connection &) constexpr default
References Connection().
operator==()
bool AudioProcessorGraph::Connection::operator== (const Connection & other) const constexpr noexcept
References Connection(), destination, and source.
operator!=()
bool AudioProcessorGraph::Connection::operator!= (const Connection & other) const constexpr noexcept
References Connection(), and operator==().
operator<()
bool AudioProcessorGraph::Connection::operator< (const Connection & other) const constexpr noexcept
References Connection(), and x.
Member Data Documentation
source
NodeAndChannel AudioProcessorGraph::Connection::source { {}, 0 }
The channel and node which is the input source for this connection.
Referenced by Connection(), and operator==().
destination
NodeAndChannel AudioProcessorGraph::Connection::destination { {}, 0 }
The channel and node which is the input source for this connection.
Referenced by Connection(), and operator==().