JUCE: ExtensionsVisitor::VST3Client Struct Reference
ExtensionsVisitor::VST3Client Struct Reference abstract
juce_audio_processors » utilities
Can be used to retrieve information about a VST3 that is wrapped by an AudioProcessor.
Public Member Functions
virtual ~VST3Client ()=default
virtual Steinberg::Vst::IComponent * getIComponentPtr () const noexcept=0
virtual MemoryBlock getPreset () const =0
virtual bool setPreset (const MemoryBlock &) const =0
Detailed Description
Can be used to retrieve information about a VST3 that is wrapped by an AudioProcessor.
Constructor & Destructor Documentation
~VST3Client()
virtual ExtensionsVisitor::VST3Client::~VST3Client () virtual default
Member Function Documentation
getIComponentPtr()
virtual Steinberg::Vst::IComponent * ExtensionsVisitor::VST3Client::getIComponentPtr () const pure virtual noexcept
getPreset()
virtual MemoryBlock ExtensionsVisitor::VST3Client::getPreset () const pure virtual
References getPreset().
Referenced by getPreset().
setPreset()
virtual bool ExtensionsVisitor::VST3Client::setPreset (const MemoryBlock &) const pure virtual
References setPreset().
Referenced by setPreset().