JUCE: juce::midi_ci::Message::ProfileSpecificData Struct Reference
juce::midi_ci::Message::ProfileSpecificData Struct Reference
juce_midi_ci » ci
See the MIDI-CI specification.
Public Member Functions
auto tie () const
bool operator== (const ProfileSpecificData &x) const
bool operator!= (const ProfileSpecificData &x) const
Public Attributes
Profile profile {}
Span< const std::byte > data
Detailed Description
See the MIDI-CI specification.
Member Function Documentation
tie()
auto juce::midi_ci::Message::ProfileSpecificData::tie () const
References data, and profile.
Referenced by operator==().
operator==()
bool juce::midi_ci::Message::ProfileSpecificData::operator== (const ProfileSpecificData & x) const
References tie(), and x.
Referenced by operator!=().
operator!=()
bool juce::midi_ci::Message::ProfileSpecificData::operator!= (const ProfileSpecificData & x) const
References operator==(), and x.
Member Data Documentation
profile
Profile juce::midi_ci::Message::ProfileSpecificData::profile {}
Referenced by tie().
data
Span<const std::byte> juce::midi_ci::Message::ProfileSpecificData::data
Referenced by tie().