JUCE: Atomic< Type > Struct Template Reference
Atomic< Type > Struct Template Reference final
juce_core » memory
A simple wrapper around std::atomic.
Public Types
using DiffType = typename AtomicHelpers::DiffTypeHelper<Type>::Type
Public Member Functions
Atomic () noexcept
Creates a new value, initialised to zero.
Atomic (Type initialValue) noexcept
Creates a new value, with a given initial value.
Atomic (const Atomic &other) noexcept
Copies another value (atomically).
~Atomic () noexcept
Destructor.
Type get () const noexcept
Atomically reads and returns the current value.
void set (Type newValue) noexcept
Atomically sets the current value.
Type exchange (Type newValue) noexcept
Atomically sets the current value, returning the value that was replaced.
bool compareAndSetBool (Type newValue, Type valueToCompare) noexcept
Atomically compares this value with a target value, and if it is equal, sets this to be equal to a new value.
Atomic< Type > & operator= (const Atomic &other) noexcept
Copies another value into this one (atomically).
Atomic< Type > & operator= (Type newValue) noexcept
Copies another value into this one (atomically).
Type operator+= (DiffType amountToAdd) noexcept
Atomically adds a number to this value, returning the new value.
Type operator-= (DiffType amountToSubtract) noexcept
Atomically subtracts a number from this value, returning the new value.
Type operator++ () noexcept
Atomically increments this value, returning the new value.
Type operator-- () noexcept
Atomically decrements this value, returning the new value.
void memoryBarrier () noexcept
Implements a memory read/write barrier.
Public Attributes
std::atomic< Type > value
The std::atomic object that this class operates on.
Detailed Description
template<typename Type>
struct Atomic< Type >
A simple wrapper around std::atomic.
Member Typedef Documentation
DiffType
template<typename Type> using Atomic< Type >::DiffType = typename AtomicHelpers::DiffTypeHelper<Type>::Type
Constructor & Destructor Documentation
Atomic() [1/3]
template<typename Type> Atomic< Type >::Atomic () noexcept
Creates a new value, initialised to zero.
References value.
Referenced by Atomic(), operator=(), and operator=().
Atomic() [2/3]
template<typename Type> Atomic< Type >::Atomic (Type initialValue) noexcept
Creates a new value, with a given initial value.
Atomic() [3/3]
template<typename Type> Atomic< Type >::Atomic (const Atomic< Type > & other) noexcept
Copies another value (atomically).
References Atomic().
~Atomic()
template<typename Type> Atomic< Type >::~Atomic () noexcept
Destructor.
Member Function Documentation
get()
template<typename Type> Type Atomic< Type >::get () const noexcept
Atomically reads and returns the current value.
References value.
Referenced by ThreadLocalValue< Type >::get().
set()
template<typename Type> void Atomic< Type >::set (Type newValue) noexcept
Atomically sets the current value.
References value.
exchange()
template<typename Type> Type Atomic< Type >::exchange (Type newValue) noexcept
Atomically sets the current value, returning the value that was replaced.
References value.
compareAndSetBool()
template<typename Type> bool Atomic< Type >::compareAndSetBool (Type newValue, Type valueToCompare) noexcept
Atomically compares this value with a target value, and if it is equal, sets this to be equal to a new value.
This operation is the atomic equivalent of doing this:
bool compareAndSetBool (Type newValue, Type valueToCompare)
{
    if (get() == valueToCompare)
    {
        set (newValue);
        return true;
    }
    return false;
}
Internally, this method calls std::atomic::compare_exchange_strong with memory_order_seq_cst (the strictest std::memory_order).
Returns
true if the comparison was true and the value was replaced; false if the comparison failed and the value was left unchanged.
See also
compareAndSetValue
References value.
Referenced by ThreadLocalValue< Type >::get().
operator=() [1/2]
template<typename Type> Atomic< Type > & Atomic< Type >::operator= (const Atomic< Type > & other) noexcept
Copies another value into this one (atomically).
References Atomic(), and value.
operator=() [2/2]
template<typename Type> Atomic< Type > & Atomic< Type >::operator= (Type newValue) noexcept
Copies another value into this one (atomically).
References Atomic(), and value.
operator+=()
template<typename Type> Type Atomic< Type >::operator+= (DiffType amountToAdd) noexcept
Atomically adds a number to this value, returning the new value.
References value.
operator-=()
template<typename Type> Type Atomic< Type >::operator-= (DiffType amountToSubtract) noexcept
Atomically subtracts a number from this value, returning the new value.
References value.
operator++()
template<typename Type> Type Atomic< Type >::operator++ () noexcept
Atomically increments this value, returning the new value.
References value.
operator--()
template<typename Type> Type Atomic< Type >::operator-- () noexcept
Atomically decrements this value, returning the new value.
References value.
memoryBarrier()
template<typename Type> void Atomic< Type >::memoryBarrier () noexcept
Implements a memory read/write barrier.
Internally this calls std::atomic_thread_fence with memory_order_seq_cst (the strictest std::memory_order).
Member Data Documentation
value
template<typename Type> std::atomic<Type> Atomic< Type >::value
The std::atomic object that this class operates on.
Referenced by Atomic(), compareAndSetBool(), exchange(), get(), operator++(), operator+=(), operator--(), operator-=(), operator=(), operator=(), and set().