JUCE: Toolbar::LookAndFeelMethods Struct Reference
Toolbar::LookAndFeelMethods Struct Reference abstract
juce_gui_basics » widgets
This abstract base class is implemented by LookAndFeel classes.
Public Member Functions
virtual ~LookAndFeelMethods ()=default
virtual void paintToolbarBackground (Graphics &, int width, int height, Toolbar &)=0
virtual Button * createToolbarMissingItemsButton (Toolbar &)=0
virtual void paintToolbarButtonBackground (Graphics &, int width, int height, bool isMouseOver, bool isMouseDown, ToolbarItemComponent &)=0
virtual void paintToolbarButtonLabel (Graphics &, int x, int y, int width, int height, const String &text, ToolbarItemComponent &)=0
Detailed Description
This abstract base class is implemented by LookAndFeel classes.
Constructor & Destructor Documentation
~LookAndFeelMethods()
virtual Toolbar::LookAndFeelMethods::~LookAndFeelMethods () virtual default
Member Function Documentation
paintToolbarBackground()
virtual void Toolbar::LookAndFeelMethods::paintToolbarBackground (Graphics & , int width, int height, Toolbar &) pure virtual
Implemented in LookAndFeel_V2, and LookAndFeel_V4.
References Toolbar::Toolbar().
createToolbarMissingItemsButton()
virtual Button * Toolbar::LookAndFeelMethods::createToolbarMissingItemsButton (Toolbar &) pure virtual
Implemented in LookAndFeel_V2.
References Toolbar::Toolbar().
paintToolbarButtonBackground()
virtual void Toolbar::LookAndFeelMethods::paintToolbarButtonBackground (Graphics & , int width, int height, bool isMouseOver, bool isMouseDown, ToolbarItemComponent &) pure virtual
Implemented in LookAndFeel_V2.
References Component::isMouseOver().
paintToolbarButtonLabel()
virtual void Toolbar::LookAndFeelMethods::paintToolbarButtonLabel (Graphics & , int x, int y, int width, int height, const String & text, ToolbarItemComponent &) pure virtual
Implemented in LookAndFeel_V2, and LookAndFeel_V4.
References x, and y.