JUCE: juce::midi_ci::Message::ProfileDetailsResponse Struct Reference
juce::midi_ci::Message::ProfileDetailsResponse Struct Reference
juce_midi_ci » ci
See the MIDI-CI specification.
Public Member Functions
auto tie () const
bool operator== (const ProfileDetailsResponse &x) const
bool operator!= (const ProfileDetailsResponse &x) const
Public Attributes
Profile profile {}
std::byte target {}
Span< const std::byte > data
Detailed Description
See the MIDI-CI specification.
Member Function Documentation
tie()
auto juce::midi_ci::Message::ProfileDetailsResponse::tie () const
References data, profile, and target.
Referenced by operator==().
operator==()
bool juce::midi_ci::Message::ProfileDetailsResponse::operator== (const ProfileDetailsResponse & x) const
References tie(), and x.
Referenced by operator!=().
operator!=()
bool juce::midi_ci::Message::ProfileDetailsResponse::operator!= (const ProfileDetailsResponse & x) const
References operator==(), and x.
Member Data Documentation
profile
Profile juce::midi_ci::Message::ProfileDetailsResponse::profile {}
Referenced by tie().
target
std::byte juce::midi_ci::Message::ProfileDetailsResponse::target {}
Referenced by tie().
data
Span<const std::byte> juce::midi_ci::Message::ProfileDetailsResponse::data
Referenced by tie().