JUCE: dsp::SIMDRegister::ElementAccess< Type > Struct Template Reference
dsp::SIMDRegister::ElementAccess< Type > Struct Template Reference
juce_dsp » containers
Public Member Functions
ElementAccess (const ElementAccess &)=default
operator Type () const
ElementAccess & operator= (Type scalar) noexcept
ElementAccess & operator= (const ElementAccess &o) noexcept
Constructor & Destructor Documentation
ElementAccess()
template<typename Type> dsp::SIMDRegister::ElementAccess< Type >::ElementAccess (const ElementAccess< Type > &) default
References ElementAccess().
Referenced by ElementAccess(), operator=(), operator=(), and SIMDRegister.
Member Function Documentation
operator Type()
template<typename Type> dsp::SIMDRegister::ElementAccess< Type >::operator Type () const
operator=() [1/2]
template<typename Type> ElementAccess & dsp::SIMDRegister::ElementAccess< Type >::operator= (Type scalar) noexcept
References ElementAccess().
operator=() [2/2]
template<typename Type> ElementAccess & dsp::SIMDRegister::ElementAccess< Type >::operator= (const ElementAccess< Type > & o) noexcept
References ElementAccess().