JUCE: juce::midi_ci::Message::PropertySubscribeResponse Struct Reference
juce::midi_ci::Message::PropertySubscribeResponse Struct Reference
juce_midi_ci » ci
See the MIDI-CI specification.
Public Member Functions
bool operator== (const PropertySubscribeResponse &x) const
bool operator!= (const PropertySubscribeResponse &x) const
Public Member Functions inherited from juce::midi_ci::Message::DynamicSizePropertyExchange
auto tie () const
Additional Inherited Members
Public Attributes inherited from juce::midi_ci::Message::DynamicSizePropertyExchange
std::byte requestID {}
Span< const std::byte > header
uint16_t totalNumChunks {}
uint16_t thisChunkNum {}
Span< const std::byte > data
Detailed Description
See the MIDI-CI specification.
Member Function Documentation
operator==()
bool juce::midi_ci::Message::PropertySubscribeResponse::operator== (const PropertySubscribeResponse & x) const
References juce::midi_ci::Message::DynamicSizePropertyExchange::tie(), and x.
Referenced by operator!=().
operator!=()
bool juce::midi_ci::Message::PropertySubscribeResponse::operator!= (const PropertySubscribeResponse & x) const
References operator==(), and x.