JUCE: GridItem::Span Struct Reference
GridItem::Span Struct Reference
juce_gui_basics » layout
Represents a span.
Public Member Functions
Span (int numberToUse) noexcept
Span (int numberToUse, const String &nameToUse)
Span (const String &nameToUse)
Public Attributes
int number = 1
String name
Detailed Description
Represents a span.
Constructor & Destructor Documentation
Span() [1/3]
GridItem::Span::Span (int numberToUse) explicit noexcept
References jassert, and number.
Referenced by Span().
Span() [2/3]
GridItem::Span::Span (int numberToUse, const String & nameToUse) explicit
References String::isNotEmpty(), jassert, name, and Span().
Span() [3/3]
GridItem::Span::Span (const String & nameToUse) explicit
References String::isNotEmpty(), jassert, and name.
Member Data Documentation
number
int GridItem::Span::number = 1
Referenced by Span().
name
String GridItem::Span::name
Referenced by Span(), and Span().