JUCE: FlexItem::Margin Struct Reference
FlexItem::Margin Struct Reference final
juce_gui_basics » layout
Represents a margin.
Public Member Functions
Margin () noexcept
Creates a margin of size zero.
Margin (float size) noexcept
Creates a margin with this size on all sides.
Margin (float top, float right, float bottom, float left) noexcept
Creates a margin with these sizes.
Public Attributes
float left
Left margin size.
float right
Right margin size.
float top
Top margin size.
float bottom
Bottom margin size.
Detailed Description
Represents a margin.
Constructor & Destructor Documentation
Margin() [1/3]
FlexItem::Margin::Margin () noexcept
Creates a margin of size zero.
Referenced by Margin(), and Margin().
Margin() [2/3]
FlexItem::Margin::Margin (float size) noexcept
Creates a margin with this size on all sides.
References Margin().
Margin() [3/3]
FlexItem::Margin::Margin (float top, float right, float bottom, float left) noexcept
Creates a margin with these sizes.
References bottom, left, Margin(), right, and top.
Member Data Documentation
left
float FlexItem::Margin::left
Left margin size.
Referenced by Margin().
right
float FlexItem::Margin::right
Right margin size.
Referenced by Margin().
top
float FlexItem::Margin::top
Top margin size.
Referenced by Margin().
bottom
float FlexItem::Margin::bottom
Bottom margin size.
Referenced by Margin().