JUCE: WebBrowserComponent::Options::WinWebView2 Class Reference
WebBrowserComponent::Options::WinWebView2 Class Reference
juce_gui_extra » misc
Options specific to the WebView2 backend.
Public Member Functions
WinWebView2 withDLLLocation (const File &location) const
Sets a custom location for the WebView2Loader.dll that is not a part of the standard system DLL search paths.
WinWebView2 withUserDataFolder (const File &folder) const
Sets a non-default location for storing user data for the browser instance.
WinWebView2 withStatusBarDisabled () const
If this is set, the status bar usually displayed in the lower-left of the webview will be disabled.
WinWebView2 withBuiltInErrorPageDisabled () const
If this is set, a blank page will be displayed on error instead of the default built-in error page.
WinWebView2 withBackgroundColour (const Colour &colour) const
Sets the background colour that WebView2 renders underneath all web content.
File getDLLLocation () const
File getUserDataFolder () const
bool getIsStatusBarDisabled () const noexcept
bool getIsBuiltInErrorPageDisabled () const noexcept
Colour getBackgroundColour () const
Detailed Description
Options specific to the WebView2 backend.
These options will be ignored if another backend is used.
Member Function Documentation
withDLLLocation()
WinWebView2 WebBrowserComponent::Options::WinWebView2::withDLLLocation (const File & location) const nodiscard
Sets a custom location for the WebView2Loader.dll that is not a part of the standard system DLL search paths.
References withMember().
withUserDataFolder()
WinWebView2 WebBrowserComponent::Options::WinWebView2::withUserDataFolder (const File & folder) const nodiscard
Sets a non-default location for storing user data for the browser instance.
In plugin projects you may find it necessary to use this option and specify a location such as File::SpecialLocationType::tempDirectory. Otherwise WebView2 may function incorrectly due to being denied access to the default user data location.
References withMember().
withStatusBarDisabled()
WinWebView2 WebBrowserComponent::Options::WinWebView2::withStatusBarDisabled () const nodiscard
If this is set, the status bar usually displayed in the lower-left of the webview will be disabled.
References withMember().
withBuiltInErrorPageDisabled()
WinWebView2 WebBrowserComponent::Options::WinWebView2::withBuiltInErrorPageDisabled () const nodiscard
If this is set, a blank page will be displayed on error instead of the default built-in error page.
References withMember().
withBackgroundColour()
WinWebView2 WebBrowserComponent::Options::WinWebView2::withBackgroundColour (const Colour & colour) const nodiscard
Sets the background colour that WebView2 renders underneath all web content.
This colour must either be fully opaque or fully transparent.
References Colour::isOpaque(), Colour::isTransparent(), jassert, and withMember().
getDLLLocation()
File WebBrowserComponent::Options::WinWebView2::getDLLLocation () const
getUserDataFolder()
File WebBrowserComponent::Options::WinWebView2::getUserDataFolder () const
getIsStatusBarDisabled()
bool WebBrowserComponent::Options::WinWebView2::getIsStatusBarDisabled () const noexcept
getIsBuiltInErrorPageDisabled()
bool WebBrowserComponent::Options::WinWebView2::getIsBuiltInErrorPageDisabled () const noexcept
getBackgroundColour()
Colour WebBrowserComponent::Options::WinWebView2::getBackgroundColour () const