JUCE: AudioProcessorEditorARAExtension Class Reference
AudioProcessorEditorARAExtension Class Reference
juce_audio_processors » utilities
Extension class meant to be subclassed by the plugin's implementation of.
Public Member Functions
AudioProcessorEditorARAExtension (AudioProcessor *audioProcessor)
Constructor.
template<typename EditorView_t = ARAEditorView>
EditorView_t * getARAEditorView () const noexcept
Returns the result of ARA::PlugIn::PlugInExtension::getEditorView() with the pointer cast to ARAEditorView*.
bool isARAEditorView () const noexcept
Returns true if plugin instance fulfills the ARAEditorView role.
Protected Member Functions
~AudioProcessorEditorARAExtension ()
Destructor.
Detailed Description
Extension class meant to be subclassed by the plugin's implementation of.
See also
AudioProcessorEditor.
Subclassing AudioProcessorARAExtension allows access to the ARAEditorView instance role as described by the ARA SDK.
Constructor & Destructor Documentation
AudioProcessorEditorARAExtension()
AudioProcessorEditorARAExtension::AudioProcessorEditorARAExtension (AudioProcessor * audioProcessor) explicit
Constructor.
Referenced by ~AudioProcessorEditorARAExtension().
~AudioProcessorEditorARAExtension()
AudioProcessorEditorARAExtension::~AudioProcessorEditorARAExtension () protected
Destructor.
References AudioProcessorEditorARAExtension().
Member Function Documentation
getARAEditorView()
template<typename EditorView_t = ARAEditorView> EditorView_t * AudioProcessorEditorARAExtension::getARAEditorView () const noexcept
Returns the result of ARA::PlugIn::PlugInExtension::getEditorView() with the pointer cast to ARAEditorView*.
If you have overridden ARADocumentControllerSpecialisation::doCreateEditorView(), then you can use the template parameter to cast the pointers to your subclass of ARAEditorView.
Referenced by isARAEditorView().
isARAEditorView()
bool AudioProcessorEditorARAExtension::isARAEditorView () const noexcept
Returns true if plugin instance fulfills the ARAEditorView role.
References getARAEditorView().