JUCE: AccessibilityRangedNumericValueInterface Class Reference
AccessibilityRangedNumericValueInterface Class Reference abstract
juce_gui_basics » accessibility
A value interface that represents a ranged numeric value.
Public Member Functions
bool isReadOnly () const override=0
Returns true if the value is read-only and cannot be modified by an accessibility client.
double getCurrentValue () const override=0
Returns the current value.
void setValue (double newValue) override=0
Sets the current value to a new value.
AccessibleValueRange getRange () const override=0
Returns the range.
String getCurrentValueAsString () const final
Returns the current value as a String.
void setValueAsString (const String &newValue) final
Sets the current value to a new String value.
Public Member Functions inherited from AccessibilityValueInterface
virtual ~AccessibilityValueInterface ()=default
Destructor.
Detailed Description
A value interface that represents a ranged numeric value.
Member Function Documentation
isReadOnly()
bool AccessibilityRangedNumericValueInterface::isReadOnly () const override pure virtual
Returns true if the value is read-only and cannot be modified by an accessibility client.
See also
setValueAsString
Implements AccessibilityValueInterface.
getCurrentValue()
double AccessibilityRangedNumericValueInterface::getCurrentValue () const override pure virtual
Returns the current value.
Implements AccessibilityValueInterface.
Referenced by getCurrentValueAsString().
setValue()
void AccessibilityRangedNumericValueInterface::setValue (double newValue) override pure virtual
Sets the current value to a new value.
Implements AccessibilityValueInterface.
Referenced by setValueAsString().
getRange()
AccessibleValueRange AccessibilityRangedNumericValueInterface::getRange () const override pure virtual
Returns the range.
Implements AccessibilityValueInterface.
getCurrentValueAsString()
String AccessibilityRangedNumericValueInterface::getCurrentValueAsString () const final virtual
Returns the current value as a String.
Implements AccessibilityValueInterface.
References getCurrentValue().
setValueAsString()
void AccessibilityRangedNumericValueInterface::setValueAsString (const String & newValue) final virtual
Sets the current value to a new String value.
Implements AccessibilityValueInterface.
References setValue().