JUCE: SpeakerMappings::VstSpeakerConfigurationHolder Class Reference
SpeakerMappings::VstSpeakerConfigurationHolder Class Reference
juce_audio_processors » format_types
Class to hold a speaker configuration.
Public Member Functions
VstSpeakerConfigurationHolder ()
VstSpeakerConfigurationHolder (const Vst2::VstSpeakerArrangement &vstConfig)
VstSpeakerConfigurationHolder (const VstSpeakerConfigurationHolder &other)
VstSpeakerConfigurationHolder (VstSpeakerConfigurationHolder &&other)
VstSpeakerConfigurationHolder (const AudioChannelSet &channels)
VstSpeakerConfigurationHolder & operator= (const VstSpeakerConfigurationHolder &vstConfig)
VstSpeakerConfigurationHolder & operator= (const Vst2::VstSpeakerArrangement &vstConfig)
VstSpeakerConfigurationHolder & operator= (VstSpeakerConfigurationHolder &&vstConfig)
const Vst2::VstSpeakerArrangement & get () const
Detailed Description
Class to hold a speaker configuration.
Constructor & Destructor Documentation
VstSpeakerConfigurationHolder() [1/5]
SpeakerMappings::VstSpeakerConfigurationHolder::VstSpeakerConfigurationHolder ()
Referenced by operator=(), operator=(), operator=(), VstSpeakerConfigurationHolder(), and VstSpeakerConfigurationHolder().
VstSpeakerConfigurationHolder() [2/5]
SpeakerMappings::VstSpeakerConfigurationHolder::VstSpeakerConfigurationHolder (const Vst2::VstSpeakerArrangement & vstConfig)
References operator=().
VstSpeakerConfigurationHolder() [3/5]
SpeakerMappings::VstSpeakerConfigurationHolder::VstSpeakerConfigurationHolder (const VstSpeakerConfigurationHolder & other)
References get(), operator=(), and VstSpeakerConfigurationHolder().
VstSpeakerConfigurationHolder() [4/5]
SpeakerMappings::VstSpeakerConfigurationHolder::VstSpeakerConfigurationHolder (VstSpeakerConfigurationHolder && other)
References VstSpeakerConfigurationHolder().
VstSpeakerConfigurationHolder() [5/5]
SpeakerMappings::VstSpeakerConfigurationHolder::VstSpeakerConfigurationHolder (const AudioChannelSet & channels)
References AudioChannelSet::AudioChannelSet(), SpeakerMappings::channelSetToVstArrangementType(), SpeakerMappings::getSpeakerType(), and zeromem().
Member Function Documentation
operator=() [1/3]
VstSpeakerConfigurationHolder & SpeakerMappings::VstSpeakerConfigurationHolder::operator= (const VstSpeakerConfigurationHolder & vstConfig)
References get(), operator=(), and VstSpeakerConfigurationHolder().
Referenced by operator=(), VstSpeakerConfigurationHolder(), and VstSpeakerConfigurationHolder().
operator=() [2/3]
VstSpeakerConfigurationHolder & SpeakerMappings::VstSpeakerConfigurationHolder::operator= (const Vst2::VstSpeakerArrangement & vstConfig)
References VstSpeakerConfigurationHolder().
operator=() [3/3]
VstSpeakerConfigurationHolder & SpeakerMappings::VstSpeakerConfigurationHolder::operator= (VstSpeakerConfigurationHolder && vstConfig)
References VstSpeakerConfigurationHolder().
get()
const Vst2::VstSpeakerArrangement & SpeakerMappings::VstSpeakerConfigurationHolder::get () const
Referenced by operator=(), and VstSpeakerConfigurationHolder().