JUCE: Image::BitmapData Class Reference
Image::BitmapData Class Reference final
juce_graphics » images
Retrieves a section of an image as raw pixel data, so it can be read or written to.
Classes
class BitmapDataReleaser
Used internally by custom image types to manage pixel data lifetime.
Public Types
enum ReadWriteMode { readOnly , writeOnly , readWrite }
Public Member Functions
BitmapData (Image &image, int x, int y, int w, int h, ReadWriteMode mode)
BitmapData (const Image &image, Rectangle< int >, ReadWriteMode mode)
BitmapData (const Image &image, int x, int y, int w, int h)
BitmapData (const Image &image, ReadWriteMode mode)
uint8 * getLinePointer (int y) const noexcept
Returns a pointer to the start of a line in the image.
uint8 * getPixelPointer (int x, int y) const noexcept
Returns a pointer to a pixel in the image.
Colour getPixelColour (int x, int y) const noexcept
Returns the colour of a given pixel.
void setPixelColour (int x, int y, Colour colour) const noexcept
Sets the colour of a given pixel.
Rectangle< int > getBounds () const noexcept
Returns the size of the bitmap.
bool convertFrom (const Image::BitmapData &src)
Attempts to copy the contents of src into this bitmap data.
Public Attributes
uint8 * data
The raw pixel data, packed according to the image's pixel format.
size_t size
The number of valid/allocated bytes after data.
PixelFormat pixelFormat
The format of the data.
int lineStride
The number of bytes between each line.
int pixelStride
The number of bytes between each pixel.
int width
int height
std::unique_ptr< BitmapDataReleaser > dataReleaser
Detailed Description
Retrieves a section of an image as raw pixel data, so it can be read or written to.
You should only use this class as a last resort - messing about with the internals of an image is only recommended for people who really know what they're doing!
A BitmapData object should be used as a temporary, stack-based object. Don't keep one hanging around while the image is being used elsewhere.
Depending on the way the image class is implemented, this may create a temporary buffer which is copied back to the image when the object is deleted, or it may just get a pointer directly into the image's raw data.
You can use the stride and data values in this class directly, but don't alter them! The actual format of the pixel data depends on the image's format - see Image::getFormat(), and the PixelRGB, PixelARGB and PixelAlpha classes for more info.
Member Enumeration Documentation
ReadWriteMode
enum Image::BitmapData::ReadWriteMode
Enumerator
readOnly
writeOnly
readWrite
Constructor & Destructor Documentation
BitmapData() [1/4]
Image::BitmapData::BitmapData (Image & image, int x, int y, int w, int h, ReadWriteMode mode)
References h, Image::Image(), w, x, and y.
BitmapData() [2/4]
Image::BitmapData::BitmapData (const Image & image, Rectangle< int > , ReadWriteMode mode)
References Image::Image().
BitmapData() [3/4]
Image::BitmapData::BitmapData (const Image & image, int x, int y, int w, int h)
References h, Image::Image(), w, x, and y.
BitmapData() [4/4]
Image::BitmapData::BitmapData (const Image & image, ReadWriteMode mode)
References Image::Image().
Member Function Documentation
getLinePointer()
uint8 * Image::BitmapData::getLinePointer (int y) const noexcept
Returns a pointer to the start of a line in the image.
The coordinate you provide here isn't checked, so it's the caller's responsibility to make sure it's not out-of-range.
References data, lineStride, and y.
getPixelPointer()
uint8 * Image::BitmapData::getPixelPointer (int x, int y) const noexcept
Returns a pointer to a pixel in the image.
The coordinates you give here are not checked, so it's the caller's responsibility to make sure they're not out-of-range.
References data, lineStride, pixelStride, x, and y.
getPixelColour()
Colour Image::BitmapData::getPixelColour (int x, int y) const noexcept
Returns the colour of a given pixel.
For performance reasons, this won't do any bounds-checking on the coordinates, so it's the caller's responsibility to make sure they're within the image's size.
References x, and y.
setPixelColour()
void Image::BitmapData::setPixelColour (int x, int y, Colour colour) const noexcept
Sets the colour of a given pixel.
For performance reasons, this won't do any bounds-checking on the coordinates, so it's the caller's responsibility to make sure they're within the image's size.
References x, and y.
getBounds()
Rectangle< int > Image::BitmapData::getBounds () const noexcept
Returns the size of the bitmap.
References height, and width.
convertFrom()
bool Image::BitmapData::convertFrom (const Image::BitmapData & src)
Attempts to copy the contents of src into this bitmap data.
Returns true on success, and false otherwise.
The source BitmapData must be readable, and the destination (current) BitmapData must be writeable. This function cannot check for this precondition, so you must ensure this yourself!
Member Data Documentation
data
uint8* Image::BitmapData::data
The raw pixel data, packed according to the image's pixel format.
Referenced by getLinePointer(), and getPixelPointer().
size
size_t Image::BitmapData::size
The number of valid/allocated bytes after data.
May be smaller than "lineStride * height" if this is a section of a larger image.
pixelFormat
PixelFormat Image::BitmapData::pixelFormat
The format of the data.
lineStride
int Image::BitmapData::lineStride
The number of bytes between each line.
Referenced by getLinePointer(), and getPixelPointer().
pixelStride
int Image::BitmapData::pixelStride
The number of bytes between each pixel.
Referenced by getPixelPointer().
width
int Image::BitmapData::width
Referenced by getBounds().
height
int Image::BitmapData::height
Referenced by getBounds().
dataReleaser
std::unique_ptr<BitmapDataReleaser> Image::BitmapData::dataReleaser