JUCE: juce::dsp::ConvolutionMessageQueue Class Reference
juce::dsp::ConvolutionMessageQueue Class Reference
juce_dsp » frequency
Used by the Convolution to dispatch engine-update messages on a background thread.
Public Member Functions
ConvolutionMessageQueue ()
Initialises the queue to a default size.
~ConvolutionMessageQueue () noexcept
ConvolutionMessageQueue (int numEntries)
Initialises the queue with the specified number of entries.
ConvolutionMessageQueue (ConvolutionMessageQueue &&) noexcept
ConvolutionMessageQueue & operator= (ConvolutionMessageQueue &&) noexcept
ConvolutionMessageQueue (const ConvolutionMessageQueue &)=delete
ConvolutionMessageQueue & operator= (const ConvolutionMessageQueue &)=delete
Detailed Description
Used by the Convolution to dispatch engine-update messages on a background thread.
May be shared between multiple Convolution instances.
Constructor & Destructor Documentation
ConvolutionMessageQueue() [1/4]
juce::dsp::ConvolutionMessageQueue::ConvolutionMessageQueue ()
Initialises the queue to a default size.
If your Convolution is updated very frequently, or you are sharing this queue between multiple Convolutions, consider using the alternative constructor taking an explicit size argument.
Referenced by ConvolutionMessageQueue(), ConvolutionMessageQueue(), ConvolutionMessageQueue(), operator=(), and operator=().
~ConvolutionMessageQueue()
juce::dsp::ConvolutionMessageQueue::~ConvolutionMessageQueue () noexcept
ConvolutionMessageQueue() [2/4]
juce::dsp::ConvolutionMessageQueue::ConvolutionMessageQueue (int numEntries) explicit
Initialises the queue with the specified number of entries.
In general, the number of required entries scales with the number of Convolutions sharing the same Queue, and the frequency of updates to those Convolutions.
References ConvolutionMessageQueue().
ConvolutionMessageQueue() [3/4]
juce::dsp::ConvolutionMessageQueue::ConvolutionMessageQueue (ConvolutionMessageQueue &&) noexcept
References ConvolutionMessageQueue().
ConvolutionMessageQueue() [4/4]
juce::dsp::ConvolutionMessageQueue::ConvolutionMessageQueue (const ConvolutionMessageQueue &) delete
References ConvolutionMessageQueue().
Member Function Documentation
operator=() [1/2]
ConvolutionMessageQueue & juce::dsp::ConvolutionMessageQueue::operator= (ConvolutionMessageQueue &&) noexcept
References ConvolutionMessageQueue().
operator=() [2/2]
ConvolutionMessageQueue & juce::dsp::ConvolutionMessageQueue::operator= (const ConvolutionMessageQueue &) delete
References ConvolutionMessageQueue().