JUCE: OSCAddress Class Reference
OSCAddress Class Reference
juce_osc » osc
An OSC address.
Public Member Functions
OSCAddress (const String &address)
Constructs a new OSCAddress from a String.
OSCAddress (const char *address)
Constructs a new OSCAddress from a C string.
bool operator== (const OSCAddress &other) const noexcept
Compares two OSCAddress objects.
bool operator!= (const OSCAddress &other) const noexcept
Compares two OSCAddress objects.
String toString () const noexcept
Converts the OSCAddress to a String.
Detailed Description
An OSC address.
This address always starts with a forward slash and has a format similar to an URL, with several address parts separated by slashes.
Only a subset of ASCII characters are allowed in OSC addresses; see OpenSoundControl 1.0 specification for details.
OSC addresses can be used to register ListenerWithOSCAddress objects to an OSCReceiver if you wish them to only listen to certain messages with matching OSC address patterns.
See also
OSCReceiver, OSCAddressPattern, OSCMessage
Constructor & Destructor Documentation
OSCAddress() [1/2]
OSCAddress::OSCAddress (const String & address)
Constructs a new OSCAddress from a String.
Exceptions
OSCFormatError if the string is not a valid OSC address.
Referenced by operator!=(), and operator==().
OSCAddress() [2/2]
OSCAddress::OSCAddress (const char * address)
Constructs a new OSCAddress from a C string.
Exceptions
OSCFormatError of the string is not a valid OSC address.
Member Function Documentation
operator==()
bool OSCAddress::operator== (const OSCAddress & other) const noexcept
Compares two OSCAddress objects.
Returns
true if they contain the same address, false otherwise.
References OSCAddress().
operator!=()
bool OSCAddress::operator!= (const OSCAddress & other) const noexcept
Compares two OSCAddress objects.
Returns
false if they contain the same address, true otherwise.
References OSCAddress().
toString()
String OSCAddress::toString () const noexcept
Converts the OSCAddress to a String.
Note: Trailing slashes are always removed automatically.
Returns
a String object that represents the OSC address.