JUCE: LAMEEncoderAudioFormat Class Reference
LAMEEncoderAudioFormat Class Reference
juce_audio_formats » codecs
An AudioFormat class which can use an installed version of the LAME mp3 encoder to encode a file.
Public Member Functions
LAMEEncoderAudioFormat (const File &lameExecutableToUse)
Creates a LAMEEncoderAudioFormat that expects to find a working LAME executable at the location given.
~LAMEEncoderAudioFormat ()
bool canHandleFile (const File &)
Returns true if this the given file can be read by this format.
Array< int > getPossibleSampleRates ()
Returns a set of sample rates that the format can read and write.
Array< int > getPossibleBitDepths ()
Returns a set of bit depths that the format can read and write.
bool canDoStereo ()
Returns true if the format can do 2-channel audio.
bool canDoMono ()
Returns true if the format can do 1-channel audio.
bool isCompressed ()
Returns true if the format uses compressed data.
StringArray getQualityOptions ()
Returns a list of different qualities that can be used when writing.
AudioFormatReader * createReaderFor (InputStream *, bool deleteStreamIfOpeningFails)
Tries to create an object that can read from a stream containing audio data in this format.
AudioFormatWriter * createWriterFor (OutputStream *, double sampleRateToUse, unsigned int numberOfChannels, int bitsPerSample, const StringPairArray &metadataValues, int qualityOptionIndex)
Tries to create an object that can write to a stream with this audio format.
virtual AudioFormatWriter * createWriterFor (OutputStream *streamToWriteTo, double sampleRateToUse, const AudioChannelSet &channelLayout, int bitsPerSample, const StringPairArray &metadataValues, int qualityOptionIndex)
Tries to create an object that can write to a stream with this audio format.
Public Member Functions inherited from AudioFormat
virtual ~AudioFormat ()
Destructor.
const String & getFormatName () const
Returns the name of this format.
virtual StringArray getFileExtensions () const
Returns all the file extensions that might apply to a file of this format.
virtual bool isChannelLayoutSupported (const AudioChannelSet &channelSet)
Returns true if the channel layout is supported by this format.
virtual MemoryMappedAudioFormatReader * createMemoryMappedReader (const File &file)
Attempts to create a MemoryMappedAudioFormatReader, if possible for this format.
virtual MemoryMappedAudioFormatReader * createMemoryMappedReader (FileInputStream *fin)
Additional Inherited Members
Protected Member Functions inherited from AudioFormat
AudioFormat (String formatName, StringArray fileExtensions)
Creates an AudioFormat object.
AudioFormat (StringRef formatName, StringRef fileExtensions)
Creates an AudioFormat object.
Detailed Description
An AudioFormat class which can use an installed version of the LAME mp3 encoder to encode a file.
This format can't read MP3s, it just writes them. Internally, the AudioFormatWriter object that is returned writes the incoming audio data to a temporary WAV file, and then when the writer is deleted, it invokes the LAME executable to convert the data to an MP3, whose data is then piped into the original OutputStream that was used when first creating the writer.
See also
AudioFormat
Constructor & Destructor Documentation
LAMEEncoderAudioFormat()
LAMEEncoderAudioFormat::LAMEEncoderAudioFormat (const File & lameExecutableToUse)
Creates a LAMEEncoderAudioFormat that expects to find a working LAME executable at the location given.
Referenced by createWriterFor().
~LAMEEncoderAudioFormat()
LAMEEncoderAudioFormat::~LAMEEncoderAudioFormat ()
Member Function Documentation
canHandleFile()
bool LAMEEncoderAudioFormat::canHandleFile (const File & fileToTest) virtual
Returns true if this the given file can be read by this format.
Subclasses shouldn't do too much work here, just check the extension or file type. The base class implementation just checks the file's extension against one of the ones that was registered in the constructor.
Reimplemented from AudioFormat.
getPossibleSampleRates()
Array< int > LAMEEncoderAudioFormat::getPossibleSampleRates () virtual
Returns a set of sample rates that the format can read and write.
Implements AudioFormat.
getPossibleBitDepths()
Array< int > LAMEEncoderAudioFormat::getPossibleBitDepths () virtual
Returns a set of bit depths that the format can read and write.
Implements AudioFormat.
canDoStereo()
bool LAMEEncoderAudioFormat::canDoStereo () virtual
Returns true if the format can do 2-channel audio.
Implements AudioFormat.
canDoMono()
bool LAMEEncoderAudioFormat::canDoMono () virtual
Returns true if the format can do 1-channel audio.
Implements AudioFormat.
isCompressed()
bool LAMEEncoderAudioFormat::isCompressed () virtual
Returns true if the format uses compressed data.
Reimplemented from AudioFormat.
getQualityOptions()
StringArray LAMEEncoderAudioFormat::getQualityOptions () virtual
Returns a list of different qualities that can be used when writing.
Non-compressed formats will just return an empty array, but for something like Ogg-Vorbis or MP3, it might return a list of bit-rates, etc.
When calling createWriterFor(), an index from this array is passed in to tell the format which option is required.
Reimplemented from AudioFormat.
createReaderFor()
AudioFormatReader * LAMEEncoderAudioFormat::createReaderFor (InputStream * sourceStream, bool deleteStreamIfOpeningFails) virtual
Tries to create an object that can read from a stream containing audio data in this format.
The reader object that is returned can be used to read from the stream, and should then be deleted by the caller.
Parameters
sourceStream the stream to read from - the AudioFormatReader object that is returned will delete this stream when it no longer needs it.
deleteStreamIfOpeningFails if no reader can be created, this determines whether this method should delete the stream object that was passed-in. (If a valid reader is returned, it will always be in charge of deleting the stream, so this parameter is ignored)
See also
AudioFormatReader
Implements AudioFormat.
createWriterFor() [1/2]
AudioFormatWriter * LAMEEncoderAudioFormat::createWriterFor (OutputStream * streamToWriteTo, double sampleRateToUse, unsigned int numberOfChannels, int bitsPerSample, const StringPairArray & metadataValues, int qualityOptionIndex) virtual
Tries to create an object that can write to a stream with this audio format.
The writer object that is returned can be used to write to the stream, and should then be deleted by the caller.
If the stream can't be created for some reason (e.g. the parameters passed in here aren't suitable), this will return nullptr.
Parameters
streamToWriteTo the stream that the data will go to - this will be deleted by the AudioFormatWriter object when it's no longer needed. If no AudioFormatWriter can be created by this method, the stream will NOT be deleted, so that the caller can re-use it to try to open a different format, etc
sampleRateToUse the sample rate for the file, which must be one of the ones returned by getPossibleSampleRates()
numberOfChannels the number of channels
bitsPerSample the bits per sample to use - this must be one of the values returned by getPossibleBitDepths()
metadataValues a set of metadata values that the writer should try to write to the stream. Exactly what these are depends on the format, and the subclass doesn't actually have to do anything with them if it doesn't want to. Have a look at the specific format implementation classes to see possible values that can be used
qualityOptionIndex the index of one of compression qualities returned by the getQualityOptions() method. If there aren't any quality options for this format, just pass 0 in this parameter, as it'll be ignored
See also
AudioFormatWriter
Implements AudioFormat.
References AudioFormat::createWriterFor(), and LAMEEncoderAudioFormat().
createWriterFor() [2/2]
virtual AudioFormatWriter * AudioFormat::createWriterFor (OutputStream * streamToWriteTo, double sampleRateToUse, const AudioChannelSet & channelLayout, int bitsPerSample, const StringPairArray & metadataValues, int qualityOptionIndex) virtual
Tries to create an object that can write to a stream with this audio format.
The writer object that is returned can be used to write to the stream, and should then be deleted by the caller.
If the stream can't be created for some reason (e.g. the parameters passed in here aren't suitable), this will return nullptr.
Parameters
streamToWriteTo the stream that the data will go to - this will be deleted by the AudioFormatWriter object when it's no longer needed. If no AudioFormatWriter can be created by this method, the stream will NOT be deleted, so that the caller can re-use it to try to open a different format, etc
sampleRateToUse the sample rate for the file, which must be one of the ones returned by getPossibleSampleRates()
channelLayout the channel layout for the file. Use isChannelLayoutSupported to check if the writer supports this layout.
bitsPerSample the bits per sample to use - this must be one of the values returned by getPossibleBitDepths()
metadataValues a set of metadata values that the writer should try to write to the stream. Exactly what these are depends on the format, and the subclass doesn't actually have to do anything with them if it doesn't want to. Have a look at the specific format implementation classes to see possible values that can be used
qualityOptionIndex the index of one of compression qualities returned by the getQualityOptions() method. If there aren't any quality options for this format, just pass 0 in this parameter, as it'll be ignored
See also
AudioFormatWriter
Reimplemented from AudioFormat.