JUCE: RuntimePermissions Class Reference
RuntimePermissions Class Reference
juce_core » misc
Public Types
enum PermissionID {
recordAudio = 1 , bluetoothMidi = 2 , readExternalStorage = 3 , writeExternalStorage = 4 ,
camera = 5 , readMediaAudio = 6 , readMediaImages = 7 , readMediaVideo = 8 ,
postNotification = 9
}
using Callback = std::function<void (bool)>
Function type of runtime permission request callbacks.
Static Public Member Functions
static void request (PermissionID permission, Callback callback)
Call this method to request a runtime permission.
static bool isRequired (PermissionID permission)
Returns whether a runtime request is required to obtain the permission on the current platform.
static bool isGranted (PermissionID permission)
Returns true if the app has been already granted this permission, either via a previous runtime request or otherwise, or no permission is necessary.
Detailed Description
Class to handle app runtime permissions for certain functionality on some platforms.
The use of this class is currently only required if the app should run on
Android API level 23 and higher.
On lower API levels, the permissions are specified in the app manifest. On iOS,
runtime permission requests are handled automatically by the Apple APIs and not
manually in the app code. On Windows, OS X, and Linux, runtime permissions are not
used at all. In all these cases, request() will simply call through to the
callback with no overhead and pass true (making it safe to use on all platforms).
For example, to enable audio recording on Android in your cross-platform app,
you could modify your code as follows:
Old code:
    audioDeviceManager.initialise (2, 2, nullptr, true, String(), nullptr);
New code:
    RuntimePermissions::request (
        RuntimePermissions::recordAudio,
        [this] (bool wasGranted)
        {
             if (! wasGranted)
             {
e.g. display an error or initialise with 0 input channels return; }
audioDeviceManager.initialise (2, 2, nullptr, true, String(), nullptr); });
Member Typedef Documentation
Callback
using RuntimePermissions::Callback = std::function<void (bool)>
Function type of runtime permission request callbacks.
Member Enumeration Documentation
PermissionID
enum RuntimePermissions::PermissionID
Enumerator
recordAudio
Permission to access the microphone (required on Android).
You need to request this, for example, to initialise an AudioDeviceManager with a non-zero number of input channels, and to open the default audio input device.
bluetoothMidi
Permission to scan for and pair to Bluetooth MIDI devices (required on Android).
You need to request this before calling BluetoothMidiDevicePairingDialogue::open(), otherwise no devices will be found.
readExternalStorage
Permission to read from external storage such as SD cards.
writeExternalStorage
Permission to write to external storage such as SD cards.
camera
Permission to use camera.
readMediaAudio
Permission to read audio files that your app didn't create.
Has the same effect as readExternalStorage on iOS and Android versions before 33.
readMediaImages
Permission to read image files that your app didn't create.
Has the same effect as readExternalStorage on iOS and Android versions before 33.
readMediaVideo
Permission to read video files that your app didn't create.
Has the same effect as readExternalStorage on iOS and Android versions before 33.
postNotification
Permission to post notifications.
See also
PushNotifications::requestPermissionsWithSettings
Member Function Documentation
request()
void RuntimePermissions::request (PermissionID permission, Callback callback) static
Call this method to request a runtime permission.
Parameters
permission The PermissionID of the permission you want to request.
callback The callback to be called after the request has been granted or denied; the argument passed will be true if the permission has been granted and false otherwise.
If no runtime request is required or possible to obtain the permission, the callback will be called immediately. The argument passed in will be true if the permission is granted or no permission is required on this platform, and false otherwise.
If a runtime request is required to obtain the permission, the callback will be called asynchronously after the OS has granted or denied the requested permission (typically by displaying a dialog box to the user and waiting until the user has responded).
Referenced by StandalonePluginHolder::StandalonePluginHolder().
isRequired()
bool RuntimePermissions::isRequired (PermissionID permission) static
Returns whether a runtime request is required to obtain the permission on the current platform.
Referenced by StandalonePluginHolder::StandalonePluginHolder().
isGranted()
bool RuntimePermissions::isGranted (PermissionID permission) static
Returns true if the app has been already granted this permission, either via a previous runtime request or otherwise, or no permission is necessary.
Note that this can be false even if isRequired returns false. In this case, the permission can not be obtained at all at runtime.
Referenced by StandalonePluginHolder::StandalonePluginHolder().