JUCE: Label::Listener Class Reference
Label::Listener Class Reference abstract
juce_gui_basics » widgets
A class for receiving events from a Label.
Public Member Functions
virtual ~Listener ()=default
Destructor.
virtual void labelTextChanged (Label *labelThatHasChanged)=0
Called when a Label's text has changed.
virtual void editorShown (Label *, TextEditor &)
Called when a Label goes into editing mode and displays a TextEditor.
virtual void editorHidden (Label *, TextEditor &)
Called when a Label is about to delete its TextEditor and exit editing mode.
Detailed Description
A class for receiving events from a Label.
You can register a Label::Listener with a Label using the Label::addListener() method, and it will be called when the text of the label changes, either because of a call to Label::setText() or by the user editing the text (if the label is editable).
See also
Label::addListener, Label::removeListener
Constructor & Destructor Documentation
~Listener()
virtual Label::Listener::~Listener () virtual default
Destructor.
Member Function Documentation
labelTextChanged()
virtual void Label::Listener::labelTextChanged (Label * labelThatHasChanged) pure virtual
Called when a Label's text has changed.
References Label::Label().
editorShown()
virtual void Label::Listener::editorShown (Label * , TextEditor &) virtual
Called when a Label goes into editing mode and displays a TextEditor.
References Label::Label().
editorHidden()
virtual void Label::Listener::editorHidden (Label * , TextEditor &) virtual
Called when a Label is about to delete its TextEditor and exit editing mode.
References Label::Label().