JUCE: RelativePointPath::CloseSubPath Class Reference
RelativePointPath::CloseSubPath Class Reference
juce_gui_basics » positioning
Class for the close sub path element.
Public Member Functions
CloseSubPath ()
void addToPath (Path &path, Expression::Scope *) const override
RelativePoint * getControlPoints (int &numPoints) override
ElementBase * clone () const override
Public Member Functions inherited from RelativePointPath::ElementBase
ElementBase (ElementType type)
virtual ~ElementBase ()=default
bool isDynamic ()
Additional Inherited Members
Public Attributes inherited from RelativePointPath::ElementBase
const ElementType type
Detailed Description
Class for the close sub path element.
Constructor & Destructor Documentation
CloseSubPath()
RelativePointPath::CloseSubPath::CloseSubPath ()
Referenced by clone().
Member Function Documentation
addToPath()
void RelativePointPath::CloseSubPath::addToPath (Path & path, Expression::Scope *) const override virtual
Implements RelativePointPath::ElementBase.
getControlPoints()
RelativePoint * RelativePointPath::CloseSubPath::getControlPoints (int & numPoints) override virtual
Implements RelativePointPath::ElementBase.
clone()
ElementBase * RelativePointPath::CloseSubPath::clone () const override virtual
Implements RelativePointPath::ElementBase.
References CloseSubPath(), and RelativePointPath::ElementBase::ElementBase().