JUCE: Graphics::ScopedSaveState Class Reference
Graphics::ScopedSaveState Class Reference
juce_graphics » contexts
Uses RAII to save and restore the state of a graphics context.
Public Member Functions
ScopedSaveState (Graphics &)
~ScopedSaveState ()
Detailed Description
Uses RAII to save and restore the state of a graphics context.
On construction, this calls Graphics::saveState(), and on destruction it calls Graphics::restoreState() on the Graphics object that you supply.
Constructor & Destructor Documentation
ScopedSaveState()
Graphics::ScopedSaveState::ScopedSaveState (Graphics &)
References Graphics::Graphics().
Referenced by ~ScopedSaveState().
~ScopedSaveState()
Graphics::ScopedSaveState::~ScopedSaveState ()
References Graphics::Graphics(), and ScopedSaveState().