JUCE: PerformanceCounter Class Reference
PerformanceCounter Class Reference
juce_core » time
A timer for measuring performance of code and dumping the results to a file.
Classes
struct Statistics
Holds the current statistics.
Public Member Functions
PerformanceCounter (const String &counterName, int runsPerPrintout=100, const File &loggingFile=File())
Creates a PerformanceCounter object.
~PerformanceCounter ()
Destructor.
void start () noexcept
Starts timing.
bool stop ()
Stops timing and prints out the results.
void printStatistics ()
Dumps the current metrics to the debugger output and to a file.
Statistics getStatisticsAndReset ()
Returns a copy of the current stats, and resets the internal counter.
Detailed Description
A timer for measuring performance of code and dumping the results to a file.
e.g.
PerformanceCounter pc ("fish", 50, "/temp/myfishlog.txt");
for (;;)
{
    pc.start();
    doSomethingFishy();
    pc.stop();
}
In this example, the time of each period between calling start/stop will be measured and averaged over 50 runs, and the results printed to a file every 50 times round the loop.
Constructor & Destructor Documentation
PerformanceCounter()
PerformanceCounter::PerformanceCounter (const String & counterName, int runsPerPrintout = 100, const File & loggingFile = File())
Creates a PerformanceCounter object.
Parameters
counterName the name used when printing out the statistics
runsPerPrintout the number of start/stop iterations before calling printStatistics()
loggingFile a file to dump the results to - if this is File(), the results are just written to the debugger output
Referenced by getStatisticsAndReset().
~PerformanceCounter()
PerformanceCounter::~PerformanceCounter ()
Destructor.
Member Function Documentation
start()
void PerformanceCounter::start () noexcept
Starts timing.
See also
stop
stop()
bool PerformanceCounter::stop ()
Stops timing and prints out the results.
The number of iterations before doing a printout of the results is set in the constructor.
See also
start
References stop().
Referenced by stop().
printStatistics()
void PerformanceCounter::printStatistics ()
Dumps the current metrics to the debugger output and to a file.
As well as using Logger::outputDebugString to print the results, this will write then to the file specified in the constructor (if this was valid).
References printStatistics().
Referenced by printStatistics().
getStatisticsAndReset()
Statistics PerformanceCounter::getStatisticsAndReset ()
Returns a copy of the current stats, and resets the internal counter.
References getStatisticsAndReset(), JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR, and PerformanceCounter().
Referenced by getStatisticsAndReset().