JUCE: RelativeParallelogram Class Reference
RelativeParallelogram Class Reference
juce_gui_basics » positioning
A parallelogram defined by three RelativePoint positions.
Public Member Functions
RelativeParallelogram ()
RelativeParallelogram (const Rectangle< float > &simpleRectangle)
RelativeParallelogram (const RelativePoint &topLeft, const RelativePoint &topRight, const RelativePoint &bottomLeft)
RelativeParallelogram (const String &topLeft, const String &topRight, const String &bottomLeft)
~RelativeParallelogram ()
void resolveThreePoints (Point< float > *points, Expression::Scope *scope) const
void resolveFourCorners (Point< float > *points, Expression::Scope *scope) const
const Rectangle< float > getBounds (Expression::Scope *scope) const
void getPath (Path &path, Expression::Scope *scope) const
AffineTransform resetToPerpendicular (Expression::Scope *scope)
bool isDynamic () const
bool operator== (const RelativeParallelogram &) const noexcept
bool operator!= (const RelativeParallelogram &) const noexcept
Static Public Member Functions
static Point< float > getInternalCoordForPoint (const Point< float > *parallelogramCorners, Point< float > point) noexcept
static Point< float > getPointForInternalCoord (const Point< float > *parallelogramCorners, Point< float > internalPoint) noexcept
static Rectangle< float > getBoundingBox (const Point< float > *parallelogramCorners) noexcept
Public Attributes
RelativePoint topLeft
RelativePoint topRight
RelativePoint bottomLeft
Detailed Description
A parallelogram defined by three RelativePoint positions.
See also
RelativePoint, RelativeCoordinate
Constructor & Destructor Documentation
RelativeParallelogram() [1/4]
RelativeParallelogram::RelativeParallelogram ()
Referenced by operator!=(), and operator==().
RelativeParallelogram() [2/4]
RelativeParallelogram::RelativeParallelogram (const Rectangle< float > & simpleRectangle)
RelativeParallelogram() [3/4]
RelativeParallelogram::RelativeParallelogram (const RelativePoint & topLeft, const RelativePoint & topRight, const RelativePoint & bottomLeft)
References bottomLeft, topLeft, and topRight.
RelativeParallelogram() [4/4]
RelativeParallelogram::RelativeParallelogram (const String & topLeft, const String & topRight, const String & bottomLeft)
References bottomLeft, topLeft, and topRight.
~RelativeParallelogram()
RelativeParallelogram::~RelativeParallelogram ()
Member Function Documentation
resolveThreePoints()
void RelativeParallelogram::resolveThreePoints (Point< float > * points, Expression::Scope * scope) const
References Point.
resolveFourCorners()
void RelativeParallelogram::resolveFourCorners (Point< float > * points, Expression::Scope * scope) const
References Point.
getBounds()
const Rectangle< float > RelativeParallelogram::getBounds (Expression::Scope * scope) const
getPath()
void RelativeParallelogram::getPath (Path & path, Expression::Scope * scope) const
resetToPerpendicular()
AffineTransform RelativeParallelogram::resetToPerpendicular (Expression::Scope * scope)
isDynamic()
bool RelativeParallelogram::isDynamic () const
operator==()
bool RelativeParallelogram::operator== (const RelativeParallelogram &) const noexcept
References RelativeParallelogram().
operator!=()
bool RelativeParallelogram::operator!= (const RelativeParallelogram &) const noexcept
References RelativeParallelogram().
getInternalCoordForPoint()
Point< float > RelativeParallelogram::getInternalCoordForPoint (const Point< float > * parallelogramCorners, Point< float > point) static noexcept
References Point.
getPointForInternalCoord()
Point< float > RelativeParallelogram::getPointForInternalCoord (const Point< float > * parallelogramCorners, Point< float > internalPoint) static noexcept
References Point.
getBoundingBox()
Rectangle< float > RelativeParallelogram::getBoundingBox (const Point< float > * parallelogramCorners) static noexcept
References Point.
Member Data Documentation
topLeft
RelativePoint RelativeParallelogram::topLeft
Referenced by RelativeParallelogram(), and RelativeParallelogram().
topRight
RelativePoint RelativeParallelogram::topRight
Referenced by RelativeParallelogram(), and RelativeParallelogram().
bottomLeft
RelativePoint RelativeParallelogram::bottomLeft
Referenced by RelativeParallelogram(), and RelativeParallelogram().