JUCE: ScopedMessageBox Class Reference
ScopedMessageBox Class Reference
juce_gui_basics » windows
Objects of this type can be used to programmatically close message boxes.
Public Member Functions
ScopedMessageBox (std::shared_ptr< detail::ScopedMessageBoxImpl >)
ScopedMessageBox ()
Constructor.
~ScopedMessageBox () noexcept
Destructor.
ScopedMessageBox (ScopedMessageBox &&) noexcept
Move constructor.
ScopedMessageBox & operator= (ScopedMessageBox &&) noexcept
Move assignment operator.
void close ()
Closes the message box, if it is currently showing.
Detailed Description
Objects of this type can be used to programmatically close message boxes.
See also
NativeMessageBox::showScopedAsync(), AlertWindow::showScopedAsync()
Constructor & Destructor Documentation
ScopedMessageBox() [1/3]
ScopedMessageBox::ScopedMessageBox (std::shared_ptr< detail::ScopedMessageBoxImpl >) explicit
Referenced by close(), operator=(), and ScopedMessageBox().
ScopedMessageBox() [2/3]
ScopedMessageBox::ScopedMessageBox ()
Constructor.
~ScopedMessageBox()
ScopedMessageBox::~ScopedMessageBox () noexcept
Destructor.
ScopedMessageBox() [3/3]
ScopedMessageBox::ScopedMessageBox (ScopedMessageBox &&) noexcept
Move constructor.
References ScopedMessageBox().
Member Function Documentation
operator=()
ScopedMessageBox & ScopedMessageBox::operator= (ScopedMessageBox &&) noexcept
Move assignment operator.
References ScopedMessageBox().
close()
void ScopedMessageBox::close ()
Closes the message box, if it is currently showing.
This is also called automatically during ~ScopedMessageBox. This is useful if you want to display a message corresponding to a particular view, and hide the message automatically when the view is hidden. This situation commonly arises when displaying messages in plugin editors.
References close(), JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR, and ScopedMessageBox().
Referenced by close().