JUCE: AudioProcessorParameterWithIDAttributes Class Reference
AudioProcessorParameterWithIDAttributes Class Reference
juce_audio_processors » utilities
An instance of this class may be passed to the constructor of an AudioProcessorParameterWithID to set optional characteristics of that parameter.
Public Types
using Category = AudioProcessorParameter::Category
Public Member Functions
auto withLabel (String x) const
An optional label for the parameter's value.
auto withCategory (Category x) const
The semantics of this parameter.
auto withMeta (bool x) const
auto withAutomatable (bool x) const
auto withInverted (bool x) const
auto getLabel () const
An optional label for the parameter's value.
auto getCategory () const
The semantics of this parameter.
auto getMeta () const
auto getAutomatable () const
auto getInverted () const
Detailed Description
An instance of this class may be passed to the constructor of an AudioProcessorParameterWithID to set optional characteristics of that parameter.
Member Typedef Documentation
Category
using AudioProcessorParameterWithIDAttributes::Category = AudioProcessorParameter::Category
Member Function Documentation
withLabel()
auto AudioProcessorParameterWithIDAttributes::withLabel (String x) const nodiscard
An optional label for the parameter's value.
References withMember(), and x.
withCategory()
auto AudioProcessorParameterWithIDAttributes::withCategory (Category x) const nodiscard
The semantics of this parameter.
References withMember(), and x.
withMeta()
auto AudioProcessorParameterWithIDAttributes::withMeta (bool x) const nodiscard
See also
AudioProcessorParameter::isMetaParameter()
References withMember(), and x.
withAutomatable()
auto AudioProcessorParameterWithIDAttributes::withAutomatable (bool x) const nodiscard
See also
AudioProcessorParameter::isAutomatable()
References withMember(), and x.
withInverted()
auto AudioProcessorParameterWithIDAttributes::withInverted (bool x) const nodiscard
See also
AudioProcessorParameter::isOrientationInverted()
References withMember(), and x.
getLabel()
auto AudioProcessorParameterWithIDAttributes::getLabel () const nodiscard
An optional label for the parameter's value.
getCategory()
auto AudioProcessorParameterWithIDAttributes::getCategory () const nodiscard
The semantics of this parameter.
getMeta()
auto AudioProcessorParameterWithIDAttributes::getMeta () const nodiscard
See also
AudioProcessorParameter::isMetaParameter()
getAutomatable()
auto AudioProcessorParameterWithIDAttributes::getAutomatable () const nodiscard
See also
AudioProcessorParameter::isAutomatable()
getInverted()
auto AudioProcessorParameterWithIDAttributes::getInverted () const nodiscard
See also
AudioProcessorParameter::isOrientationInverted()