JUCE: juce::midi_ci::RequestKey Class Reference
juce::midi_ci::RequestKey Class Reference
juce_midi_ci » ci
A key used to uniquely identify ongoing transactions initiated by a ci::Device.
Public Member Functions
RequestKey (MUID muid, Token64 key)
Constructor.
MUID getMuid () const
Returns the muid of the device to which we are subscribed.
Token64 getKey () const
Returns an identifier unique to this subscription.
bool operator== (const RequestKey &other) const
Equality operator.
bool operator!= (const RequestKey &other) const
Inequality operator.
bool operator< (const RequestKey &other) const
Less-than operator.
Detailed Description
A key used to uniquely identify ongoing transactions initiated by a ci::Device.
Constructor & Destructor Documentation
RequestKey()
juce::midi_ci::RequestKey::RequestKey (MUID muid, Token64 key)
Constructor.
Referenced by operator!=(), operator<(), and operator==().
Member Function Documentation
getMuid()
MUID juce::midi_ci::RequestKey::getMuid () const
Returns the muid of the device to which we are subscribed.
getKey()
Token64 juce::midi_ci::RequestKey::getKey () const
Returns an identifier unique to this subscription.
operator==()
bool juce::midi_ci::RequestKey::operator== (const RequestKey & other) const
Equality operator.
References RequestKey().
operator!=()
bool juce::midi_ci::RequestKey::operator!= (const RequestKey & other) const
Inequality operator.
References RequestKey().
operator<()
bool juce::midi_ci::RequestKey::operator< (const RequestKey & other) const
Less-than operator.
References RequestKey().