JUCE: format_types
format_types
juce_audio_processors
Namespaces
namespace ARA
namespace ARAHostModel
namespace Steinberg
namespace Presonus
Classes
class ARAFactoryWrapper
Encapsulates an ARAFactory pointer and makes sure that it remains in a valid state for the lifetime of the ARAFactoryWrapper object.
struct ARAFactoryResult
Represents the result of AudioPluginFormatManager::createARAFactoryAsync().
class ARAEditGuard
Reference counting helper class to ensure that the DocumentController is in editable state.
struct ARAHostModel::ConversionFunctions< A, B >
Allows converting, without warnings, between pointers of two unrelated types.
class ARAHostModel::ManagedARAHandle< Base, PtrIn >
This class is used by the various ARA model object helper classes, such as MusicalContext, AudioSource etc.
class ARAHostModel::AudioSource
Helper class for the host side implementation of the ARA AudioSource model object.
class ARAHostModel::AudioModification
Helper class for the host side implementation of the ARA AudioModification model object.
struct ARAHostModel::DeletionListener
This class is used internally by PlaybackRegionRegistry to be notified when a PlaybackRegion object is deleted.
struct ARAHostModel::PlaybackRegion
Helper class for the host side implementation of the ARA PlaybackRegion model object.
class ARAHostModel::MusicalContext
Helper class for the host side implementation of the ARA MusicalContext model object.
class ARAHostModel::RegionSequence
Helper class for the host side implementation of the ARA RegionSequence model object.
class ARAHostModel::PlaybackRegionRegistry< RendererRef, Interface >
Base class used by the PlaybackRendererInterface and EditorRendererInterface plugin extension interfaces.
class ARAHostModel::PlugInExtensionInstance
Wrapper class for ARA::ARAPlugInExtensionInstance*.
class ARAHostDocumentController
Wrapper class for ARA::Host::DocumentController.
class AudioUnitPluginFormat
Implements a plugin format manager for AudioUnits.
class LADSPAPluginFormat
Implements a plugin format manager for LADSPA plugins.
class LV2PluginFormat
Implements a plugin format for LV2 plugins.
class VST3PluginFormat
Implements a plugin format for VST3s.
struct SpeakerMappings
Structure for VST speaker mappings.
struct SpeakerMappings::Mapping
Structure describing a mapping.
class SpeakerMappings::VstSpeakerConfigurationHolder
Class to hold a speaker configuration.
class VSTPluginFormat
Implements a plugin format manager for VSTs.
class VSTPluginFormat::ExtraFunctions
Base class for some extra functions that can be attached to a VST plugin instance.
Macros
#define DEVELOPMENT 0
#define NOMINMAX
#define LILV_DYN_MANIFEST
#define LILV_STATIC
#define LV2_STATIC
#define SERD_STATIC
#define SORD_STATIC
#define SRATOM_STATIC
#define ZIX_STATIC
#define LILV_VERSION "0.24.12"
#define SERD_VERSION "0.30.10"
#define SORD_VERSION "0.16.9"
#define LILV_CXX 1
#define LILV_DIR_SEP "/"
#define LILV_PATH_SEP ":"
#define LILV_DEFAULT_LV2_PATH
Functions
template<typename Obj, typename Member, typename... Ts>
constexpr Obj makeARASizedStruct (Member Obj::*member, Ts &&... ts)
void JUCE_API createARAFactoryAsync (AudioPluginInstance &instance, std::function< void(ARAFactoryWrapper)> cb)
Calls the provided callback with an ARAFactoryWrapper object obtained from the provided AudioPluginInstance.
Detailed Description
Macro Definition Documentation
DEVELOPMENT
#define DEVELOPMENT 0
NOMINMAX
#define NOMINMAX
LILV_DYN_MANIFEST
#define LILV_DYN_MANIFEST
LILV_STATIC
#define LILV_STATIC
LV2_STATIC
#define LV2_STATIC
SERD_STATIC
#define SERD_STATIC
SORD_STATIC
#define SORD_STATIC
SRATOM_STATIC
#define SRATOM_STATIC
ZIX_STATIC
#define ZIX_STATIC
LILV_VERSION
#define LILV_VERSION "0.24.12"
SERD_VERSION
#define SERD_VERSION "0.30.10"
SORD_VERSION
#define SORD_VERSION "0.16.9"
LILV_CXX
#define LILV_CXX 1
LILV_DIR_SEP
#define LILV_DIR_SEP "/"
LILV_PATH_SEP
#define LILV_PATH_SEP ":"
LILV_DEFAULT_LV2_PATH
#define LILV_DEFAULT_LV2_PATH
Value:
    "~/Library/Audio/Plug-Ins/LV2"  LILV_PATH_SEP \
    "~/.lv2"                        LILV_PATH_SEP \
    "/usr/local/lib/lv2"            LILV_PATH_SEP \
    "/usr/lib/lv2"                  LILV_PATH_SEP \
    "/Library/Audio/Plug-Ins/LV2"
Function Documentation
makeARASizedStruct()
template<typename Obj, typename Member, typename... Ts> Obj makeARASizedStruct (Member Obj::* member, Ts &&... ts) constexpr
References makeARASizedStruct().
Referenced by ARAHostModel::AudioModification::getEmptyProperties(), ARAHostModel::AudioSource::getEmptyProperties(), ARAHostModel::MusicalContext::getEmptyProperties(), ARAHostModel::PlaybackRegion::getEmptyProperties(), ARAHostModel::RegionSequence::getEmptyProperties(), and makeARASizedStruct().
createARAFactoryAsync()
void JUCE_API createARAFactoryAsync (AudioPluginInstance & instance, std::function< void(ARAFactoryWrapper)> cb)
Calls the provided callback with an ARAFactoryWrapper object obtained from the provided AudioPluginInstance.
If the provided AudioPluginInstance has no ARA extensions, the callback will be called with an ARAFactoryWrapper that wraps a nullptr.
The object passed to the callback must be checked even if the plugin instance reports having ARA extensions.
References JUCE_API.