JUCE: animation
animation
juce_animation
Classes
class Animator
Wrapper class for managing the lifetime of all the different animator kinds created through the builder classes.
struct Animator::Compare
Comparison function used by the implementation to store Animators in ordered collections.
class Animator::Weak
class AnimatorSetBuilder
A builder class that can be used to construct an Animator wrapping an AnimatorSet implementation.
class AnimatorUpdater
Helper class to update several animators at once, without owning or otherwise extending the lifetimes of those animators.
class SpringEasingOptions
A selection of options available for customising a spring style easing function.
struct Easings
Holds a number of easing functions that you can pass into ValueAnimatorBuilder::withEasing to transform the linear progression of animations.
class StaticAnimationLimits< ValueType >
Helper class for using linear interpolation between a begin and an end value.
class ValueAnimatorBuilder
A builder class that can be used to construct an Animator wrapping a ValueAnimator implementation.
class VBlankAnimatorUpdater
Similar to AnimatorUpdater, but automatically calls update() whenever the screen refreshes.
Functions
template<typename ValueType>
StaticAnimationLimits< ValueType > makeAnimationLimits (const ValueType &end)
Creates an instance of StaticAnimationLimits, deducing ValueType from the function argument.
template<typename ValueType>
StaticAnimationLimits< ValueType > makeAnimationLimits (const ValueType &begin, const ValueType &end)
Creates an instance of StaticAnimationLimits, deducing ValueType from the function arguments.
Detailed Description
Function Documentation
makeAnimationLimits() [1/2]
template<typename ValueType> StaticAnimationLimits< ValueType > makeAnimationLimits (const ValueType & end)
Creates an instance of StaticAnimationLimits, deducing ValueType from the function argument.
References end().
makeAnimationLimits() [2/2]
template<typename ValueType> StaticAnimationLimits< ValueType > makeAnimationLimits (const ValueType & begin, const ValueType & end)
Creates an instance of StaticAnimationLimits, deducing ValueType from the function arguments.
References begin(), and end().