JUCE: juce::midi_ci::Message::ProfileOff Struct Reference
juce::midi_ci::Message::ProfileOff Struct Reference
juce_midi_ci » ci
See the MIDI-CI specification.
Public Member Functions
auto tie () const
bool operator== (const ProfileOff &x) const
bool operator!= (const ProfileOff &x) const
Public Attributes
Profile profile {}
Detailed Description
See the MIDI-CI specification.
Member Function Documentation
tie()
auto juce::midi_ci::Message::ProfileOff::tie () const
References profile.
Referenced by operator==().
operator==()
bool juce::midi_ci::Message::ProfileOff::operator== (const ProfileOff & x) const
References tie(), and x.
Referenced by operator!=().
operator!=()
bool juce::midi_ci::Message::ProfileOff::operator!= (const ProfileOff & x) const
References operator==(), and x.
Member Data Documentation
profile
Profile juce::midi_ci::Message::ProfileOff::profile {}
Referenced by tie().