JUCE: TableHeaderComponent::LookAndFeelMethods Struct Reference
TableHeaderComponent::LookAndFeelMethods Struct Reference abstract
juce_gui_basics » widgets
This abstract base class is implemented by LookAndFeel classes.
Public Member Functions
virtual ~LookAndFeelMethods ()=default
virtual void drawTableHeaderBackground (Graphics &, TableHeaderComponent &)=0
virtual void drawTableHeaderColumn (Graphics &, TableHeaderComponent &, const String &columnName, int columnId, int width, int height, bool isMouseOver, bool isMouseDown, int columnFlags)=0
Detailed Description
This abstract base class is implemented by LookAndFeel classes.
Constructor & Destructor Documentation
~LookAndFeelMethods()
virtual TableHeaderComponent::LookAndFeelMethods::~LookAndFeelMethods () virtual default
Member Function Documentation
drawTableHeaderBackground()
virtual void TableHeaderComponent::LookAndFeelMethods::drawTableHeaderBackground (Graphics & , TableHeaderComponent &) pure virtual
Implemented in LookAndFeel_V2, and LookAndFeel_V3.
References TableHeaderComponent::TableHeaderComponent().
drawTableHeaderColumn()
virtual void TableHeaderComponent::LookAndFeelMethods::drawTableHeaderColumn (Graphics & , TableHeaderComponent & , const String & columnName, int columnId, int width, int height, bool isMouseOver, bool isMouseDown, int columnFlags) pure virtual
Implemented in LookAndFeel_V2.
References Component::isMouseOver(), and TableHeaderComponent::TableHeaderComponent().