JUCE: NamedValueSet::NamedValue Struct Reference
NamedValueSet::NamedValue Struct Reference
juce_core » containers
Structure for a named var object.
Public Member Functions
NamedValue () noexcept
~NamedValue () noexcept
NamedValue (const Identifier &name, const var &value)
NamedValue (const Identifier &name, var &&value) noexcept
NamedValue (Identifier &&name, var &&value) noexcept
NamedValue (const NamedValue &)
NamedValue (NamedValue &&) noexcept
NamedValue & operator= (NamedValue &&) noexcept
bool operator== (const NamedValue &) const noexcept
bool operator!= (const NamedValue &) const noexcept
Public Attributes
Identifier name
var value
Detailed Description
Structure for a named var object.
Constructor & Destructor Documentation
NamedValue() [1/6]
NamedValueSet::NamedValue::NamedValue () noexcept
Referenced by NamedValue(), NamedValue(), NamedValue(), NamedValue(), NamedValue(), operator!=(), operator=(), operator==(), and ~NamedValue().
~NamedValue()
NamedValueSet::NamedValue::~NamedValue () noexcept
References NamedValue().
NamedValue() [2/6]
NamedValueSet::NamedValue::NamedValue (const Identifier & name, const var & value)
References name, NamedValue(), and value.
NamedValue() [3/6]
NamedValueSet::NamedValue::NamedValue (const Identifier & name, var && value) noexcept
References name, NamedValue(), and value.
NamedValue() [4/6]
NamedValueSet::NamedValue::NamedValue (Identifier && name, var && value) noexcept
References name, NamedValue(), and value.
NamedValue() [5/6]
NamedValueSet::NamedValue::NamedValue (const NamedValue &)
References NamedValue().
NamedValue() [6/6]
NamedValueSet::NamedValue::NamedValue (NamedValue &&) noexcept
References NamedValue().
Member Function Documentation
operator=()
NamedValue & NamedValueSet::NamedValue::operator= (NamedValue &&) noexcept
References NamedValue().
operator==()
bool NamedValueSet::NamedValue::operator== (const NamedValue &) const noexcept
References NamedValue().
operator!=()
bool NamedValueSet::NamedValue::operator!= (const NamedValue &) const noexcept
References NamedValue().
Member Data Documentation
name
Identifier NamedValueSet::NamedValue::name
Referenced by NamedValue(), NamedValue(), and NamedValue().
value
var NamedValueSet::NamedValue::value
Referenced by NamedValue(), NamedValue(), and NamedValue().