JUCE: juce::midi_ci::Message::ProfileDetails Struct Reference
juce::midi_ci::Message::ProfileDetails Struct Reference
juce_midi_ci » ci
See the MIDI-CI specification.
Public Member Functions
auto tie () const
bool operator== (const ProfileDetails &x) const
bool operator!= (const ProfileDetails &x) const
Public Attributes
Profile profile {}
std::byte target {}
Detailed Description
See the MIDI-CI specification.
Member Function Documentation
tie()
auto juce::midi_ci::Message::ProfileDetails::tie () const
References profile, and target.
Referenced by operator==().
operator==()
bool juce::midi_ci::Message::ProfileDetails::operator== (const ProfileDetails & x) const
References tie(), and x.
Referenced by operator!=().
operator!=()
bool juce::midi_ci::Message::ProfileDetails::operator!= (const ProfileDetails & x) const
References operator==(), and x.
Member Data Documentation
profile
Profile juce::midi_ci::Message::ProfileDetails::profile {}
Referenced by tie().
target
std::byte juce::midi_ci::Message::ProfileDetails::target {}
Referenced by tie().