JUCE: ValueTree::Iterator Struct Reference
ValueTree::Iterator Struct Reference
juce_data_structures » values
Iterator for a ValueTree.
Public Types
using difference_type = std::ptrdiff_t
using value_type = ValueTree
using reference = ValueTree&
using pointer = ValueTree*
using iterator_category = std::forward_iterator_tag
Public Member Functions
Iterator (const ValueTree &, bool isEnd)
Iterator & operator++ ()
bool operator== (const Iterator &) const
bool operator!= (const Iterator &) const
ValueTree operator* () const
Detailed Description
Iterator for a ValueTree.
You shouldn't ever need to use this class directly - it's used internally by ValueTree::begin() and ValueTree::end() to allow range-based-for loops on a ValueTree.
Member Typedef Documentation
difference_type
using ValueTree::Iterator::difference_type = std::ptrdiff_t
value_type
using ValueTree::Iterator::value_type = ValueTree
reference
using ValueTree::Iterator::reference = ValueTree&
pointer
using ValueTree::Iterator::pointer = ValueTree*
iterator_category
using ValueTree::Iterator::iterator_category = std::forward_iterator_tag
Constructor & Destructor Documentation
Iterator()
ValueTree::Iterator::Iterator (const ValueTree & , bool isEnd)
References ValueTree::ValueTree().
Referenced by operator!=(), operator++(), and operator==().
Member Function Documentation
operator++()
Iterator & ValueTree::Iterator::operator++ ()
References Iterator().
operator==()
bool ValueTree::Iterator::operator== (const Iterator &) const
References Iterator().
operator!=()
bool ValueTree::Iterator::operator!= (const Iterator &) const
References Iterator().
operator*()
ValueTree ValueTree::Iterator::operator* () const
References ValueTree::ValueTree().