JUCE: TreeView::LookAndFeelMethods Struct Reference
TreeView::LookAndFeelMethods Struct Reference abstract
juce_gui_basics » widgets
This abstract base class is implemented by LookAndFeel classes to provide TreeView drawing functionality.
Public Member Functions
virtual ~LookAndFeelMethods ()=default
virtual void drawTreeviewPlusMinusBox (Graphics &, const Rectangle< float > &area, Colour backgroundColour, bool isItemOpen, bool isMouseOver)=0
virtual bool areLinesDrawnForTreeView (TreeView &)=0
virtual int getTreeViewIndentSize (TreeView &)=0
Detailed Description
This abstract base class is implemented by LookAndFeel classes to provide TreeView drawing functionality.
Constructor & Destructor Documentation
~LookAndFeelMethods()
virtual TreeView::LookAndFeelMethods::~LookAndFeelMethods () virtual default
Member Function Documentation
drawTreeviewPlusMinusBox()
virtual void TreeView::LookAndFeelMethods::drawTreeviewPlusMinusBox (Graphics & , const Rectangle< float > & area, Colour backgroundColour, bool isItemOpen, bool isMouseOver) pure virtual
Implemented in LookAndFeel_V2, and LookAndFeel_V3.
References Component::isMouseOver().
areLinesDrawnForTreeView()
virtual bool TreeView::LookAndFeelMethods::areLinesDrawnForTreeView (TreeView &) pure virtual
Implemented in LookAndFeel_V2, and LookAndFeel_V3.
References TreeView::TreeView().
getTreeViewIndentSize()
virtual int TreeView::LookAndFeelMethods::getTreeViewIndentSize (TreeView &) pure virtual
Implemented in LookAndFeel_V2, and LookAndFeel_V3.
References TreeView::TreeView().