JUCE: PropertyComponent::LookAndFeelMethods Struct Reference
PropertyComponent::LookAndFeelMethods Struct Reference abstract
juce_gui_basics » properties
This abstract base class is implemented by LookAndFeel classes.
Public Member Functions
virtual ~LookAndFeelMethods ()=default
virtual void drawPropertyPanelSectionHeader (Graphics &, const String &name, bool isOpen, int width, int height)=0
virtual void drawPropertyComponentBackground (Graphics &, int width, int height, PropertyComponent &)=0
virtual void drawPropertyComponentLabel (Graphics &, int width, int height, PropertyComponent &)=0
virtual Rectangle< int > getPropertyComponentContentPosition (PropertyComponent &)=0
virtual int getPropertyPanelSectionHeaderHeight (const String &sectionTitle)=0
Detailed Description
This abstract base class is implemented by LookAndFeel classes.
Constructor & Destructor Documentation
~LookAndFeelMethods()
virtual PropertyComponent::LookAndFeelMethods::~LookAndFeelMethods () virtual default
Member Function Documentation
drawPropertyPanelSectionHeader()
virtual void PropertyComponent::LookAndFeelMethods::drawPropertyPanelSectionHeader (Graphics & , const String & name, bool isOpen, int width, int height) pure virtual
Implemented in LookAndFeel_V2, and LookAndFeel_V4.
References name.
drawPropertyComponentBackground()
virtual void PropertyComponent::LookAndFeelMethods::drawPropertyComponentBackground (Graphics & , int width, int height, PropertyComponent &) pure virtual
Implemented in LookAndFeel_V2, and LookAndFeel_V4.
References PropertyComponent::PropertyComponent().
drawPropertyComponentLabel()
virtual void PropertyComponent::LookAndFeelMethods::drawPropertyComponentLabel (Graphics & , int width, int height, PropertyComponent &) pure virtual
Implemented in LookAndFeel_V2, and LookAndFeel_V4.
References PropertyComponent::PropertyComponent().
getPropertyComponentContentPosition()
virtual Rectangle< int > PropertyComponent::LookAndFeelMethods::getPropertyComponentContentPosition (PropertyComponent &) pure virtual
Implemented in LookAndFeel_V2, and LookAndFeel_V4.
References PropertyComponent::PropertyComponent().
getPropertyPanelSectionHeaderHeight()
virtual int PropertyComponent::LookAndFeelMethods::getPropertyPanelSectionHeaderHeight (const String & sectionTitle) pure virtual
Implemented in LookAndFeel_V2.