JUCE: ExtensionsVisitor Struct Reference
ExtensionsVisitor Struct Reference
juce_audio_processors » utilities
Create a derived implementation of this class and pass it to AudioPluginInstance::getExtensions() to retrieve format-specific information about a plugin instance.
Classes
struct ARAClient
Can be used to retrieve information about a plugin that provides ARA extensions.
struct AudioUnitClient
Can be used to retrieve information about an AudioUnit that is wrapped by an AudioProcessor.
struct Unknown
Indicates that there is no platform specific information available.
struct VST3Client
Can be used to retrieve information about a VST3 that is wrapped by an AudioProcessor.
struct VSTClient
Can be used to retrieve information about a VST that is wrapped by an AudioProcessor.
Public Member Functions
ExtensionsVisitor ()=default
ExtensionsVisitor (const ExtensionsVisitor &)=default
ExtensionsVisitor (ExtensionsVisitor &&)=default
ExtensionsVisitor & operator= (const ExtensionsVisitor &)=default
ExtensionsVisitor & operator= (ExtensionsVisitor &&)=default
virtual ~ExtensionsVisitor ()=default
virtual void visitUnknown (const Unknown &)
Will be called if there is no platform specific information available.
virtual void visitVST3Client (const VST3Client &)
Called with VST3-specific information.
virtual void visitVSTClient (const VSTClient &)
Called with VST-specific information.
virtual void visitAudioUnitClient (const AudioUnitClient &)
Called with AU-specific information.
virtual void visitARAClient (const ARAClient &)
Called with ARA-specific information.
Detailed Description
Create a derived implementation of this class and pass it to AudioPluginInstance::getExtensions() to retrieve format-specific information about a plugin instance.
Note that the references passed to the visit member functions are only guaranteed to live for the duration of the function call, so don't store pointers to these objects! If you need to store and reuse format-specific information, it is recommended to copy the result of the function calls that you care about. For example, you should store the result of VST::getAEffectPtr() rather than storing a pointer to the VST instance.
Constructor & Destructor Documentation
ExtensionsVisitor() [1/3]
ExtensionsVisitor::ExtensionsVisitor () default
Referenced by ExtensionsVisitor(), ExtensionsVisitor(), operator=(), and operator=().
ExtensionsVisitor() [2/3]
ExtensionsVisitor::ExtensionsVisitor (const ExtensionsVisitor &) default
References ExtensionsVisitor().
ExtensionsVisitor() [3/3]
ExtensionsVisitor::ExtensionsVisitor (ExtensionsVisitor &&) default
References ExtensionsVisitor().
~ExtensionsVisitor()
virtual ExtensionsVisitor::~ExtensionsVisitor () virtual default
Member Function Documentation
operator=() [1/2]
ExtensionsVisitor & ExtensionsVisitor::operator= (const ExtensionsVisitor &) default
References ExtensionsVisitor().
operator=() [2/2]
ExtensionsVisitor & ExtensionsVisitor::operator= (ExtensionsVisitor &&) default
References ExtensionsVisitor().
visitUnknown()
virtual void ExtensionsVisitor::visitUnknown (const Unknown &) virtual
Will be called if there is no platform specific information available.
visitVST3Client()
virtual void ExtensionsVisitor::visitVST3Client (const VST3Client &) virtual
Called with VST3-specific information.
visitVSTClient()
virtual void ExtensionsVisitor::visitVSTClient (const VSTClient &) virtual
Called with VST-specific information.
visitAudioUnitClient()
virtual void ExtensionsVisitor::visitAudioUnitClient (const AudioUnitClient &) virtual
Called with AU-specific information.
visitARAClient()
virtual void ExtensionsVisitor::visitARAClient (const ARAClient &) virtual
Called with ARA-specific information.