JUCE: juce::midi_ci::Message::ProfileDisabledReport Struct Reference
juce::midi_ci::Message::ProfileDisabledReport Struct Reference
juce_midi_ci » ci
See the MIDI-CI specification.
Public Member Functions
auto tie () const
bool operator== (const ProfileDisabledReport &x) const
bool operator!= (const ProfileDisabledReport &x) const
Public Attributes
Profile profile {}
uint16_t numChannels {}
Only valid if the message header specifies version 0x02 or greater.
Detailed Description
See the MIDI-CI specification.
Member Function Documentation
tie()
auto juce::midi_ci::Message::ProfileDisabledReport::tie () const
References numChannels, and profile.
Referenced by operator==().
operator==()
bool juce::midi_ci::Message::ProfileDisabledReport::operator== (const ProfileDisabledReport & x) const
References tie(), and x.
Referenced by operator!=().
operator!=()
bool juce::midi_ci::Message::ProfileDisabledReport::operator!= (const ProfileDisabledReport & x) const
References operator==(), and x.
Member Data Documentation
profile
Profile juce::midi_ci::Message::ProfileDisabledReport::profile {}
Referenced by tie().
numChannels
uint16_t juce::midi_ci::Message::ProfileDisabledReport::numChannels {}
Only valid if the message header specifies version 0x02 or greater.
Referenced by tie().