JUCE: GridItem::Property Struct Reference
GridItem::Property Struct Reference
juce_gui_basics » layout
Represents a property.
Public Member Functions
Property () noexcept
Property (Keyword keyword) noexcept
Property (const char *lineNameToUse) noexcept
Property (const String &lineNameToUse) noexcept
Property (int numberToUse) noexcept
Property (int numberToUse, const String &lineNameToUse) noexcept
Property (Span spanToUse) noexcept
bool hasSpan () const noexcept
bool hasAbsolute () const noexcept
bool hasAuto () const noexcept
bool hasName () const noexcept
const String & getName () const noexcept
int getNumber () const noexcept
Detailed Description
Represents a property.
Constructor & Destructor Documentation
Property() [1/7]
GridItem::Property::Property () noexcept
Referenced by Property(), Property(), Property(), Property(), Property(), and Property().
Property() [2/7]
GridItem::Property::Property (Keyword keyword) noexcept
References Property().
Property() [3/7]
GridItem::Property::Property (const char * lineNameToUse) noexcept
References Property().
Property() [4/7]
GridItem::Property::Property (const String & lineNameToUse) noexcept
References Property().
Property() [5/7]
GridItem::Property::Property (int numberToUse) noexcept
References Property().
Property() [6/7]
GridItem::Property::Property (int numberToUse, const String & lineNameToUse) noexcept
References Property().
Property() [7/7]
GridItem::Property::Property (Span spanToUse) noexcept
References Property().
Member Function Documentation
hasSpan()
bool GridItem::Property::hasSpan () const noexcept
References hasSpan().
Referenced by hasSpan().
hasAbsolute()
bool GridItem::Property::hasAbsolute () const noexcept
hasAuto()
bool GridItem::Property::hasAuto () const noexcept
hasName()
bool GridItem::Property::hasName () const noexcept
getName()
const String & GridItem::Property::getName () const noexcept
getNumber()
int GridItem::Property::getNumber () const noexcept