JUCE: MathConstants< FloatType > Struct Template Reference
MathConstants< FloatType > Struct Template Reference
juce_core » maths
Commonly used mathematical constants.
Static Public Attributes
static constexpr FloatType pi = static_cast<FloatType> (3.141592653589793238L)
A predefined value for Pi.
static constexpr FloatType twoPi = static_cast<FloatType> (2 * 3.141592653589793238L)
A predefined value for 2 * Pi.
static constexpr FloatType halfPi = static_cast<FloatType> (3.141592653589793238L / 2)
A predefined value for Pi / 2.
static constexpr FloatType euler = static_cast<FloatType> (2.71828182845904523536L)
A predefined value for Euler's number.
static constexpr FloatType sqrt2 = static_cast<FloatType> (1.4142135623730950488L)
A predefined value for sqrt (2)
Detailed Description
template<typename FloatType>
struct MathConstants< FloatType >
Commonly used mathematical constants.
Member Data Documentation
pi
template<typename FloatType> FloatType MathConstants< FloatType >::pi = static_cast<FloatType> (3.141592653589793238L) static constexpr
A predefined value for Pi.
Referenced by degreesToRadians(), juce::dsp::Oscillator< SampleType >::initialise(), juce::dsp::Oscillator< SampleType >::process(), juce::dsp::Oscillator< SampleType >::processSample(), radiansToDegrees(), and juce::dsp::StateVariableFilter::Parameters< NumericType >::setCutOffFrequency().
twoPi
template<typename FloatType> FloatType MathConstants< FloatType >::twoPi = static_cast<FloatType> (2 * 3.141592653589793238L) static constexpr
A predefined value for 2 * Pi.
Referenced by juce::dsp::Phase< Type >::advance(), juce::dsp::Oscillator< SampleType >::process(), and juce::dsp::Oscillator< SampleType >::processSample().
halfPi
template<typename FloatType> FloatType MathConstants< FloatType >::halfPi = static_cast<FloatType> (3.141592653589793238L / 2) static constexpr
A predefined value for Pi / 2.
euler
template<typename FloatType> FloatType MathConstants< FloatType >::euler = static_cast<FloatType> (2.71828182845904523536L) static constexpr
A predefined value for Euler's number.
sqrt2
template<typename FloatType> FloatType MathConstants< FloatType >::sqrt2 = static_cast<FloatType> (1.4142135623730950488L) static constexpr
A predefined value for sqrt (2)
Referenced by juce::dsp::StateVariableFilter::Parameters< NumericType >::setCutOffFrequency().