JUCE: TabbedButtonBar::LookAndFeelMethods Struct Reference
TabbedButtonBar::LookAndFeelMethods Struct Reference abstract
juce_gui_basics » layout
This abstract base class is implemented by LookAndFeel classes to provide window drawing functionality.
Public Member Functions
virtual ~LookAndFeelMethods ()=default
virtual int getTabButtonSpaceAroundImage ()=0
virtual int getTabButtonOverlap (int tabDepth)=0
virtual int getTabButtonBestWidth (TabBarButton &, int tabDepth)=0
virtual Rectangle< int > getTabButtonExtraComponentBounds (const TabBarButton &, Rectangle< int > &textArea, Component &extraComp)=0
virtual void drawTabButton (TabBarButton &, Graphics &, bool isMouseOver, bool isMouseDown)=0
virtual Font getTabButtonFont (TabBarButton &, float height)=0
virtual void drawTabButtonText (TabBarButton &, Graphics &, bool isMouseOver, bool isMouseDown)=0
virtual void drawTabbedButtonBarBackground (TabbedButtonBar &, Graphics &)=0
virtual void drawTabAreaBehindFrontButton (TabbedButtonBar &, Graphics &, int w, int h)=0
virtual void createTabButtonShape (TabBarButton &, Path &path, bool isMouseOver, bool isMouseDown)=0
virtual void fillTabButtonShape (TabBarButton &, Graphics &, const Path &path, bool isMouseOver, bool isMouseDown)=0
virtual Button * createTabBarExtrasButton ()=0
Detailed Description
This abstract base class is implemented by LookAndFeel classes to provide window drawing functionality.
Constructor & Destructor Documentation
~LookAndFeelMethods()
virtual TabbedButtonBar::LookAndFeelMethods::~LookAndFeelMethods () virtual default
Member Function Documentation
getTabButtonSpaceAroundImage()
virtual int TabbedButtonBar::LookAndFeelMethods::getTabButtonSpaceAroundImage () pure virtual
Implemented in LookAndFeel_V2, and LookAndFeel_V3.
getTabButtonOverlap()
virtual int TabbedButtonBar::LookAndFeelMethods::getTabButtonOverlap (int tabDepth) pure virtual
Implemented in LookAndFeel_V2, and LookAndFeel_V3.
getTabButtonBestWidth()
virtual int TabbedButtonBar::LookAndFeelMethods::getTabButtonBestWidth (TabBarButton & , int tabDepth) pure virtual
Implemented in LookAndFeel_V2.
getTabButtonExtraComponentBounds()
virtual Rectangle< int > TabbedButtonBar::LookAndFeelMethods::getTabButtonExtraComponentBounds (const TabBarButton & , Rectangle< int > & textArea, Component & extraComp) pure virtual
Implemented in LookAndFeel_V2.
References Component::Component().
drawTabButton()
virtual void TabbedButtonBar::LookAndFeelMethods::drawTabButton (TabBarButton & , Graphics & , bool isMouseOver, bool isMouseDown) pure virtual
Implemented in LookAndFeel_V2, and LookAndFeel_V3.
References Component::isMouseOver().
getTabButtonFont()
virtual Font TabbedButtonBar::LookAndFeelMethods::getTabButtonFont (TabBarButton & , float height) pure virtual
Implemented in LookAndFeel_V2.
drawTabButtonText()
virtual void TabbedButtonBar::LookAndFeelMethods::drawTabButtonText (TabBarButton & , Graphics & , bool isMouseOver, bool isMouseDown) pure virtual
Implemented in LookAndFeel_V2.
References Component::isMouseOver().
drawTabbedButtonBarBackground()
virtual void TabbedButtonBar::LookAndFeelMethods::drawTabbedButtonBarBackground (TabbedButtonBar & , Graphics &) pure virtual
Implemented in LookAndFeel_V2.
References TabbedButtonBar::TabbedButtonBar().
drawTabAreaBehindFrontButton()
virtual void TabbedButtonBar::LookAndFeelMethods::drawTabAreaBehindFrontButton (TabbedButtonBar & , Graphics & , int w, int h) pure virtual
Implemented in LookAndFeel_V2, and LookAndFeel_V3.
References h, TabbedButtonBar::TabbedButtonBar(), and w.
createTabButtonShape()
virtual void TabbedButtonBar::LookAndFeelMethods::createTabButtonShape (TabBarButton & , Path & path, bool isMouseOver, bool isMouseDown) pure virtual
Implemented in LookAndFeel_V2.
References Component::isMouseOver().
fillTabButtonShape()
virtual void TabbedButtonBar::LookAndFeelMethods::fillTabButtonShape (TabBarButton & , Graphics & , const Path & path, bool isMouseOver, bool isMouseDown) pure virtual
Implemented in LookAndFeel_V2.
References Component::isMouseOver().
createTabBarExtrasButton()
virtual Button * TabbedButtonBar::LookAndFeelMethods::createTabBarExtrasButton () pure virtual
Implemented in LookAndFeel_V2.