JUCE: ConcertinaPanel::LookAndFeelMethods Struct Reference
ConcertinaPanel::LookAndFeelMethods Struct Reference abstract
juce_gui_basics » layout
This abstract base class is implemented by LookAndFeel classes.
Public Member Functions
virtual ~LookAndFeelMethods ()=default
virtual void drawConcertinaPanelHeader (Graphics &, const Rectangle< int > &area, bool isMouseOver, bool isMouseDown, ConcertinaPanel &, Component &)=0
Detailed Description
This abstract base class is implemented by LookAndFeel classes.
Constructor & Destructor Documentation
~LookAndFeelMethods()
virtual ConcertinaPanel::LookAndFeelMethods::~LookAndFeelMethods () virtual default
Member Function Documentation
drawConcertinaPanelHeader()
virtual void ConcertinaPanel::LookAndFeelMethods::drawConcertinaPanelHeader (Graphics & , const Rectangle< int > & area, bool isMouseOver, bool isMouseDown, ConcertinaPanel & , Component &) pure virtual
Implemented in LookAndFeel_V2, LookAndFeel_V3, and LookAndFeel_V4.
References Component::Component(), ConcertinaPanel::ConcertinaPanel(), and Component::isMouseOver().