JUCE: juce::midi_ci::Message::ProcessMidiMessageReportResponse Struct Reference
juce::midi_ci::Message::ProcessMidiMessageReportResponse Struct Reference
juce_midi_ci » ci
See the MIDI-CI specification.
Public Member Functions
auto tie () const
bool operator== (const ProcessMidiMessageReportResponse &x) const
bool operator!= (const ProcessMidiMessageReportResponse &x) const
Public Attributes
std::byte messageDataControl {}
std::byte requestedMessages {}
std::byte channelControllerMessages {}
std::byte noteDataMessages {}
Detailed Description
See the MIDI-CI specification.
Member Function Documentation
tie()
auto juce::midi_ci::Message::ProcessMidiMessageReportResponse::tie () const
References channelControllerMessages, messageDataControl, noteDataMessages, and requestedMessages.
Referenced by operator==().
operator==()
bool juce::midi_ci::Message::ProcessMidiMessageReportResponse::operator== (const ProcessMidiMessageReportResponse & x) const
References tie(), and x.
Referenced by operator!=().
operator!=()
bool juce::midi_ci::Message::ProcessMidiMessageReportResponse::operator!= (const ProcessMidiMessageReportResponse & x) const
References operator==(), and x.
Member Data Documentation
messageDataControl
std::byte juce::midi_ci::Message::ProcessMidiMessageReportResponse::messageDataControl {}
Referenced by tie().
requestedMessages
std::byte juce::midi_ci::Message::ProcessMidiMessageReportResponse::requestedMessages {}
Referenced by tie().
channelControllerMessages
std::byte juce::midi_ci::Message::ProcessMidiMessageReportResponse::channelControllerMessages {}
Referenced by tie().
noteDataMessages
std::byte juce::midi_ci::Message::ProcessMidiMessageReportResponse::noteDataMessages {}
Referenced by tie().