JUCE: CallOutBox::LookAndFeelMethods Struct Reference
CallOutBox::LookAndFeelMethods Struct Reference abstract
juce_gui_basics » windows
This abstract base class is implemented by LookAndFeel classes.
Public Member Functions
virtual ~LookAndFeelMethods ()=default
virtual void drawCallOutBoxBackground (CallOutBox &, Graphics &, const Path &, Image &)=0
virtual int getCallOutBoxBorderSize (const CallOutBox &)=0
virtual float getCallOutBoxCornerSize (const CallOutBox &)=0
Detailed Description
This abstract base class is implemented by LookAndFeel classes.
Constructor & Destructor Documentation
~LookAndFeelMethods()
virtual CallOutBox::LookAndFeelMethods::~LookAndFeelMethods () virtual default
Member Function Documentation
drawCallOutBoxBackground()
virtual void CallOutBox::LookAndFeelMethods::drawCallOutBoxBackground (CallOutBox & , Graphics & , const Path & , Image &) pure virtual
Implemented in LookAndFeel_V2, and LookAndFeel_V4.
References CallOutBox::CallOutBox().
getCallOutBoxBorderSize()
virtual int CallOutBox::LookAndFeelMethods::getCallOutBoxBorderSize (const CallOutBox &) pure virtual
Implemented in LookAndFeel_V2.
References CallOutBox::CallOutBox().
getCallOutBoxCornerSize()
virtual float CallOutBox::LookAndFeelMethods::getCallOutBoxCornerSize (const CallOutBox &) pure virtual
Implemented in LookAndFeel_V2.
References CallOutBox::CallOutBox().