JUCE: juce::midi_ci::Message::ProfileInquiry Struct Reference
juce::midi_ci::Message::ProfileInquiry Struct Reference
juce_midi_ci » ci
See the MIDI-CI specification.
Public Member Functions
auto tie () const
bool operator== (const ProfileInquiry &x) const
bool operator!= (const ProfileInquiry &x) const
Detailed Description
See the MIDI-CI specification.
Member Function Documentation
tie()
auto juce::midi_ci::Message::ProfileInquiry::tie () const
Referenced by operator==().
operator==()
bool juce::midi_ci::Message::ProfileInquiry::operator== (const ProfileInquiry & x) const
References tie(), and x.
Referenced by operator!=().
operator!=()
bool juce::midi_ci::Message::ProfileInquiry::operator!= (const ProfileInquiry & x) const
References operator==(), and x.