JUCE: Label::LookAndFeelMethods Struct Reference
Label::LookAndFeelMethods Struct Reference abstract
juce_gui_basics » widgets
This abstract base class is implemented by LookAndFeel classes to provide label drawing functionality.
Public Member Functions
virtual ~LookAndFeelMethods ()=default
virtual void drawLabel (Graphics &, Label &)=0
virtual Font getLabelFont (Label &)=0
virtual BorderSize< int > getLabelBorderSize (Label &)=0
Detailed Description
This abstract base class is implemented by LookAndFeel classes to provide label drawing functionality.
Constructor & Destructor Documentation
~LookAndFeelMethods()
virtual Label::LookAndFeelMethods::~LookAndFeelMethods () virtual default
Member Function Documentation
drawLabel()
virtual void Label::LookAndFeelMethods::drawLabel (Graphics & , Label &) pure virtual
Implemented in LookAndFeel_V2.
References Label::Label().
getLabelFont()
virtual Font Label::LookAndFeelMethods::getLabelFont (Label &) pure virtual
Implemented in LookAndFeel_V2.
References Label::Label().
getLabelBorderSize()
virtual BorderSize< int > Label::LookAndFeelMethods::getLabelBorderSize (Label &) pure virtual
Implemented in LookAndFeel_V2.
References Label::Label().