JUCE: ComboBox::LookAndFeelMethods Struct Reference
ComboBox::LookAndFeelMethods Struct Reference abstract
juce_gui_basics » widgets
This abstract base class is implemented by LookAndFeel classes to provide ComboBox functionality.
Public Member Functions
virtual ~LookAndFeelMethods ()=default
virtual void drawComboBox (Graphics &, int width, int height, bool isButtonDown, int buttonX, int buttonY, int buttonW, int buttonH, ComboBox &)=0
virtual Font getComboBoxFont (ComboBox &)=0
virtual Label * createComboBoxTextBox (ComboBox &)=0
virtual void positionComboBoxText (ComboBox &, Label &labelToPosition)=0
virtual PopupMenu::Options getOptionsForComboBoxPopupMenu (ComboBox &, Label &)=0
virtual void drawComboBoxTextWhenNothingSelected (Graphics &, ComboBox &, Label &)=0
Detailed Description
This abstract base class is implemented by LookAndFeel classes to provide ComboBox functionality.
Constructor & Destructor Documentation
~LookAndFeelMethods()
virtual ComboBox::LookAndFeelMethods::~LookAndFeelMethods () virtual default
Member Function Documentation
drawComboBox()
virtual void ComboBox::LookAndFeelMethods::drawComboBox (Graphics & , int width, int height, bool isButtonDown, int buttonX, int buttonY, int buttonW, int buttonH, ComboBox &) pure virtual
Implemented in LookAndFeel_V1, LookAndFeel_V2, LookAndFeel_V3, and LookAndFeel_V4.
References ComboBox::ComboBox().
getComboBoxFont()
virtual Font ComboBox::LookAndFeelMethods::getComboBoxFont (ComboBox &) pure virtual
Implemented in LookAndFeel_V1, LookAndFeel_V2, and LookAndFeel_V4.
References ComboBox::ComboBox().
createComboBoxTextBox()
virtual Label * ComboBox::LookAndFeelMethods::createComboBoxTextBox (ComboBox &) pure virtual
Implemented in LookAndFeel_V2.
References ComboBox::ComboBox().
positionComboBoxText()
virtual void ComboBox::LookAndFeelMethods::positionComboBoxText (ComboBox & , Label & labelToPosition) pure virtual
Implemented in LookAndFeel_V2, and LookAndFeel_V4.
References ComboBox::ComboBox().
getOptionsForComboBoxPopupMenu()
virtual PopupMenu::Options ComboBox::LookAndFeelMethods::getOptionsForComboBoxPopupMenu (ComboBox & , Label &) pure virtual
Implemented in LookAndFeel_V2.
References ComboBox::ComboBox().
drawComboBoxTextWhenNothingSelected()
virtual void ComboBox::LookAndFeelMethods::drawComboBoxTextWhenNothingSelected (Graphics & , ComboBox & , Label &) pure virtual
Implemented in LookAndFeel_V2.
References ComboBox::ComboBox().